### ISSUE TITLE
Failure to execute Peak2GeneLinkage

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#451] opened 2020-12-04 18:09 UTC
> proj5 <- addPeak2GeneLinks(
+     ArchRProj = proj5,
+     reducedDims = "IterativeLSI"
+ )
ArchR logging to : ArchRLogs/ArchR-addPeak2GeneLinks-95552b6fd397-Date-2020-12-04_Time-12-03-16.log
If there is an issue, please report to github with logFile!
2020-12-04 12:03:16 : Getting Available Matrices, 0.002 mins elapsed.
2020-12-04 12:03:16 : Filtered Low Prediction Score Cells (1357 of 7272, 0.187), 0.002 mins elapsed.
2020-12-04 12:03:17 : Computing KNN, 0.004 mins elapsed.
2020-12-04 12:03:17 : Identifying Non-Overlapping KNN pairs, 0.01 mins elapsed.
2020-12-04 12:03:21 : Identified 493 Groupings!, 0.076 mins elapsed.
2020-12-04 12:03:21 : Getting Group RNA Matrix, 0.077 mins elapsed.
2020-12-04 12:04:10 : Getting Group ATAC Matrix, 0.888 mins elapsed.
2020-12-04 12:05:15 : Normalizing Group Matrices, 1.975 mins elapsed.
2020-12-04 12:05:21 : Finding Peak Gene Pairings, 2.081 mins elapsed.
2020-12-04 12:05:22 : Computing Correlations, 2.088 mins elapsed.
2020-12-04 12:05:48 : Completed Peak2Gene Correlations!, 2.533 mins elapsed.
ArchR logging successful to : ArchRLogs/ArchR-addPeak2GeneLinks-95552b6fd397-Date-2020-12-04_Time-12-03-16.log
> p2g <- getPeak2GeneLinks(
+     ArchRProj = proj5,
+     corCutOff = 0.45,
+     resolution = 1,
+     returnLoops = FALSE
+ )
> p2g
DataFrame with 0 rows and 6 columns
> metadata(p2g)[[1]]
GRanges object with 189661 ranges and 0 metadata columns:
           seqnames              ranges strand
              <Rle>           <IRanges>  <Rle>
       [1]     chr1     3117281-3117781      *
       [2]     chr1     3191088-3191588      *
       [3]     chr1     3372559-3373059      *
       [4]     chr1     3395459-3395959      *
       [5]     chr1     3399909-3400409      *
       ...      ...                 ...    ...
  [189657]     chrX 169899189-169899689      *
  [189658]     chrX 169902721-169903221      *
  [189659]     chrX 169903598-169904098      *
  [189660]     chrX 169906143-169906643      *
  [189661]     chrX 169937046-169937546      *
  -------
  seqinfo: 20 sequences from an unspecified genome; no seqlengths
> p2g <- getPeak2GeneLinks(
+     ArchRProj = proj5,
+     corCutOff = 0.45,
+     resolution = 1,
+     returnLoops = TRUE
+ )
Error in .validInput(input = start, name = "start", valid = c("integer")) : 
  Input value for 'start' is not a integer, (start = numeric) please supply valid input!
In addition: Warning message:
In min(abs(c(input%%1, input%%1 - 1)), na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
> 
> p2g[[1]]
integer(0)

**Comment by rcorces** [comment] 2020-12-04 18:37
duplicate of #442 and #385 
see solutions there

**Closed by rcorces** 2020-12-04 18:37 UTC
