### ISSUE TITLE
Aesthetics of the geneTrack

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#426] opened 2020-11-19 16:41 UTC
Hi,
 How can I increase the fontsize in the **geneTrack**  segment when using plotBrowserTrack.
I have included baseSize and scTileSize and facetbaseSize attributes but the geneTrack gene name font size remained unchanged. Suggestions?

Thank you!!

**Comment by rcorces** [comment] 2020-11-20 01:52
adobe illustrator :)

This is not currently possible. It would be trivial to enable but I have a feeling that it might have been disabled to prevent weird issues with the gene track.

@jgranja24  -  I think the problem is that the call to `.geneTracks()` doesnt pass along the `baseSize` parameter:
https://github.com/GreenleafLab/ArchR/blob/2f022a448d8248a0f9afb33419bcbaeafe7731c0/R/ArchRBrowser.R#L872

**Comment by sylestiel** [comment] 2020-11-20 02:03
Ok. Thanks for the info.

**Comment by rcorces** [comment] 2020-11-20 02:04
I'm going to leave this open for now incase @jgranja24 wants to give his 2 cents.

**Comment by jgranja24** [comment] 2020-11-26 07:31
This unfortunately wont work with `baseSize` parameter because you need to change the `label size` for geneTracks. I dont think we want to add these at this moment to keep things as simple as possible. If you think there is a strong need for this please let us know.

**Comment by jgranja24** [comment] 2020-11-26 07:31
Closing this issue feel free to further comment/open new issues!

Best

Jeff

**Closed by jgranja24** 2020-11-26 07:31 UTC
Labels: documentation
