### ISSUE TITLE
Add palette option to plotBrowserTrack

### ISSUE THREAD

**Issue by kwells4** [GreenleafLab/ArchR#176] opened 2020-05-27 17:22 UTC
Would it be possible to add a palette option to plotBrowserTracks?

**Comment by rcorces** [comment] 2020-05-28 17:02
Thanks for the suggestion.
@jgranja24 - this seems trivial. the hidden `.bulkTrack()` function can accept a palette via `pal` but we just havent enabled that function.

**Comment by kwells4** [comment] 2020-05-28 17:04
Yup, I just added pal to the .bulkTrack call in my forked version and it worked perfectly.

**Comment by jgranja24** [comment] 2020-05-28 17:33
Yeah Ill update it, I enabled more options for the ArchRBrowser that are not available in plotBrowserTrack

**Comment by jgranja24** [comment] 2020-05-30 07:38
This is now available in the dev version. I will add it to master shortly.

**Comment by jgranja24** [comment] 2020-05-31 18:56
This is available in master. Closing now, feel free to re-open if further issues.

Best

Jeff

**Closed by jgranja24** 2020-05-31 18:56 UTC
Labels: enhancement

**Comment by lunazere** [comment] 2020-10-13 05:57
Would it be possible to add a palette option also for the features?

I have call peaks using addReproduciblePeakSet on 4 specific clusters, and I would like to plot them separately. To make easier the visualization, I would like that the peaks and the pseudo-bulk track of cell type A are plotted with the same colour (and the same with the rest of cell types). Is there any way this can be done?

Thanks!

**Comment by rcorces** [comment] 2020-10-13 14:37
@lunazere Thanks for posting. This looks like a duplicate of #337 . If you agree, please cross-post there since this issue is closed.

**Comment by RinconFer** [comment] 2023-06-21 19:10
Doing some more test I think that the peak plot is actually using the stallion palette set independently of whatever palette you are trying to use for the track plots. As you can see in the image below the colors in the peaks are the first to colors in the stallion palette, which have nothing in common with my palette.
![image](https://github.com/GreenleafLab/ArchR/assets/62716429/9b00fee9-cbf3-4e7b-b57e-c75b1d48c134)

Additionally, but maybe this need a separate issue, you can see that the CoAccessibility plot is showing links between peaks that are not in the peak plot (since I am only showing significatively enriched peaks for each cluster). Is it possible to restrict the CoAccessibility plot (and the Gene2PeakLink plot) to peaks appearing in the Peaks plot?

**Comment by rcorces** [comment] 2023-06-26 19:01
Apologies for the delay in replying. You are correct - we do not currently have a way for you to specify the palette for feature tracks.

Regarding your question for Co-accessibility, you can always manually manipulate the coaccessibility links and pass them as a new loopTrack
