### ISSUE TITLE
bug in addPeak2GeneLinks function

### ISSUE THREAD

**Issue by JLiLab** [GreenleafLab/ArchR#385] opened 2020-10-31 19:57 UTC
In the current version (ArchR_1.0.0 ), there seems a bug in IntegrativeAnalysis.R (line 1176): 
o$TStat <- (o$correlation / sqrt((max(1-o$Correlation^2, 0.00000000000000001))/(ncol(seATAC)-2))) #T-statistic P-value

It differs from "o$TStat <- (o$Correlation / sqrt((1-o$Correlation^2)/(ncol(seATAC)-2)))" in previous versions. 

J

**Comment by jgranja24** [comment] 2020-11-02 16:28
Nice catch i just updated this on master. Thanks!

https://github.com/GreenleafLab/ArchR/blob/b6b42107098ecdfafc064855bcefe32844a0027c/R/IntegrativeAnalysis.R#L1176

**Comment by jgranja24** [comment] 2020-11-02 16:28
Closing this issue thanks for the help!

**Comment by JLiLab** [comment] 2020-11-02 18:50
Thank you for the quick action! I tested the new version but found that all the peak2gene pairs (>70,000 pairs) determined by the previous version were disappeared. Somethings seem not right.

**Comment by biojiangke** [comment] 2020-11-04 15:45
I'll second this. After the update, the previous peak2gene pairs disappeared and "getPeak2GeneLinks" would return an error message: "Input value for 'start' is not a integer, (start = numeric) please supply valid input!". This seems to mean the links are empty.

**Comment by jessie-wangjie** [comment] 2020-11-18 18:57
I got the same error, the correlation calculated had a lot NAs
o$Correlation <- rowCorCpp(as.integer(o$A), as.integer(o$B), assay(seATAC), assay(seRNA))

**Comment by JLiLab** [comment] 2020-11-18 19:39
If you change the code back to the original: o$TStat <- (o$Correlation / sqrt((1-o$Correlation^2)/(ncol(seATAC)-2))), you will get the same result. Not sure why though

**Comment by YanFang0620** [comment] 2020-11-27 15:32
Hi,
I tried to follow the tutorial steps:

p2g <- getPeak2GeneLinks(
  ArchRProj = projHeme5,
  corCutOff = 0.45,
  resolution = 1,
  returnLoops = TRUE
)

But I got an error message:

Error in .validInput(input = start, name = "start", valid = c("integer")) : 
  Input value for 'start' is not a integer, (start = numeric) please supply valid input!
In addition: Warning message:
In min(abs(c(input%%1, input%%1 - 1)), na.rm = TRUE) :
  no non-missing arguments to min; returning Inf

It seems like if I set returnLoops = TRUE, the error will come out. But if I set it to FALSE, it will be OK.
I have no idea what's the problem is? 
I will appreciate if someone could help me to solve this problem.

**Comment by rcorces** [comment] 2020-11-27 15:58
@YanFang0620 - this is unrelated to this issue. Please create a new issue and **upload your log file** as requested in the issue template.

**Comment by jgranja24** [comment] 2020-11-29 01:17
Sorry I think the bug is now fixed in the new release branch -----

To install --
`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories())
`

The change --
`  o$TStat <- (o$Correlation / sqrt((pmax(1-o$Correlation^2, 0.00000000000000001, na.rm = TRUE))/(ncol(seATAC)-2))) #T-statistic P-value`

**Comment by YanFang0620** [comment] 2020-11-29 01:46
> Sorry I think the bug is now fixed in the new release branch -----
> 
> To install --
> `devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories()) `
> 
> The change --
> ` o$TStat <- (o$Correlation / sqrt((pmax(1-o$Correlation^2, 0.00000000000000001, na.rm = TRUE))/(ncol(seATAC)-2))) #T-statistic P-value`

Thank you for your suggestion!
I think the new branch doesn't work either. When I ran the following codes with new release branch of ArchR, it still got error:
```
> p2g <- getPeak2GeneLinks(
  ArchRProj = projHeme5,
  corCutOff = 0.1,
  resolution = 1,
  returnLoops = TRUE
)
```

![image](https://user-images.githubusercontent.com/54081315/100529963-64d08f80-31ba-11eb-8e2b-738ffd443e6d.png)

```
> packageVersion("ArchR")
[1] ‘1.0.1’
```

**Comment by jgranja24** [comment] 2020-11-29 02:06
Did you re-run `addPeak2GeneLinks`?

**Comment by YanFang0620** [comment] 2020-11-29 02:37
> Did you re-run `addPeak2GeneLinks`?

I'm so sorry.  It worked after re-run `addPeak2GeneLinks`! Thank you so much your patience!

**Comment by jgranja24** [comment] 2020-11-29 08:03
Great! Closing this issue. Feel free to open new issues!

**Closed by jgranja24** 2020-11-29 08:03 UTC
Labels: bug

**Comment by sylestiel** [comment] 2020-12-04 18:02
@YanFang0620 
@jgranja24 
How did you overcome this issue?  Not understanding what the workaround was?

Thanks

**Comment by rcorces** [comment] 2020-12-04 18:39
@sylestiel - just reinstall using the new development branch.
`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories())`
then re-run `addPeak2GeneLinks()`
