### ISSUE TITLE
The nadir of the volcano plot is not at Log2FC=0

### ISSUE THREAD

**Issue by dyxmvp** [GreenleafLab/ArchR#1252] opened 2022-01-12 00:44 UTC
Hello,

I found that plot Volcano plots using the markerPlot() function sometimes looks strange, which was not properly centered for Fold-change. I'm not sure why the nadir of the volcano is not at Log2FC=0, and the Log2FC=0 has a smaller FDR? I think the issue might be from the getMarkerFeatures() function, so I attached the log file.

![image](https://user-images.githubusercontent.com/13945175/149043136-d27c2421-a4d5-444c-9f97-c032487507fc.png)

I have already searched previous Issues and Discussions, and the tutorial code and dataset worked well. 
[ArchR-getMarkerFeatures-4c8e5e6ec6b4-Date-2022-01-11_Time-11-45-18.log](https://github.com/GreenleafLab/ArchR/files/7850723/ArchR-getMarkerFeatures-4c8e5e6ec6b4-Date-2022-01-11_Time-11-45-18.log)

Thanks!

**Comment by rcorces** [comment] 2022-01-12 00:45
Hi @dyxmvp! Thanks for using ArchR! I am currently on paternity leave and will not be responding to any issues or discussion threads. I plan to be back in late January and will do my best to address your issue then.<br />
In the meantime, it is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment. Search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.<br />
If you are able to solve your issue, please post the solution and close this issue post. <br />
Otherwise __if you would like my help when I return, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment] 2022-03-20 04:43
Sorry for not following up on this sooner. This is very odd behavior. If you are still experiencing this issue, please post here and I will attempt to help. I'm closing this for now since it is quite old, but happy to re-open as needed.

**Closed by rcorces** 2022-03-20 04:43 UTC
Labels: bug
