### ISSUE TITLE
createArrowFiles fails with no fragments detected

### ISSUE THREAD

**Issue by cnk113** [GreenleafLab/ArchR#770] opened 2021-05-23 23:20 UTC
[ArchR-createArrows-a341127258a65-Date-2021-05-23_Time-15-40-53.log](https://github.com/GreenleafLab/ArchR/files/6529038/ArchR-createArrows-a341127258a65-Date-2021-05-23_Time-15-40-53.log)
[ArchR-createArrows-a34115294cf68-Date-2021-05-23_Time-16-08-25.log](https://github.com/GreenleafLab/ArchR/files/6529074/ArchR-createArrows-a34115294cf68-Date-2021-05-23_Time-16-08-25.log)

When I try to create the ArrowFiles with the outputs from the new Cellranger atac 2 fragments it seems to be failing, I tried both w/ and w/o validBarcodes and on different samples set since I thought that was the issue. I've successfully been able to create the fragments file w/ the output from CR1.2.

**Comment by rcorces** [comment] 2021-05-24 03:52
Yes - I'm aware of this problem but have not implemented a solution yet. Thanks for your patience. In the meantime, you can manually edit your fragment files and the re-zip them (using **bgzip**!!)

**Comment by cnk113** [comment] 2021-05-24 19:27
Is it just unzip and rezip? I tried this with bgzip and reindexing with tabix and it still failed.

**Comment by rcorces** [comment] 2021-05-24 19:59
No. 10x has added a header to the fragment file as of cellranger-atac v2.0.0. Until we patch a fix, you need to remove that header. For example (there are probably faster ways to do this but this works):
```
zcat fragments.tsv.gz | grep -v ^\# | bgzip >fragments_fixed.tzv.gz
```
And then used the file without the header as input to ArchR.

**Comment by cnk113** [comment] 2021-05-24 21:06
So even with that fix I'm still getting the same error w/ no fragments found.
[ArchR-createArrows-c1db277ca4032-Date-2021-05-24_Time-14-03-55.log](https://github.com/GreenleafLab/ArchR/files/6534997/ArchR-createArrows-c1db277ca4032-Date-2021-05-24_Time-14-03-55.log)

**Comment by rcorces** [comment] 2021-05-24 22:23
I'm actually unable to reproduce any errors or abnormal behavior with the new 10x frag files from cellranger-atac v2.0. I had heard an anecdotal complaint about this but I dont think there is any problem. Your issue is unlikely to be related to the new format and more likely related to some other problem with your input. perhaps you can post more information

**Comment by rcorces** [comment] 2021-05-29 12:40
Closing but feel free to comment here again if you need additional help

**Comment by cnk113** [comment] 2021-06-01 21:10
So this error was from release_.1.0.2, I rolled back to 1.0.1.
I'm assuming  one of the commits in creating the arrow file broke this.

**Comment by rcorces** [comment] 2021-06-03 04:10
I just tested this in release_1.0.2 and was still not able to encounter an error. If anyone runs into this again, let me know and perhaps be prepared to provide a copy of your fragment file in case something unexpected is going on.

**Comment by Zepeng-Mu** [comment] 2021-07-01 19:31
Hi, I also encountered this error.
The last time I generated an arrow files was in May 30. And according to log the release I used was Archr 1.0.1.
Now I got some new data and found that I consistently get this error message on my new data as well as the old data. I'm using release 1.0.2 now.

It's not due to my fragment file because I can load them using Rsamtools scanTabix by myself. I compared 1.0.1 and 1.0.2 and found that these three lines are newly added:
https://github.com/GreenleafLab/ArchR/blob/0d77da238cbcf6f4fa0c8daac4cec7df34c63a44/R/CreateArrow.R#L1263-L1265

These were not in 1.0.1, and as my understanding the columns are `dt` are V1-V5. RG, start, and end were not defined yet.
Could this be the reason why there are no fragments detected?
I still want to use v1.0.2 because I remember there was another bug fix for this release.

Thanks so much!

**Comment by rcorces** [comment] 2021-07-01 20:12
@Zepeng-Mu - This seems possible. It looks like the code that applied to bam input was copied to also apply to fragment input and the column names might not have been correct. I have not had problems with this on my end and I'm not sure why that would be.
I made your suggested change in a new branch off of `release_1.0.2` via https://github.com/GreenleafLab/ArchR/commit/b0a48c86c77f9af66ac7254d782dde917e817284

Can you try installing that branch and let me know if it fixes your problem?
```
devtools::install_github("GreenleafLab/ArchR", ref="dev_210701_createArrow", repos = BiocManager::repositories())
```

**Comment by Zepeng-Mu** [comment] 2021-07-01 23:18
Hi,
I tried the new branch and now there's another error:

```
ArchR logging to : ArchRLogs/ArchR-createArrows-52a046000bb5-Date-2021-07-01_Time-17-18-44.log
If there is an issue, please report to github with logFile!
2021-07-01 17:18:45 : Batch Execution w/ safelapply!, 0 mins elapsed.
2021-07-01 17:18:46 : (PBMC-5-6-7-8 : 1 of 1) Arrow Exists! Overriding since not completed!, 0.004 mins elapsed.
2021-07-01 17:18:46 : (PBMC-5-6-7-8 : 1 of 1) Reading In Fragments from inputFiles (readMethod = tabix), 0.006 mins elapsed.
2021-07-01 17:18:46 : (PBMC-5-6-7-8 : 1 of 1) Tabix Bed To Temporary File, 0.007 mins elapsed.
2021-07-01 17:54:16 : (PBMC-5-6-7-8 : 1 of 1) Successful creation of Temporary File, 35.508 mins elapsed.
2021-07-01 17:54:16 : (PBMC-5-6-7-8 : 1 of 1) Creating ArrowFile From Temporary File, 35.508 mins elapsed.
2021-07-01 18:11:18 : (PBMC-5-6-7-8 : 1 of 1) Successful creation of Arrow File, 52.552 mins elapsed.
2021-07-01 18:14:18 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
ArchR logging successful to : ArchRLogs/ArchR-createArrows-52a046000bb5-Date-2021-07-01_Time-17-18-44.log
Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  1 function calls resulted in an error
```

```
************************************************************
2021-07-01 18:13:38 : ERROR Found in .fastTSSCounts for (PBMC-5-6-7-8 : 1 of 1)
LogFile = ArchRLogs/ArchR-createArrows-52a046000bb5-Date-2021-07-01_Time-17-18-44.log

<simpleError in .getFragsFromArrow(ArrowFile = ArrowFile, chr = names(featureList)[x],     out = "IRanges", cellNames = cellNames): Chromosome NA not in ArrowFile! Available Chromosomes are : chr1,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr2,chr20,chr21,chr22,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chrX,chrY>

2021-07-01 18:13:38 : errorList, Class = list

errorList$x: length = 1
[1] 24


errorList$chr: length = 1
[1] NA


errorList$fragments: length = 1
[1] "Error with Fragments!"


errorList$features: length = 1
[1] "Error with Features!"



************************************************************
```

Thanks!

**Comment by Zepeng-Mu** [comment] 2021-07-02 00:20
But I just realized the error also happens with release 1.0.1. Seems that mclapply failed on some cores.

**Comment by rcorces** [comment] 2021-07-02 00:27
This seems like a problem with your fragment file input. It seems like some entries lack a valid chromosome

**Comment by Zepeng-Mu** [comment] 2021-07-02 01:21
Hi, this does seem to be the case if I quickly check the chromosome names:
```
➜ tabix -l fragments.tsv.gz
chr1
chr10
chr11
chr12
chr13
chr14
chr15
chr16
chr17
chr18
chr19
chr2
chr20
chr21
chr22
chr3
chr4
chr5
chr6
chr7
chr8
chr9
chrX
chrY
```
I will continue to explore to see what's going on.
Thanks!

**Comment by rcorces** [comment] 2021-07-02 03:45
can you clarify if you are getting this error also with the tutorial dataset fragment files? If not, it is likely a problem with your input.

**Comment by Zepeng-Mu** [comment] 2021-07-02 17:42
Hi, indeed it's a problem with my input.
I used a custom gene annotation which lacks `chrY` compared to the default one. I wonder why `ArchR:::.availableChr(ArrowFiles)` gives me `"chr1"  "chr10" "chr11" "chr12" "chr13" "chr14" "chr15" "chr16" "chr17" "chr18" "chr19" "chr2"  "chr20" "chr21" "chr22" "chr3"  "chr4"  "chr5"  "chr6"  "chr7"  "chr8"  "chr9"  "chrX"  "chrY"` since `createArrowFiles` by default has `excludeChr=c("chrM", "chrY")`.
But other than this, I don't have any problem generating arrow files now.
Thanks so much!

**Comment by rcorces** [comment] 2021-07-03 13:09
Glad this has been resolved. The default to exclude chrY prevents users from inadvertently allowing sex differences that are specific to males to appear as signal in their data.

**Comment by rcorces** [comment] 2021-08-18 17:34
reopening this to ensure that the `dev_210701_createArrow` branch gets properly merged because I lost track of this.

**Closed** 2021-10-09 21:50 UTC
Labels: bug
