### ISSUE TITLE
error during motif foot-printing

### ISSUE THREAD

**Issue by aa20g217** [GreenleafLab/ArchR#716] opened 2021-04-27 10:34 UTC
Hey,

When I am using getFootprints() from ArchR I am getting this error:
`error in evaluating the argument ‘values’ in selecting a method for function ‘Rle’: Error in h5checktypeOrOpenLoc(). Cannot open file. File ‘/Users/akshay/Desktop/PhD/Projetcs-extra/archR/HemeTutorial/GroupCoverages/Clusters2/B._.scATAC_BMMC_R1.insertions.coverage.h5’ does not exist.`

It seems that getFootprints() is trying to access a file that is not available on my system because I ran ArchR on a different system and moved all saved ArchR files (save-ProjHeme1,save-ProjHeme2, etc.) only. In principle, getFootprints() require save-ProjHeme5 (naming from ArchR tutorial) ArchR object. Therefore, I will highly appreciate it if you could tell us if there a way to plot motif footprints with save-ProjHeme5 only?

Thank you.

**Comment by ankushs0128** [comment] 2021-04-27 10:53
Following! i am also having the same issue for the Motif - footprinting

**Comment by rcorces** [comment] 2021-04-27 15:54
I believe this is caused by the same bug reported here which has not been fixed yet
https://github.com/GreenleafLab/ArchR/issues/529
If you agree, feel free to close this issue and cross-post there.

**Closed** 2021-04-27 16:14 UTC
Labels: bug
