### ISSUE TITLE
Bug in filterdoublet function:as.POSIXct.numeric(e) : 'origin' must be supplied

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#249] opened 2020-07-17 04:38 UTC
Hi,

I'm getting an error from filterDoublets function.
I think it's related to the date and time formating. I would be happy to have your comments on it.
Here is the error:
```

filterDoublets(projHeme1)
Filtering 16991 cells from ArchRProject!
	S307 : 634 of 7963 (8%)
	S309 : 735 of 8575 (8.6%)
	S324 : 717 of 8470 (8.5%)
	S318 : 181 of 4264 (4.2%)
	S306 : 249 of 4998 (5%)
	S301 : 498 of 7059 (7.1%)
	S317 : 450 of 6710 (6.7%)
	S303 : 1199 of 10953 (10.9%)
	S322 : 319 of 5651 (5.6%)
	S211 : 298 of 5462 (5.5%)
	S225 : 57 of 2394 (2.4%)
	S128 : 692 of 8320 (8.3%)
	S127 : 773 of 8793 (8.8%)
	S226 : 325 of 5707 (5.7%)
	S319 : 338 of 5816 (5.8%)
	S228 : 433 of 6587 (6.6%)
	S323 : 0 of 5977 (0%)
Error in as.POSIXct.numeric(e) : 'origin' must be supplied
> as.Date(15103, origin="1970-01-01")

```

**Comment by jmchan88** [comment] 2020-07-21 15:49
I am getting the same exact error too:

Filtering 286 cells from ArchRProject!
        Lx108_chemoresistant_T_1b : 286 of 4374 (6.5%)
Error in as.POSIXct.numeric(e) : 'origin' must be supplied
Calls: filterDoublets ... unlist -> lapply -> FUN -> as.POSIXct -> as.POSIXct.numeric
Execution halted

**Comment by liaoshengyou** [comment] 2020-07-22 20:25
ArchRProj <- ArchR::addProjectSummary(ArchRProj = ArchRProj, name = "filterDoublets", 
                                 summary = c(Date = as.character(Sys.time()), cutEnrich = cutEnrich, 
                                             cutScore = cutScore, filterRatio = filterRatio))

**Comment by liaoshengyou** [comment] 2020-07-22 20:26
validInput = getAnywhere(.validInput) 
validInput = function (input = NULL, name = NULL, valid = NULL) 
{
  valid <- unique(valid)
  if (is.character(valid)) {
    valid <- tolower(valid)
  }
  else {
    stop("Validator must be a character!")
  }
  if (!is.character(name)) {
    stop("name must be a character!")
  }
  if ("null" %in% tolower(valid)) {
    valid <- c("null", valid[which(tolower(valid) != 
                                     "null")])
  }
  av <- FALSE
  for (i in seq_along(valid)) {
    vi <- valid[i]
    if (vi == "integer" | vi == "wholenumber") {
      if (all(is.numeric(input))) {
        cv <- min(abs(c(input%%1, input%%1 - 1))) < .Machine$double.eps^0.5
      }
      else {
        cv <- FALSE
      }
    }
    else if (vi == "null") {
      cv <- is.null(input)
    }
    else if (vi == "bool" | vi == "boolean" | 
             vi == "logical") {
      cv <- is.logical(input)
    }
    else if (vi == "numeric") {
      cv <- is.numeric(input)
    }
    else if (vi == "vector") {
      cv <- is.vector(input)
    }
    else if (vi == "matrix") {
      cv <- is.matrix(input)
    }
    else if (vi == "sparsematrix") {
      cv <- is(input, "dgCMatrix")
    }
    else if (vi == "character") {
      cv <- is.character(input)
    }
    else if (vi == "factor") {
      cv <- is.factor(input)
    }
    else if (vi == "rlecharacter") {
      cv1 <- is(input, "Rle")
      if (cv1) {
        cv <- is(input@values, "factor") || is(input@values, 
                                               "character")
      }
      else {
        cv <- FALSE
      }
    }
    else if (vi == "palette") {
      cv <- all(.isColor(input))
    }
    else if (vi == "timestamp") {
      cv <- is(input, "POSIXct")
    }
    else if (vi == "dataframe" | vi == "data.frame" | 
             vi == "df") {
      cv1 <- is.data.frame(input)
      cv2 <- is(input, "DataFrame")
      cv <- any(cv1, cv2)
    }
    else if (vi == "fileexists") {
      cv <- all(file.exists(input))
    }
    else if (vi == "direxists") {
      cv <- all(dir.exists(input))
    }
    else if (vi == "granges" | vi == "gr") {
      cv <- is(input, "GRanges")
    }
    else if (vi == "grangeslist" | vi == "grlist") {
      cv <- .isGRList(input)
    }
    else if (vi == "list" | vi == "simplelist") {
      cv1 <- is.list(input)
      cv2 <- is(input, "SimpleList")
      cv <- any(cv1, cv2)
    }
    else if (vi == "bsgenome") {
      cv1 <- is(input, "BSgenome")
      cv2 <- tryCatch({
        library(input)
        eval(parse(text = input))
      }, error = function(e) {
        FALSE
      })
      cv <- any(cv1, cv2)
    }
    else if (vi == "se" | vi == "summarizedexperiment") {
      cv <- is(input, "SummarizedExperiment")
    }
    else if (vi == "seurat" | vi == "seuratobject") {
      cv <- is(input, "Seurat")
    }
    else if (vi == "txdb") {
      cv <- is(input, "TxDb")
    }
    else if (vi == "orgdb") {
      cv <- is(input, "OrgDb")
    }
    else if (vi == "bsgenome") {
      cv <- is(input, "BSgenome")
    }
    else if (vi == "parallelparam") {
      cv <- is(input, "BatchtoolsParam")
    }
    else if (vi == "archrproj" | vi == "archrproject") {
      cv <- is(input, "ArchRProject")
    }
    else {
      stop("Validator is not currently supported by ArchR!")
    }
    if (cv) {
      av <- TRUE
      break
    }
  }
  if (av) {
    return(invisible(TRUE))
  }
  else {
    stop("Input value for '", name, "' is not a ", 
         paste(valid, collapse = ","), ", (", 
         name, " = ", class(input), ") please supply valid input!")
  }
}

filterDoublets_fixbug = function (ArchRProj = NULL, cutEnrich = 1, cutScore = -Inf, filterRatio = 1) {
  validInput(input = ArchRProj, name = "ArchRProj", 
                     valid = c("ArchRProj"))
  validInput(input = cutEnrich, name = "cutEnrich", 
                     valid = c("numeric"))
  validInput(input = cutScore, name = "cutScore", valid = c("numeric"))
  validInput(input = filterRatio, name = "filterRatio", 
                     valid = c("numeric"))
  if (any(grepl("filterDoublets", names(ArchRProj@projectSummary)))) {
    stop("Already ran filterDoublets on ArchRProject! Cannot be re-ran on an ArchRProject!")
  }
  df <- ArchR::getCellColData(ArchRProj, c("Sample", "DoubletEnrichment", 
                                           "DoubletScore"))
  splitDF <- split(seq_len(nrow(df)), as.character(df$Sample))
  cellsFilter <- lapply(splitDF, function(y) {
    x <- df[y, , drop = FALSE]
    n <- nrow(x)
    x <- x[order(x$DoubletEnrichment, decreasing = TRUE), 
    ]
    if (!is.null(cutEnrich)) {
      x <- x[which(x$DoubletEnrichment >= cutEnrich), ]
    }
    if (!is.null(cutScore)) {
      x <- x[which(x$DoubletScore >= cutScore), ]
    }
    if (nrow(x) > 0) {
      head(rownames(x), filterRatio * n * (n/1e+05))
    }
    else {
      NULL
    }
  }) %>% unlist(use.names = FALSE)
  message("Filtering ", length(cellsFilter), " cells from ArchRProject!")
  tabRemove <- table(df[cellsFilter, ]$Sample)
  tabAll <- table(df$Sample)
  samples <- unique(df$Sample)
  for (i in seq_along(samples)) {
    if (!is.na(tabRemove[samples[i]])) {
      message("\t", samples[i], " : ", tabRemove[samples[i]], 
              " of ", tabAll[samples[i]], " (", 
              round(100 * tabRemove[samples[i]]/tabAll[samples[i]], 
                    1), "%)")
    }
    else {
      message("\t", samples[i], " : ", 0, " of ", 
              tabAll[samples[i]], " (0%)")
    }
  }
  if (length(cellsFilter) > 0) {
    ArchRProj@cellColData <- ArchRProj@cellColData[rownames(ArchRProj@cellColData) %ni% 
                                                     cellsFilter, , drop = FALSE]
  }
  ArchRProj <- ArchR::addProjectSummary(ArchRProj = ArchRProj, name = "filterDoublets", 
                                 summary = c(Date = as.character(Sys.time()), cutEnrich = cutEnrich, 
                                             cutScore = cutScore, filterRatio = filterRatio))
  ArchRProj
}


proj <- filterDoublets_fixbug(ArchRProj = proj)

**Comment by liaoshengyou** [comment] 2020-07-22 20:27
ArchRProj <- ArchR::addProjectSummary(ArchRProj = ArchRProj, name = "filterDoublets", 
                                 summary = c(Date = as.character(Sys.time()), cutEnrich = cutEnrich, 
                                             cutScore = cutScore, filterRatio = filterRatio))

**Comment by CSBioAzim** [comment] 2020-07-23 02:35
@rcorces @jgranja24 do you have an idea why this problem occurs? I think it has a problem with formating data and time.

**Comment by s7hegde** [comment] 2020-07-24 14:40
stopgap solution here? 
https://github.com/GreenleafLab/ArchR/issues/217#issuecomment-649129065

**Comment by rcorces** [comment] 2020-07-25 01:00
Yes this is a duplicate of #217 
Please search the current and previous issues before posting.

**Closed by rcorces** 2020-07-25 01:00 UTC
Labels: bug
