### ISSUE TITLE
Is it possible to get the  output of plotPeak2GeneHeatmap() function as marix rather than plot??

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#169] opened 2020-05-22 15:13 UTC
I would like to extract interesting patterns from Peak2GeneHeatmap plot for downstream analysis. 
I was wondering is there any way to get the matrix of data that is used to creat heatmap?
I know that   `markerHeatmap( returnMat=TRUE)` can return the matrix, but I couldn't find a way for `PlotPeak2GeneHeatmap()` function.

**Comment by jgranja24** [comment] 2020-05-22 17:47
duplicate of #132 Im working on it

**Closed by jgranja24** 2020-05-22 17:47 UTC
Labels: documentation
