### ISSUE TITLE
Error in "plotTSSEnrichment"

### ISSUE THREAD

**Issue by linhch5** [GreenleafLab/ArchR#252] opened 2020-07-21 05:41 UTC
**Attach your log file**
ArchR has a built-in logging functionality for all complex functions. You MUST attach your log file (indicated in the console output) to this issue
[ArchR-plotTSSEnrichment-1b483d685a8-Date-2020-07-20_Time-22-03-06.log](https://github.com/GreenleafLab/ArchR/files/4951499/ArchR-plotTSSEnrichment-1b483d685a8-Date-2020-07-20_Time-22-03-06.log)
. Just drag and drop it here.

**Describe the bug**
I got a wrong TSSenrichment plot include just one normal line with 2 peaks and the other two lines almost straight. I am confused by the result. Is there anyone can help me? Thanks very much!

**Screenshots**
![image](https://user-images.githubusercontent.com/68565460/88017153-b66d5d00-caea-11ea-8d07-0acf22bc9131.png)

**Comment by jgranja24** [comment] 2020-07-22 21:21
Hmmm I think this has happened for some other people. I will look into this sorry for the delay.

**Comment by rcorces** [comment] 2020-08-11 18:33
I'm assuming that this is related to running on windows. Windows is not supported and its not possible for us to troubleshoot this. I'm closing this issue.

**Comment by Carota-1** [comment] 2020-08-14 06:14
I got the same issue when running in linux.

**Comment by rcorces** [comment] 2020-08-14 14:44
Can you try running with 1 thread and see if this solves the problem?

**Comment by Carota-1** [comment] 2020-08-17 09:25
Thank you for your answer, but the issue still  still exists when I use a thread.

**Comment by jgranja24** [comment] 2020-10-28 22:38
Sorry for the delays @Carota-1.

Can you try with the new release branch. I added more stability and logging and more features --

For Example

```
#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)
proj <- getTestProject()

p <- plotTSSEnrichment(ArchRProj = proj, groupBy = "Clusters")
plotPDF(p)

p <- plotFragmentSizes(ArchRProj = proj, groupBy = "Clusters")
plotPDF(p)
```

<img width="761" alt="Screen Shot 2020-10-28 at 3 36 24 PM" src="https://user-images.githubusercontent.com/25017655/97504171-93e1b000-1933-11eb-94d2-5f1265f6ea6e.png">


<img width="824" alt="Screen Shot 2020-10-28 at 3 36 27 PM" src="https://user-images.githubusercontent.com/25017655/97504183-99d79100-1933-11eb-9318-1aaea0c32d96.png">

**Comment by rcorces** [comment] 2020-11-21 23:15
Closing due to inactivity. Feel free to post to this thread if the problem can be reproduced with the latest version of ArchR and we will re-open the issue.

**Comment by zhijunyuu** [comment] 2020-11-24 09:46
> Sorry for the delays @Carota-1.
> 
> Can you try with the new release branch. I added more stability and logging and more features --
> 
> For Example
> 
> ```
> #New Release Branch
> devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
> 
> library(ArchR)
> proj <- getTestProject()
> 
> p <- plotTSSEnrichment(ArchRProj = proj, groupBy = "Clusters")
> plotPDF(p)
> 
> p <- plotFragmentSizes(ArchRProj = proj, groupBy = "Clusters")
> plotPDF(p)
> ```
> 
> <img alt="Screen Shot 2020-10-28 at 3 36 24 PM" width="761" src="https://user-images.githubusercontent.com/25017655/97504171-93e1b000-1933-11eb-94d2-5f1265f6ea6e.png">
> 
> <img alt="Screen Shot 2020-10-28 at 3 36 27 PM" width="824" src="https://user-images.githubusercontent.com/25017655/97504183-99d79100-1933-11eb-9318-1aaea0c32d96.png">

I got the same issue running on linux and using the 1.0.0 version of ArchR. Also tried 1 thread, it didn't help.

**Comment by rcorces** [comment] 2020-11-24 15:08
@zhijunyuu - Can you provide a log file?

**Comment by zhijunyuu** [comment] 2020-12-10 10:32
> @zhijunyuu - Can you provide a log file?

[ArchR-plotTSSEnrichment-6a771b6c7cfb-Date-2020-12-10_Time-10-49-07.log](https://github.com/GreenleafLab/ArchR/files/5672018/ArchR-plotTSSEnrichment-6a771b6c7cfb-Date-2020-12-10_Time-10-49-07.log)

**Comment by rcorces** [comment] 2020-12-10 15:24
Thanks @zhijunyuu 
Could you instead run using the code provided by @jgranja24 and provide that log file? This might rule out any issue with the dataset that you are using:

```
#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)
proj <- getTestProject()

p <- plotTSSEnrichment(ArchRProj = proj, groupBy = "Clusters")
plotPDF(p)

p <- plotFragmentSizes(ArchRProj = proj, groupBy = "Clusters")
plotPDF(p)
```

**Comment by zhijunyuu** [comment] 2020-12-10 16:03
@rcorces Thanks for your quick reply

I tried the Test data, the TSS enrichment file looks normal. 

I upgraded ArchR to 1.0.1, issue solved!

Thanks!

**Comment by rcorces** [comment] 2020-12-10 16:05
Thanks for the feedback. I wish we knew what was causing this problem but I'm glad it is working for you now.

**Comment by zhijunyuu** [comment] 2020-12-10 16:15
@rcorces 
Here is the log file that TSSEnrichment worked well for my samples, maybe you could compare it with the previous one I uploaded that didn't work, and maybe locate where the problem is. 
[ArchR-plotTSSEnrichment-76415a26afc8-Date-2020-12-10_Time-16-59-19.log](https://github.com/GreenleafLab/ArchR/files/5674095/ArchR-plotTSSEnrichment-76415a26afc8-Date-2020-12-10_Time-16-59-19.log)

**Comment by yang050036** [comment] 2021-01-29 07:20
I have the same problem. And I used 1.0.0 and 1.0.1.
This is my log file:
[ArchR-plotTSSEnrichment-6bd87a554a11-Date-2021-01-29_Time-13-24-05.log](https://github.com/GreenleafLab/ArchR/files/5892153/ArchR-plotTSSEnrichment-6bd87a554a11-Date-2021-01-29_Time-13-24-05.log)
And I have another result about only one sample: scATAC_CD34_BMMC_R1
[ArchR-plotTSSEnrichment-6bd83cd1af1b-Date-2021-01-29_Time-13-46-35.log](https://github.com/GreenleafLab/ArchR/files/5892163/ArchR-plotTSSEnrichment-6bd83cd1af1b-Date-2021-01-29_Time-13-46-35.log)
I find, SumTSS in same chr, there is a big defference between log files, for example:
only scATAC_CD34_BMMC_R1 :
```
scATAC_CD34_BMMC_R1 : SumTSS : chr1: length = 4001
[1] 113 115 107 141 124 127
```
three sample:
```
scATAC_CD34_BMMC_R1 : SumTSS : chr1: length = 4001
[1] 989 917 912 762 807 920

```
why ?

**Comment by rcorces** [comment] 2021-01-29 15:54
@yang050036 
1) Please open a new issue to ask your question about the sum of the TSS. It is not related to this issue
2) Please try the below code and let us know if it works. If this works, it is likely a problem with your input.

```
#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories())

library(ArchR)
proj <- getTestProject()

p <- plotTSSEnrichment(ArchRProj = proj, groupBy = "Clusters")
plotPDF(p)

p <- plotFragmentSizes(ArchRProj = proj, groupBy = "Clusters")
plotPDF(p)
```

**Comment by yang050036** [comment] 2021-02-01 03:18
@rcorces 
   Thanks for you reply
   I reinstall ArchR used the  command:
`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories())`
   and it worked well.
   I install the ArchR used "devtools::isntall_local" before, and I don't know where was wrong, but it works now.
  Thanks again.

**Comment by yang050036** [comment] 2021-02-01 06:21
OK, I find addArchRThreads(threads = 1) will be get the bug in my server(linux, centos7), but multiple threads works well for me.
Maybe help for you.

**Comment by Kaivalyamolugu** [comment] 2021-03-10 19:41
Hello, 
I am having the same issue of wrong TSS enrichment plots with only one of my 4 samples having a peak. I am using ArchR on Linux. I went ahead and ran the 
#New Release Branch 
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories())

library(ArchR)
proj <- getTestProject()

p <- plotTSSEnrichment(ArchRProj = proj, groupBy = "Clusters")
plotPDF(p)

p <- plotFragmentSizes(ArchRProj = proj, groupBy = "Clusters")
plotPDF(p)

as recommended in the above comments but still having the same issue (image attached).  Do you have any other recommendations? Please let me know if you'd need any other information from me or prefer to have this as a new issue. 
![image](https://user-images.githubusercontent.com/43280402/110685001-6dfece80-81a3-11eb-860b-f37af53c01d3.png)
[Log file.pdf](https://github.com/GreenleafLab/ArchR/files/6118431/Log.file.pdf)

Thanks, 
Kaivalya

**Comment by rcorces** [comment] 2021-03-10 22:43
interesting that you are able to recapitulate this with the test project - that is helpful.
Could you find this file and upload it to this issue by dragging and dropping? 
(path relative to your project directory)
`ArchRLogs/ArchR-plotTSSEnrichment-d25380cde71-Date-2021-03-10_Time-11-50-56.log`

**Comment by Kaivalyamolugu** [comment] 2021-03-11 00:47
[ArchR-plotTSSEnrichment-d25380cde71-Date-2021-03-10_Time-11-50-56.log](https://github.com/GreenleafLab/ArchR/files/6119650/ArchR-plotTSSEnrichment-d25380cde71-Date-2021-03-10_Time-11-50-56.log)

Thank you for your response. Please find it attached.

**Comment by yang050036** [comment] 2021-03-11 01:10
I don't know how it works, but it worked when I set 3 threads for 3 samples. Could you set the number of threads as you samples or clusters?

**Comment by Kaivalyamolugu** [comment] 2021-03-11 03:22
> I don't know how it works, but it worked when I set 3 threads for 3 samples. Could you set the number of threads as you samples or clusters?

Hi, I am unable to set the threads to anything higher than 1. It always defaults to 1 for me if I try to set anything higher.

**Comment by rcorces** [comment] 2021-03-11 04:20
@Kaivalyamolugu - ArchR only detects 3 cores on your machine and ArchR prevents you from requesting more than the total number of cores minus 2. From the `addArchRThreads()` params:
```
force | If you request more than the total number of CPUs minus 2, ArchR will set threads to (nCPU - 2). To bypass this, setting force = TRUE will use the number provided to threads.
```

I dont see anything in the log file that tips me off as to what is going on.

@jgranja24 - can you take a look?

**Comment by Kaivalyamolugu** [comment] 2021-03-11 15:29
Hello all, Thank you for your suggestions. I set the ArchR threads = 16 by running force = TRUE and that worked. Attached is the beautiful new plot! It does look like it's something to do with the threads?

Thanks, 
Kaivalya
![image](https://user-images.githubusercontent.com/43280402/110811360-3ef06780-824c-11eb-8775-eafee89b49df.png)

**Comment by rcorces** [comment] 2021-03-11 15:42
@Kaivalyamolugu - Thanks for confirming this. You are correct - there is something funky going on when `threads = 1` in this function. I can recapitulate this error when I set `threads = 1`
```
proj <- getTestProject()
addArchRThreads(threads = 1)
plotTSSEnrichment(ArchRProj = proj, groupBy = "Clusters")
```
![image](https://user-images.githubusercontent.com/10343046/110812288-56275900-823c-11eb-85eb-0c3605997617.png)

This is calculated incorrectly within the function and (unsurprisingly) when you use `returnDF = TRUE` the data frame object is incorrect as well:
```
> df1 <- plotTSSEnrichment(ArchRProj = proj, groupBy = "Clusters", returnDF = TRUE)
> df1[which(df1$x == 0),]
DataFrame with 5 rows and 5 columns
        group         x     value          normValue       smoothValue
  <character> <numeric> <integer>          <numeric>         <numeric>
1          C1         0       918   21.4182240278584  21.0873423732391
2          C2         0         7 0.0694334780892223 0.081156013351039
3          C3         0        21  0.696764608781776 0.811383895074882
4          C4         0        29  0.883315653886953 0.863932551764041
5          C5         0        14   1.37268292682927  1.22115299334812
```

I havent figured out where the problem is in the code but @jgranja24 will figure it out

**Comment by Kaivalyamolugu** [comment] 2021-03-11 22:59
Hello again, My R is crashing since I've set the threads to 16. Do you think it would be okay to set the threads to 1 for the rest of the code and set to 16 only for the TSS enrichment plot step?
Thanks, 
Kaivalya

**Comment by rcorces** [comment] 2021-03-11 23:02
@Kaivalyamolugu - according to your logfile, ArchR only really detects 3 cores on your machine. The error with `threads = 1` should be limited to `plotTSSEnrichment()`. Try `threads = 2` though. this should be fine on your system.

**Comment by Kaivalyamolugu** [comment] 2021-03-11 23:21
Thank you for letting me know!

**Comment by sqs1020** [comment] 2022-01-20 20:18
Hello, I am also getting the same problem on my 6 samples. I cannot use any other threads except for threads = 1. I am using macOS.
![image](https://user-images.githubusercontent.com/52260392/150415508-4331566e-2b53-4fbf-bbcd-b11fe42edc90.png)

![image](https://user-images.githubusercontent.com/52260392/150415418-5a9dbd0b-94ca-4861-a81d-705717fb5bff.png)

**Comment by rcorces** [comment] 2022-01-20 22:49
@sqs1020 - I believe your problem is unrelated. see https://github.com/GreenleafLab/ArchR/issues/1145#issuecomment-970811134
just run `library(parallel)` before using ArchR when using threads > 1

**Comment by sqs1020** [comment] 2022-01-20 22:52
> @sqs1020 - I believe your problem is unrelated. see [#1145 (comment)](https://github.com/GreenleafLab/ArchR/issues/1145#issuecomment-970811134) just run `library(parallel)` before using ArchR when using threads > 1

Thanks for the reply. My innitial problem is related, that is asscociated with the "plotTSSEnrichment" function (see attached scrreenshot). And then I found this ticket and read the comments. People are saysing using different threads can solve the problem and that's why I have the problem trying different threads. Thank you!
![image](https://user-images.githubusercontent.com/52260392/150434726-94af1503-2f04-4e8e-bc66-14ca51421991.png)

**Comment by sqs1020** [comment] 2022-01-20 23:01
> library(parallel)

After using library(parallel) and trying threads = 6 , the problem solved. Thanks again!
![image](https://user-images.githubusercontent.com/52260392/150435714-a55dd2ae-ba01-473c-ac82-76c23f52a9c9.png)

**Comment by rcorces** [comment] 2022-05-21 12:55
This issue has finally been fixed via https://github.com/GreenleafLab/ArchR/commit/506161d36d1457d4b3aba20918c0e4f622ae937e in `release_1.0.2`. It was a C++ bug.

**Closed by rcorces** 2022-05-21 12:55 UTC
Labels: bug, help wanted

**Comment by rcorces** [comment] 2022-05-21 12:56
```
> addArchRThreads(threads = 1)
Setting default number of Parallel threads to 1.
> plotTSSEnrichment(ArchRProj = proj, groupBy = "Clusters")
ArchR logging to : ArchRLogs/ArchR-plotTSSEnrichment-2f2e58d1b16f-Date-2022-05-21_Time-05-53-46.log
If there is an issue, please report to github with logFile!
2022-05-21 05:53:46 : C1 Computing TSS (1 of 5)!, 0.003 mins elapsed.
2022-05-21 05:53:47 : C1 Finished Computing TSS (1 of 5)!, 0.015 mins elapsed.
2022-05-21 05:53:47 : C2 Computing TSS (2 of 5)!, 0.017 mins elapsed.
2022-05-21 05:53:48 : C2 Finished Computing TSS (2 of 5)!, 0.024 mins elapsed.
2022-05-21 05:53:48 : C3 Computing TSS (3 of 5)!, 0.024 mins elapsed.
2022-05-21 05:53:48 : C3 Finished Computing TSS (3 of 5)!, 0.034 mins elapsed.
2022-05-21 05:53:48 : C4 Computing TSS (4 of 5)!, 0.034 mins elapsed.
2022-05-21 05:53:49 : C4 Finished Computing TSS (4 of 5)!, 0.044 mins elapsed.
2022-05-21 05:53:49 : C5 Computing TSS (5 of 5)!, 0.044 mins elapsed.
2022-05-21 05:53:49 : C5 Finished Computing TSS (5 of 5)!, 0.052 mins elapsed.
ArchR logging successful to : ArchRLogs/ArchR-plotTSSEnrichment-2f2e58d1b16f-Date-2022-05-21_Time-05-53-46.log
> 
```
![image](https://user-images.githubusercontent.com/10343046/169652508-8b387bce-f577-4fef-82af-11e155715d73.png)
