### ISSUE TITLE
Extracting cluster data (bam/biqwig)  for Genome browser Visualisation.

### ISSUE THREAD

**Issue by annrosebright** [GreenleafLab/ArchR#236] opened 2020-07-06 10:41 UTC
I want to look into certain genomic regions (enhancers) and also compare the scATACseq data with other datasets (chIP seq, RNAseq, and methylation).  For this, it would be great if I could download this information used by the ArchRBrowser and upload it in other external genome browser software( UCSC Genome Browser or IGV browser )

Is there any possibility to do that? Cluster specific bam or bigwig files would be sufficient I guess. Any suggestions or help would be great.

**Comment by rcorces** [comment] 2020-07-06 14:39
Thanks for using ArchR! This is a duplicate of https://github.com/GreenleafLab/ArchR/issues/54
See that post for the solution.

**Closed by rcorces** 2020-07-06 14:39 UTC
