### ISSUE TITLE
Inspect Arrow Files Waiting Time Too long + No Responses

### ISSUE THREAD

**Issue by KuroToaster** [GreenleafLab/ArchR#1853] opened 2023-02-22 18:29 UTC
Hello, 

I have a problem of inspecting arrow files because the responding time is too long, and I have to stop the inspection manually. 

When I created the arrow files by the createArrowFiles function, the output is:
Using GeneAnnotation set by addArchRGenome(Mm9)!
Using GeneAnnotation set by addArchRGenome(Mm9)!
ArchR logging to : ArchRLogs/ArchR-createArrows-192e34757f0d-Date-2023-02-22_Time-10-25-27.log
If there is an issue, please report to github with logFile!
2023-02-22 10:25:27 : Batch Execution w/ safelapply!, 0 mins elapsed.

According to the tutorial, this should mean that the arrow files are created properly, right? 

However, as I further inspect if the arrow files are there or not by running "ArrowFiles", the console no longer response, follows a long waiting time. Then, I proceeded with creating archR project, the error printed is no arrow files found. 

Thank you in advance!

**Comment by rcorces** [comment] 2023-02-22 18:29
Hi @KuroToaster! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by KuroToaster** [comment] 2023-02-22 18:41
Yes, I am so sorry to put it in this session. But thank you so much for your reply to my post!

1. I have searched for this for a long time in the discussion post. Initially, I thought it was my input files problem, but I further checked the post for someone issuing an input file problem, and my files should be properly loaded into the createArrowFiles function.

2. I reproduce the same error when I run it with the tutorial code. When I create the arrow files, they displayed:

Using GeneAnnotation set by addArchRGenome(Mm9)!
Using GeneAnnotation set by addArchRGenome(Mm9)!
ArchR logging to : ArchRLogs/ArchR-createArrows-192e7b7be4d5-Date-2023-02-22_Time-10-39-02.log
If there is an issue, please report to github with logFile!
2023-02-22 10:39:02 : Batch Execution w/ safelapply!, 0 mins elapsed.

However, when I inspect the arrow files, nothing is printing as expected. 

Thank you!

**Comment by rcorces** [comment] 2023-02-22 22:49
Please follow all instructions when posting to GitHub. You have not uploaded a log file.

**Comment by rcorces** [comment] 2023-03-03 14:06
Closing because no log file provided.

**Closed by rcorces** 2023-03-03 14:06 UTC
Labels: bug
