### ISSUE TITLE
addReproduciblePeakSet not finishing

### ISSUE THREAD

**Issue by vineethtm** [GreenleafLab/ArchR#1218] opened 2021-12-06 19:11 UTC
Log file

[ArchR-addReproduciblePeakSet-41b08ac04-Date-2021-12-06_Time-10-31-13.log](https://github.com/GreenleafLab/ArchR/files/7662966/ArchR-addReproduciblePeakSet-41b08ac04-Date-2021-12-06_Time-10-31-13.log)

Issue !

I have been running addReproduciblePeakSet with a dataset for sometime. It worked one time but I haven't been able to reproduce that.  I'm running from a singularity container and I have configured python and macs2 with that. ArchR has been able to call macs2 but this step is getting stuck at some step. So I went back to the tutorial data and tried to reproduce the results. Results are the same and program is stuck at this step. I could see files in my ReplicateCalls folder and none in the InsertionBeds folder. InsertionBeds folder were initially populated with files but were removed as the program progressed.

This is the command I used

projHeme2 <- addReproduciblePeakSet(
    ArchRProj = projHeme2, 
    groupBy = "Clusters", 
    pathToMacs2 = pathToMacs2, force=T)

ArchR logging to : ArchRLogs/ArchR-addReproduciblePeakSet-41b08ac04-Date-2021-12-06_Time-10-31-13.log
If there is an issue, please report to github with logFile!
2021-12-06 10:31:14 : Peak Calling Parameters!, 0.012 mins elapsed.
2021-12-06 10:31:14 : Batching Peak Calls!, 0.013 mins elapsed.
2021-12-06 10:31:14 : Batch Execution w/ safelapply!, 0 mins elapsed

**Comment by rcorces** [comment] 2021-12-06 19:12
Hi @vineethtm! Thanks for using ArchR! I am currently on paternity leave and will not be responding to any issues or discussion threads. I plan to be back in late January and will do my best to address your issue then.<br />
In the meantime, it is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment. Search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.<br />
If you are able to solve your issue, please post the solution and close this issue post. <br />
Otherwise __if you would like my help when I return, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by paupaiz** [comment] 2021-12-10 07:17
@vineethtm this might have to do with your singularity container. Can you try `threads=1`?

**Comment by RegnerM2015** [comment] 2022-01-25 21:29
@vineethtm, 

Were you using `singularity exec`? If so, what parameters/flags did you use to run your R script(s)? 

I am having issues with reading and writing Arrow files within my container. Thanks in advance!

**Comment by rcorces** [comment] 2022-01-25 21:50
@paupaiz might be able to offer help. we are working on a stable container for ArchR as well.

**Comment by RegnerM2015** [comment] 2022-01-25 21:58
Thanks @rcorces!

For additional context, I have built a Docker container and uploaded it to DockerHub: https://hub.docker.com/repository/docker/regnerm/scatac_processing

I would like to run some ArchR code using this container on an HPC system. My options are 1) `snakemake --use-singularity` or 2) `singularity exec`. 

I realized that trying to make a snakemake workflow for ArchR would quickly become a nightmare since there are a lot of intermediate files and subdirectories when users run ArchR.

Therefore, I think `singularity exec` would be the best approach moving forward. Feel free to suggest ideas or advice! Thank you.

**Comment by vineethtm** [comment] 2022-01-26 03:43
@rcorces. I was running that command from a Rmarkdown chunk where it didn't work ! When I copied that code to a regular Rscript and run it from there, it worked !  @paupaiz I tried threads =1 when sometimes I had issues with the previous step (adding coverage) and it worked sometimes ! @RegnerM2015 I'm not directly using singularity exec, everything is configured by the company and I used Rstudio session on a browser !

**Comment by RegnerM2015** [comment] 2022-01-26 17:01
@paupaiz 

Yes, I have been tinkering with the home directory and bind mount parameters, but I am still not able to write out Arrow Files:

```
ArchR_Script.R | singularity exec --bind $PWD:/home --home $PWD:/home docker://regnerm/scatac_processing R
```

My SLURM output and ArchRLog file are attached below:

[slurm-7041191.txt](https://github.com/GreenleafLab/ArchR/files/7943611/slurm-7041191.txt)
[ArchR-createArrows-255269df0234-Date-2022-01-26_Time-11-52-22.log](https://github.com/GreenleafLab/ArchR/files/7943606/ArchR-createArrows-255269df0234-Date-2022-01-26_Time-11-52-22.log)

As you can see, the ArrowFiles creation was not successful and my ArrowFIles directory is empty presumably b/c Singularity cannot write to this filesystem.

**Comment by rcorces** [comment] 2022-03-20 04:39
Closing as I dont think this is an ArchR issue but more likely a container issue. Feel free to follow up here and I will re-open.

**Closed by rcorces** 2022-03-20 04:39 UTC
