### ISSUE TITLE
Aggregating several ArchR projects

### ISSUE THREAD

**Issue by nonafarbehi2018** [GreenleafLab/ArchR#955] opened 2021-08-04 05:50 UTC
Hi, dear ArchR developers,

I am trying to deal with my massive 10X multiome dataset and I am keen to use ArchR to aggregate the scATAC data and perform downstream analysis. My first question is do you have any guidelines about applying ArchR package to multiome data?
and my second question is how I can aggregate various ArchR projects? I have done the initial analysis of each dataset separately using ArchR and saved the arrow files as well as projects.rds files.

Thanks
Nona

**Comment by rcorces** [comment] 2021-08-05 19:34
Please note that this is not a bug and the Issue submission system clearly states that Issues are only for bugs / errors and Discussions are for questions/feature requests. I'm transferring your Issue to a Discussion.

**Closed by rcorces** 2021-08-05 19:34 UTC
Labels: bug
