### ISSUE TITLE
object 'V4' not found in "createArrowFiles"

### ISSUE THREAD

**Issue by Zepeng-Mu** [GreenleafLab/ArchR#1396] opened 2022-04-23 18:27 UTC
Hello,
I'm using the latest version of "realease_1.0.2" but I encountered this error when creating error files:
```
2022-04-23 13:18:52 : ERROR Found in .tabixToTmp for (test : 1 of 1)
LogFile = ArchRLogs/ArchR-createArrows-40452b54ad8-Date-2022-04-23_Time-13-18-31.log

<simpleError in eval(quote(list(...)), env): object 'V4' not found>

2022-04-23 13:18:52 : errorList, Class = list

errorList$x: length = 1
[1] 54


errorList$tileChromSizes: length = 1
GRanges object with 1 range and 1 metadata column:
      seqnames             ranges strand |     chunkName
         <Rle>          <IRanges>  <Rle> |   <character>
  [1]    chr11 81003910-108005212      * | chr11#chunk54
  -------
  seqinfo: 24 sequences from an unspecified genome; no seqlengths


errorList$fragments: length = 1
[1] "Error with Fragments!"
```
This happens with example data and my own data.
```r
test=createArrowFiles(inputFiles = "HemeFragments/scATAC_BMMC_R1.fragments.tsv.gz",
                      sampleNames = "test")
```
The full log is also attached
[ArchR-createArrows-4046422a803-Date-2022-04-23_Time-13-16-06.log](https://github.com/GreenleafLab/ArchR/files/8548160/ArchR-createArrows-4046422a803-Date-2022-04-23_Time-13-16-06.log)

I use ArchR very often, and based on my old code, the last time I used `createArrowFiles` was on March 19th, but I now have the same error message on that same dataset. Using BAM files have the same error. The tmp arrow files are empty.

I tried trouble shooting by running `.tabixToTmp` line-by-line, basically I pulled out the code and removed some `.log*` functions and I did get a very large arrow file, so it seems there is no error in this case. The function is pasted below, but I cannot further narrow down the error. Thanks!!

```r
mytabixToTmp <- function(
  tabixFile = NULL, 
  sampleName = NULL,
  validBC = NULL,
  tmpFile = ArchR:::.tempfile(pattern = paste0("tmp-",sampleName,"-arrow"), fileext=".arrow"),
  chromSizes = NULL, 
  nChunk = 3,
  gsubExpression = NULL, 
  verbose = TRUE,
  prefix = "",
  tstart = NULL,
  threads = 1,
  logFile = NULL
){
  
  #######################################################################################################
  # We will dump a chunked genome into an Hdf5 file in a memory efficient manner!
  #######################################################################################################
  o <- h5closeAll()
  o <- h5createFile(tmpFile)
  o <- h5createGroup(tmpFile, paste0("Fragments"))
  o <- h5createGroup(tmpFile, paste0("Metadata"))
  o <- h5write(obj = "Arrow", file = tmpFile, name = "Class")
  o <- h5write(obj = paste0(packageVersion("ArchR")), file = tmpFile, name = "ArchRVersion")
  o <- h5write(obj = "tmp", file = tmpFile, name = "Metadata/Sample")
  
  tileChromSizes <- unlist(GenomicRanges::tile(chromSizes, nChunk))
  mcols(tileChromSizes)$chunkName <- paste0(seqnames(tileChromSizes),"#chunk",seq_along(tileChromSizes))
  
  readTiledChrom <- ArchR:::.safelapply(seq_along(tileChromSizes), function(x){
    
    tryCatch({
      
      errorCheck <- 0
      
      dt <- tryCatch({
        Rsamtools::scanTabix(tabixFile, param = tileChromSizes[x])[[1]] %>%
          textConnection %>% 
          {tryCatch(read.table(.), error = function(e) NULL)} %>% 
          {data.table(V2=.$V2 + 1, V3=.$V3, V4=.$V4)}
      }, error = function(f){
        NULL
      })
      
      if(is.null(dt)){
        
        dt <- tryCatch({
          Rsamtools::scanTabix(tabixFile, param = .convertGRSeqnames(tileChromSizes[x], method = "remove"))[[1]] %>%
            textConnection %>% 
            {tryCatch(read.table(.), error = function(e) NULL)} %>% 
            {data.table(V2=.$V2 + 1, V3=.$V3, V4=.$V4)}
        }, error = function(f){
          NULL
        })
        
      }
      
      if(is.null(dt)){
        return(list(tmpChrFile = NULL, errorCheck = errorCheck))
      }
      
      #No NAs
      dt <- dt[!is.na(dt$V2), , drop=FALSE] 
      dt <- dt[!is.na(dt$V3), , drop=FALSE]
      dt <- dt[!is.na(dt$V4), , drop=FALSE]
      
      #Care for Break Points
      dt <- dt[dt$V2 >= start(tileChromSizes[x]),]
      
      if(!is.null(gsubExpression)){
        dt$V4 <- gsub(gsubExpression, "", dt$V4)
      }
      
      #Check for valid barcodes
      if(!is.null(validBC)){
        dt <- dt[dt$V4 %in% validBC, ]
      }
      
      if(all(!is.null(dt), nrow(dt) > 0)){
        
        errorCheck <- errorCheck + 1
        
        if(threads == 1){
          
          #Order by bc
          setkey(dt, V4)
          dt <- dt[order(V4)]
          RG <- Rle(paste0(dt$V4))
          
          chrTmp <- mcols(tileChromSizes)$chunkName[x]
          chrPos <- paste0("Fragments/",chrTmp,"/Ranges")
          chrRGLengths <- paste0("Fragments/",chrTmp,"/RGLengths")
          chrRGValues <- paste0("Fragments/",chrTmp,"/RGValues")
          lengthRG <- length(RG@lengths)
          o <- h5createGroup(tmpFile, paste0("Fragments/",chrTmp))
          o <- ArchR:::.suppressAll(h5createDataset(tmpFile, chrPos, storage.mode = "integer", dims = c(nrow(dt), 2), level = 0))
          o <- ArchR:::.suppressAll(h5createDataset(tmpFile, chrRGLengths, storage.mode = "integer", dims = c(lengthRG, 1), level = 0))
          o <- ArchR:::.suppressAll(h5createDataset(tmpFile, chrRGValues, storage.mode = "character", 
                                            dims = c(lengthRG, 1), level = 0, size = max(nchar(RG@values)) + 1))
          o <- h5write(obj = cbind(dt$V2,dt$V3 - dt$V2 + 1), file = tmpFile, name = chrPos)
          o <- h5write(obj = RG@lengths, file = tmpFile, name = chrRGLengths)
          o <- h5write(obj = RG@values, file = tmpFile, name = chrRGValues)
          
          rm(dt, RG)
          gc()
          
          return(list(tmpChrFile = NULL, errorCheck = errorCheck))
          
        }else{
          
          chrTmp <- mcols(tileChromSizes)$chunkName[x]
          
          #Temporary File
          tmpChrFile <- paste0(gsub(".arrow", "", tmpFile), ".", chrTmp, ".arrow")
          if(file.exists(tmpChrFile)){
            file.remove(tmpChrFile)
          }
          
          o <- h5createFile(tmpChrFile)
          
          #Order by bc
          setkey(dt, V4)
          dt <- dt[order(V4)]
          RG <- Rle(paste0(dt$V4))
          
          chrPos <- paste0(chrTmp, "._.Ranges")
          chrRGLengths <- paste0(chrTmp, "._.RGLengths")
          chrRGValues <- paste0(chrTmp, "._.RGValues")
          lengthRG <- length(RG@lengths)
          
          o <- .suppressAll(h5createDataset(tmpChrFile, chrPos, storage.mode = "integer", dims = c(nrow(dt), 2), level = 0))
          o <- .suppressAll(h5createDataset(tmpChrFile, chrRGLengths, storage.mode = "integer", dims = c(lengthRG, 1), level = 0))
          o <- .suppressAll(h5createDataset(tmpChrFile, chrRGValues, storage.mode = "character", 
                                            dims = c(lengthRG, 1), level = 0, size = max(nchar(RG@values)) + 1))
          
          o <- h5write(obj = cbind(dt$V2,dt$V3 - dt$V2 + 1), file = tmpChrFile, name = chrPos)
          o <- h5write(obj = RG@lengths, file = tmpChrFile, name = chrRGLengths)
          o <- h5write(obj = RG@values, file = tmpChrFile, name = chrRGValues)
          
          rm(dt, RG)
          gc()
          
          return(list(tmpChrFile = tmpChrFile, errorCheck = errorCheck))
          
        }
        
      }
      
    }, error = function(e){
      
      errorList <- list(
        x = x,
        tileChromSizes = tileChromSizes[x],
        fragments = if(exists("dt", inherits = FALSE)) dt else "Error with Fragments!"
      )
      

    })
    
    
  }, threads = threads)
  
  if(threads > 1){
    
    #Parallel Linkage Hdf5

    file.remove(tmpFile)
    o <- h5closeAll()
    fid <- H5Fcreate(tmpFile)
    
    o <- h5createGroup(fid, paste0("Fragments"))
    o <- h5createGroup(fid, paste0("Metadata"))
    o <- h5write(obj = "Arrow", file = fid, name = "Class")
    o <- h5write(obj = paste0(packageVersion("ArchR")), file = fid, name = "ArchRVersion")
    o <- h5write(obj = "tmp", file = fid, name = "Metadata/Sample")
    
    tmpChrFiles <- lapply(readTiledChrom, function(x) x$tmpChrFile) %>% unlist
    
    for(i in seq_along(tmpChrFiles)){
      
      tmpChrFilei <- tmpChrFiles[i]
      splitNames <- stringr::str_split(h5ls(tmpChrFilei)$name, "._.", simplify=TRUE)
      chunkName <- splitNames[,1]
      group <- splitNames[,2]
      
      o <- h5createGroup(fid, paste0("Fragments/", chunkName[1]))
      
      H5Lcreate_external(target_file_name = tmpChrFilei, 
                         target_obj_name = h5ls(tmpChrFilei)$name[1],
                         link_loc = fid,
                         link_name = paste0("Fragments/", chunkName[1], "/", group[1]))
      
      H5Lcreate_external(target_file_name = tmpChrFilei, 
                         target_obj_name = h5ls(tmpChrFilei)$name[2],
                         link_loc = fid,
                         link_name = paste0("Fragments/", chunkName[1], "/", group[2]))
      
      H5Lcreate_external(target_file_name = tmpChrFilei, 
                         target_obj_name = h5ls(tmpChrFilei)$name[3],
                         link_loc = fid,
                         link_name = paste0("Fragments/", chunkName[1], "/", group[3]))
      
    }
    H5Fclose(fid)
  }
  
  errorCheck <- sum(lapply(readTiledChrom, function(x) x$errorCheck) %>% unlist)
  
  return(tmpFile)
}
```

**Comment by rcorces** [comment] 2022-04-23 18:28
Hi @Zepeng-Mu! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by Zepeng-Mu** [comment] 2022-04-23 19:48
I installed the commit on March 17th "SHA:0aa874a05b2969c4796d30591f98c0e09937aa8a", and `createArrowFiles` works fine.

**Comment by rcorces** [comment] 2022-04-24 13:02
Confirming that I'm able to reproduce this. Will get to the bottom of it soon. At a quick glance, there havent been any commits to `createArrowFiles()` since the commit you reference so this is likely some other code change that is having unforeseen effects on `createArrowFiles()`

**Comment by rcorces** [comment] 2022-04-24 15:19
Seems to be localized to this commit but I cant figure out what it is. Will continue looking during the week.
https://github.com/GreenleafLab/ArchR/commit/6e7abec25de9217a8830ac1d6a853702c061bf8a

**Comment by mzhibo** [comment] 2022-04-24 15:41
I also started to have this error after updating to the newest commit (b40e6b3). The previous commit (3c43c850) installed on Mar 20 2022 worked fine.

**Comment by Zepeng-Mu** [comment] 2022-05-03 22:06
Hi @rcorces, since the relevant functions themselves are not changed in the commit that introduces this bug, I think it might have something to do with the namespace or environment of the package. Here is how I tested it:
```r
library(ArchR)
testArrow <- createArrowFiles(
  inputFiles = "HemeFragments/scATAC_PBMC_R1.fragments.tsv.gz",
  # genomeAnnotation = genomeAnnot,
  # geneAnnotation = gencode_anno,
  minTSS = 4,
  minFrags = 1000,
  nChunk = 10,
  addTileMat = F,
  addGeneScoreMat = F,
  threads = 5,
  force = T
)
```
In this way, the error happens.
Then I ran
```r
detach("package:ArchR", unload = TRUE)
R.utils::sourceDirectory("~/tools/ArchR")
testArrow <- createArrowFiles(
  inputFiles = "HemeFragments/scATAC_PBMC_R1.fragments.tsv.gz",
  # genomeAnnotation = genomeAnnot,
  # geneAnnotation = gencode_anno,
  minTSS = 4,
  minFrags = 1000,
  nChunk = 10,
  addTileMat = F,
  addGeneScoreMat = F,
  threads = 5,
  force = T
)
```
This unloads the package and load functions directory into Global Env from the cloned git repo.
Then if I run the same code above, no error appears!!
So I'm thinking maybe some packages/functions that are loaded by default is causing the error.
Hope this provides some clues.

Thanks.

**Comment by rcorces** [comment] 2022-05-03 22:43
yea you're right. Its a Namespace issue. I reverted the changes between `Imports` and `Depends`  made in https://github.com/GreenleafLab/ArchR/commit/6e7abec25de9217a8830ac1d6a853702c061bf8a and ArrowFile creation works for me. I imagine there was a reason that this change was made so I'll try to get to the bottom of this.

**Comment by jeffmgranja** [comment] 2022-05-04 05:31
This is now fixed sorry for the troubles!

```
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.2", repos = BiocManager::repositories())
library(ArchR)
fragments <- getTestFragments()
arrows <- createArrowFiles(fragments, force=TRUE)
# Using GeneAnnotation set by addArchRGenome(Hg19test)!
# Using GeneAnnotation set by addArchRGenome(Hg19test)!
# ArchR logging to : ArchRLogs/ArchR-createArrows-36473d0988e1-Date-2022-05-03_Time-22-30-12.log
# If there is an issue, please report to github with logFile!
# 2022-05-03 22:30:12 : Batch Execution w/ safelapply!, 0 mins elapsed.
# 2022-05-03 22:30:12 : (PBMC : 1 of 1) Arrow Exists! Overriding since force = TRUE!, 0 mins elapsed.
# 2022-05-03 22:30:12 : (PBMC : 1 of 1) Reading In Fragments from inputFiles (readMethod = tabix), 0 mins elapsed.
# 2022-05-03 22:30:12 : (PBMC : 1 of 1) Tabix Bed To Temporary File, 0 mins elapsed.
# 2022-05-03 22:30:21 : (PBMC : 1 of 1) Successful creation of Temporary File, 0.16 mins elapsed.
# 2022-05-03 22:30:21 : (PBMC : 1 of 1) Creating ArrowFile From Temporary File, 0.16 mins elapsed.
# 2022-05-03 22:30:24 : (PBMC : 1 of 1) Successful creation of Arrow File, 0.196 mins elapsed.
# 2022-05-03 22:30:27 : (PBMC : 1 of 1) CellStats : Number of Cells Pass Filter = 496 , 0.252 mins elapsed.
# 2022-05-03 22:30:27 : (PBMC : 1 of 1) CellStats : Median Frags = 1294 , 0.252 mins elapsed.
# 2022-05-03 22:30:27 : (PBMC : 1 of 1) CellStats : Median TSS Enrichment = 21.0325 , 0.252 mins elapsed.
# 2022-05-03 22:30:28 : (PBMC : 1 of 1) Adding Additional Feature Counts!, 0.266 mins elapsed.
# 2022-05-03 22:30:29 : (PBMC : 1 of 1) Removing Fragments from Filtered Cells, 0.293 mins elapsed.
# 2022-05-03 22:30:29 : (PBMC : 1 of 1) Creating Filtered Arrow File, 0.293 mins elapsed.
# 2022-05-03 22:30:30 : (PBMC : 1 of 1) Finished Constructing Filtered Arrow File!, 0.308 mins elapsed.
# 2022-05-03 22:30:30 : (PBMC : 1 of 1) Adding TileMatrix!, 0.309 mins elapsed.
# 2022-05-03 22:30:36 : (PBMC : 1 of 1) Adding GeneScoreMatrix!, 0.406 mins elapsed.
# 2022-05-03 22:30:40 : (PBMC : 1 of 1) Finished Creating Arrow File, 0.472 mins elapsed.
# ArchR logging successful to : ArchRLogs/ArchR-createArrows-36473d0988e1-Date-2022-05-03_Time-22-30-12.log
```

**Comment by rcorces** [comment] 2022-05-04 12:53
For posterity, this was an issue with the Namespace as suggested by @Zepeng-Mu and specifically with `data.table`. Fixed in `release_1.0.2` via https://github.com/GreenleafLab/ArchR/commit/ba21b05969c7d34125dcc56cdbabf0d64007e019

**Closed by rcorces** 2022-05-04 12:53 UTC
Labels: bug
