### ISSUE TITLE
addDoubletScores fails with ‘getNTrees’ is not a valid field or method name for reference class “Rcpp_AnnoyEuclidean”>

### ISSUE THREAD

**Issue by asmagen** [GreenleafLab/ArchR#420] opened 2020-11-13 21:00 UTC
I get the following error upon trying to compute doublet scores:
```
>     doubScores <- addDoubletScores(
+         input = ArrowFiles,
+         k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
+         knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search with doublet projection.
+         LSIMethod = 1
+     )
ArchR logging to : ArchRLogs/ArchR-addDoubletScores-246ea1db4a3a-Date-2020-11-13_Time-15-47-13.log
If there is an issue, please report to github with logFile!
2020-11-13 15:47:13 : Batch Execution w/ safelapply!, 0 mins elapsed.
2020-11-13 15:47:13 : T-KP-D21-mm10 (1 of 2) :  Computing Doublet Statistics, 0 mins elapsed.

************************************************************
2020-11-13 15:51:33 : ERROR Found in uwot::umap_transform for T-KP-D21-mm10 (1 of 2) :
LogFile = ArchRLogs/ArchR-addDoubletScores-246ea1db4a3a-Date-2020-11-13_Time-15-47-13.log

<simpleError in envRefInferField(x, what, getClass(class(x)), selfEnv): ‘getNTrees’ is not a valid field or method name for reference class “Rcpp_AnnoyEuclidean”>

************************************************************


************************************************************
2020-11-13 15:51:33 : ERROR Found in .simulateProjectDoublets for T-KP-D21-mm10 (1 of 2) :
LogFile = ArchRLogs/ArchR-addDoubletScores-246ea1db4a3a-Date-2020-11-13_Time-15-47-13.log

<simpleError in .logError(e, fn = "uwot::umap_transform", info = prefix, errorList = errorList,     logFile = logFile): Exiting See Error Above>

************************************************************

Error in .logError(e, fn = ".simulateProjectDoublets", info = prefix,  :
  Exiting See Error Above
```
Any idea of what might cause this?
Thanks

**Comment by rcorces** [comment] 2020-11-14 04:32
Have you run through the full tutorial with the tutorial data? This is not a normal error that we see and my assumption is that something is not set up properly on your system.

**Comment by jgranja24** [comment] 2020-11-26 07:32
This maybe related to the R 4.0 issues? Can you attach the log file?

**Comment by rcorces** [comment] 2020-11-26 14:37
Could also be an error caused by the newer uwot / RcppAnnoy versions

**Comment by jgranja24** [comment] 2020-12-13 04:38
I think this is now fixed with the new UWOT functionality, I am closing this see https://github.com/GreenleafLab/ArchR/issues/424

**Closed by jgranja24** 2020-12-13 04:38 UTC
Labels: bug
