### ISSUE TITLE
advice / doc request on subsetting projects

### ISSUE THREAD

**Issue by juliabelk** [GreenleafLab/ArchR#82] opened 2020-04-23 18:04 UTC
After subsetting a project, which analysis steps should I re-do? Clearly I need to re-do `addIterativeLSI` and `addUMAP`, which I am keeping track of by creating new names for each subsetted project. But should I redo the below steps? I was redoing everything, but I'm a bit confused because there is no "name" attribute for `addPeakMatrix` and so `addPeakMatrix` is I think overwriting the previous `PeakMatrix` in my project.

    proj <- addImputeWeights(proj, reducedDims=dr)
    proj <- addGroupCoverages(proj, groupBy=clustering)
    proj <- addReproduciblePeakSet(proj, groupBy=clustering)
    proj <- addPeakMatrix(proj)
    proj <- addMotifAnnotations(proj,force=TRUE)
    proj <- addDeviationsMatrix(proj)

### If this is an issue with documentation that is absent/missing:

**Describe what material you feel should be explained**
Currently subsetting is discussed very briefly as an example in section 3.2 and it would be great if this section could be expanded with more details

**Where do you think this documentation would belong?**
Subsetting is an important use case so I feel like this could have its own subsection (maybe 3.7)

**Comment by rcorces** [comment] 2020-04-23 18:28
I think this is a bit context specific and depends on your application. I will make a note to add a section on project subsetting in the user manual.

`addImputeWeights` is dependent on the `reducedDims` object so you would need to re-do that
`addGroupCoverages` is dependent on the clusters so presumably if you are re-running LSI, you should re-run clustering, and thus would need to re-run `addGroupCoverages` because you would be interested in the new grouping.
If you have new clusters, you would also need to re-make your reproducible peak set. which would then affect the motif annotations and deviations matrix.

I believe that it is assumed that a single project should only ever need one peak set and one set of group coverages. While I can envision why you might want to have multiple peak sets or group coverages, I think the correct solution is to make two separate projects. @jgranja24 - what do you think?

**Comment by juliabelk** [comment] 2020-04-23 18:38
I agree I would find it most straightforward to have new copies of everything -- however they are sharing ArrowFiles and so I am not sure the best way to do this. To be precise I do have a new "project", with the subsetted cells, but still the same arrow files (which is where the PeakMatrix is stored if I understand correctly). And I would prefer not to have to duplicate the arrow files many times because they are pretty big.

One solution would be to add a name attribute to the peak set and peak matrix so that multiple could be stored in the same arrow files.

**Comment by jgranja24** [comment] 2020-04-23 18:49
The way to subset is use subsetArchRProject if you intend on re-doing analysis. You need a brand new copy of the arrow files or else it will overwrite existing matrices. This function will copy arrows and set up a project ready for analysis.

**Comment by rcorces** [comment] 2020-04-23 18:57
@juliabelk - I dont think supporting multiple peak sets is realistic given the rest of the ArchR structure. Arrow files are large but not that large. As Jeff said, I think the presumed use is to create a separate ArchR project with a separate copy of the arrow files for each project or project subset that you are interested in. 

Closing

**Closed by rcorces** 2020-04-23 18:57 UTC
Labels: documentation

**Comment by juliabelk** [comment] 2020-04-23 19:00
ok thank you, `subsetArchRProject` is exactly what I was looking for! FYI I don't think this is currently in the docs, only `subsetCells` is covered in a brief example.

**Comment by rcorces** [comment] 2020-04-23 21:06
I will add a section for this. Thanks @juliabelk

**Comment by concatenize** [comment] 2020-05-06 12:07
Regarding subsetting: if I am going to send an analysis to a collaborator or copy a subset analysis to a new folder, what files do I need to include? Can I just send the arrows and the archr project RDS file, or do I need to include the entire output directory?

**Comment by rcorces** [comment] 2020-05-06 13:19
This is somewhat application specific but there are files other than the Arrow files and ArchRProject RDS file that are important. For example, group coverages. The safest thing is to provide the whole directory. I will make sure to cover this in the user manual once I get this section together.

> or copy a subset analysis to a new folder

Just to make sure this is obvious, __copying files/folders should never be done manually__ except for the entire project directory. The `saveArchRProject()` and `subsetArchRProject()` functions will copy files are recreate directory structures for you.

**Comment by concatenize** [comment] 2020-05-06 13:35
Thanks @rcorces ! About to send files to a collaborator today and that's very useful info.
