### ISSUE TITLE
getting gene name using idxRNA

### ISSUE THREAD

**Issue by yxiao832** [GreenleafLab/ArchR#368] opened 2020-10-28 14:06 UTC
Maybe I should open a new issue here instead of commenting on previous not direct relevant threads. Let me know if this is not appropriate.

I am trying to pull out the peaks associated with my genes of interest, but I am having an issue identifying corresponding gene name using idxRNA from peak2gene dataframe. It seems multiple genes using the same idx number. Or maybe I am looking at the wrong place.

> p2geneDF <- metadata(proj@peakSet)$Peak2GeneLinks
> gSet <- metadata(p2geneDF)$geneSet
> mcols(gSet)[mcols(gSet)$idx %in% c(834),]

The output is like:
DataFrame with 11 rows and 2 columns
            name     idx
         <array> <array>
1          Ildr2     834
2          Sarnp     834
3          Car10     834
4          Mrps5     834
5        Rabggtb     834
6          Ephb2     834
7           Rfc2     834
8          Pde6h     834
9  4930567K12Rik     834
10       Sipa1l2     834
11          Kif9     834

Thanks a lot!
Yang

**Comment by jgranja24** [comment] 2020-10-28 20:34
Hi @yxiao832, the idx refers to something different each matrix in ArchR that is chromosome based is `indexed per chromosome` ie that 834 is in multiple genes because its the 834th gene on that chromsome. Here is how to annotate your peak2gene links. This process makes a larger object so I kept it more compressed in storage ---

```
#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)
proj <- getTestProject()

if(!file.exists("scRNA-Hematopoiesis-Granja-2019.rds")){
    download.file(
        url = "https://jeffgranja.s3.amazonaws.com/ArchR/TestData/scRNA-Hematopoiesis-Granja-2019.rds",
        destfile = "scRNA-Hematopoiesis-Granja-2019.rds"
    )
}

seRNA <- readRDS("scRNA-Hematopoiesis-Granja-2019.rds")

proj <- addGeneIntegrationMatrix(
    ArchRProj = proj, 
    useMatrix = "GeneScoreMatrix",
    matrixName = "GeneIntegrationMatrix",
    reducedDims = "IterativeLSI",
    seRNA = seRNA,
    addToArrow = TRUE,
    verbose = FALSE,
    groupRNA = "BioClassification",
    nameCell = "predictedCell",
    nameGroup = "predictedGroup",
    nameScore = "predictedScore",
    force = TRUE
)

proj <- addPeak2GeneLinks(proj)

p2geneDF <- metadata(proj@peakSet)$Peak2GeneLinks
p2geneDF$geneName <- mcols(metadata(p2geneDF)$geneSet)$name[p2geneDF$idxRNA]
p2geneDF$peakName <- (metadata(p2geneDF)$peakSet %>% {paste0(seqnames(.), "_", start(.), "_", end(.))})[p2geneDF$idxATAC]

> p2geneDF
DataFrame with 153894 rows and 8 columns
         idxATAC    idxRNA         Correlation                  FDR
       <integer> <integer>           <numeric>            <numeric>
1              1         2 0.00714436960966568    0.891975576529501
2              2         2   0.206067895564052 1.08749544612577e-05
3              3         2   0.187709745154478  6.6277728575822e-05
4              4         2   0.230970917550565 7.09785052131589e-07
5              5         2   0.232274447292216 6.09708826430438e-07
...          ...       ...                 ...                  ...
153890     25504      3078   0.315701130804448 4.88826759376223e-12
153891     25505      3078   0.519923106200753 1.64848166416267e-33
153892     25506      3078   0.375368854528432 7.73492476815824e-17
153893     25507      3078  -0.444076195471676 9.17186406922461e-24
153894     25508      3078  -0.124051315528399  0.00960714755007798
                VarQATAC           VarQRNA  geneName                 peakName
               <numeric>         <numeric>   <array>              <character>
1      0.185941665359887 0.446718648473034 LINC00115       chr1_757871_758371
2       0.44766347812451 0.446718648473034 LINC00115       chr1_758489_758989
3      0.432099733416967 0.446718648473034 LINC00115       chr1_761835_762335
4      0.860906382311432 0.446718648473034 LINC00115       chr1_762697_763197
5      0.226556374470754 0.446718648473034 LINC00115       chr1_764481_764981
...                  ...               ...       ...                      ...
153890 0.128312686216089 0.423001949317739     PDCD1 chr2_243029037_243029537
153891 0.953151952328681 0.423001949317739     PDCD1 chr2_243030546_243031046
153892 0.217186764936491 0.423001949317739     PDCD1 chr2_243031340_243031840
153893 0.869923161361142 0.423001949317739     PDCD1 chr2_243040594_243041094
153894  0.23906225497883 0.423001949317739     PDCD1 chr2_243050293_243050793
```

**Comment by jgranja24** [comment] 2020-10-28 20:35
Closing this issue. Feel free to open new issues!

**Closed by jgranja24** 2020-10-28 20:35 UTC
Labels: documentation

**Comment by yxiao832** [comment] 2020-10-28 22:12
Thank you!!

**Comment by wangmhan** [comment] 2021-08-30 15:55
Hello, I have a related question.

I found the result1, I use the solution above is actually quite different from result2, I use getPeak2GeneLinks(). 

## result 1
p2geneDF <- metadata(proj@peakSet)$Peak2GeneLinks
p2geneDF$geneName <- mcols(metadata(p2geneDF)$geneSet)$name[p2geneDF$idxRNA]
p2geneDF$peakName <- (metadata(p2geneDF)$peakSet %>% {paste0(seqnames(.), "_", start(.), "_", end(.))})[p2geneDF$idxATAC]
p2geneDF=p2geneDF[!is.na(p2geneDF$FDR) & abs(p2geneDF$Correlation)>0.5 & p2geneDF$FDR<0.05 & (p2geneDF$VarQRNA > 0.25 & p2geneDF$VarQATAC > 0.25),]
dim(p2geneDF)-->156660      8

## result 2
p2g <- getPeak2GeneLinks(
  ArchRProj = proj,
  corCutOff = 0.5,FDRCutOff = 0.05,
  resolution = 1,
  returnLoops = FALSE
)
dim(p2g)--> 87326     6

I tune the argument resolution=1,1000,10000, but it didn't make a change.

Could you help me to understand why it can happen? Any necessary process I missed?
Really appreciated!

**Comment by rcorces** [comment] 2021-08-30 16:16
I do not understand your question.

With regards to this:
> I tune the argument resolution=1,1000,10000, but it didn't make a change.

That is the expected behavior as `resolution` only pertains to loops and you have `returnLoops = FALSE`
<html>
<body>


resolution | A numeric describing the bp resolution to return loops as. This helps with overplotting of correlated regions.
-- | --



</body>
</html>
