### ISSUE TITLE
saveArchRProject() creates empty arrow files

### ISSUE THREAD

**Issue by shaka87** [GreenleafLab/ArchR#99] opened 2020-05-03 09:15 UTC
Hello there, 

I just started using ArchR and I like it a lot. However, I have a problem that greatly reduces usability at this point: 
When I try to save an ArchR project using saveArchRProject(), the arrow files are empty. 

I create an ArchRProject like this: 

FCR.patient = ArchRProject(
  ArrowFiles = c('./1.arrow','./2.arrow','./3.arrow','./4.arrow','./5.arrow'),
  outputDirectory = './FCR.arch',
  copyArrows = T
)

Afterwards, I have 5 arrow files in the respective directory:

total 9120712
drwxr-xr-x@ 7 liviuspenter  staff         224 May  3 11:04 .
drwxr-xr-x@ 3 liviuspenter  staff          96 May  3 11:04 ..
-rw-r--r--@ 1 liviuspenter  staff  1066533709 May  3 11:04 1.arrow
-rw-r--r--@ 1 liviuspenter  staff  1098188050 May  3 11:04 2.arrow
-rw-r--r--@ 1 liviuspenter  staff  1115898480 May  3 11:04 3.arrow
-rw-r--r--@ 1 liviuspenter  staff   749139796 May  3 11:04 4.arrow
-rw-r--r--@ 1 liviuspenter  staff   619754548 May  3 11:04 5.arrow

When I save the ArchRProject, these files suddenly are empty:

saveArchRProject(ArchRProj = FCR.patient, outputDirectory = './FCR.arch')

total 0
drwxr-xr-x@ 7 liviuspenter  staff  224 May  3 11:04 .
drwxr-xr-x@ 4 liviuspenter  staff  128 May  3 11:08 ..
-rw-r--r--@ 1 liviuspenter  staff    0 May  3 11:08 1.arrow
-rw-r--r--@ 1 liviuspenter  staff    0 May  3 11:08 2.arrow
-rw-r--r--@ 1 liviuspenter  staff    0 May  3 11:08 3.arrow
-rw-r--r--@ 1 liviuspenter  staff    0 May  3 11:08 4.arrow
-rw-r--r--@ 1 liviuspenter  staff    0 May  3 11:08 5.arrow

I have also tried to use overwrite = T, but that doesn't change anything. 
Am I doing something wrong? Thank you!

**Output in R**
Copying Arrow Files...
Copying Arrow Files (1 of 5)
Copying Arrow Files (2 of 5)
Copying Arrow Files (3 of 5)
Copying Arrow Files (4 of 5)
Copying Arrow Files (5 of 5)
Getting ImputeWeights
No imputeWeights found, returning NULL
Copying Other Files...
Saving ArchRProject...
Loading ArchRProject...
Successfully loaded ArchRProject!
    
class: ArchRProject 
outputDirectory: /Users/liviuspenter/FCR.arch 
samples(5): 3 2 1 4 5
sampleColData names(1): ArrowFiles
cellColData names(15): Sample TSSEnrichment ... DoubletEnrichment BlacklistRatio
numberOfCells(1): 23970
medianTSS(1): 13.7175
medianFrags(1): 5714

**Session Info**
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin19.4.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.3.9/lib/libopenblasp-r0.3.9.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gridExtra_2.3                     ggrastr_0.1.7                     uwot_0.1.8                        nabor_0.5.0                      
 [5] Seurat_3.1.5                      BSgenome.Hsapiens.UCSC.hg38_1.4.3 BSgenome_1.56.0                   rtracklayer_1.48.0               
 [9] Biostrings_2.56.0                 XVector_0.28.0                    ArchR_0.9.2                       magrittr_1.5                     
[13] rhdf5_2.32.0                      Matrix_1.2-18                     data.table_1.12.8                 ggplot2_3.3.0                    
[17] SummarizedExperiment_1.18.0       DelayedArray_0.14.0               matrixStats_0.56.0                Biobase_2.48.0                   
[21] GenomicRanges_1.40.0              GenomeInfoDb_1.24.0               IRanges_2.22.1                    S4Vectors_0.26.0                 
[25] BiocGenerics_0.34.0              

loaded via a namespace (and not attached):
 [1] Rtsne_0.15               colorspace_1.4-1         ellipsis_0.3.0           ggridges_0.5.2           rstudioapi_0.11         
 [6] leiden_0.3.3             listenv_0.8.0            farver_2.0.3             npsurv_0.4-0             ggrepel_0.8.2           
[11] RSpectra_0.16-0          codetools_0.2-16         splines_4.0.0            lsei_1.2-0               jsonlite_1.6.1          
[16] Rsamtools_2.4.0          Cairo_1.5-12             ica_1.0-2                cluster_2.1.0            png_0.1-7               
[21] sctransform_0.2.1        compiler_4.0.0           httr_1.4.1               assertthat_0.2.1         lazyeval_0.2.2          
[26] htmltools_0.4.0          tools_4.0.0              rsvd_1.0.3               igraph_1.2.5             gtable_0.3.0            
[31] glue_1.4.0               GenomeInfoDbData_1.2.3   RANN_2.6.1               reshape2_1.4.4           dplyr_0.8.5             
[36] Rcpp_1.0.4.6             vctrs_0.2.4              gdata_2.18.0             ape_5.3                  nlme_3.1-147            
[41] lmtest_0.9-37            stringr_1.4.0            globals_0.12.5           lifecycle_0.2.0          irlba_2.3.3             
[46] gtools_3.8.2             XML_3.99-0.3             future_1.17.0            zlibbioc_1.34.0          MASS_7.3-51.6           
[51] zoo_1.8-7                scales_1.1.0             RColorBrewer_1.1-2       reticulate_1.15          pbapply_1.4-2           
[56] stringi_1.4.6            caTools_1.18.0           BiocParallel_1.22.0      rlang_0.4.5              pkgconfig_2.0.3         
[61] bitops_1.0-6             lattice_0.20-41          ROCR_1.0-7               purrr_0.3.4              Rhdf5lib_1.10.0         
[66] GenomicAlignments_1.24.0 patchwork_1.0.0          htmlwidgets_1.5.1        labeling_0.3             cowplot_1.0.0           
[71] tidyselect_1.0.0         RcppAnnoy_0.0.16         plyr_1.8.6               R6_2.4.1                 gplots_3.0.3            
[76] pillar_1.4.3             withr_2.2.0              fitdistrplus_1.0-14      survival_3.1-12          RCurl_1.98-1.2          
[81] tibble_3.0.1             future.apply_1.5.0       tsne_0.1-3               crayon_1.3.4             KernSmooth_2.23-17      
[86] plotly_4.9.2.1           digest_0.6.25            tidyr_1.0.2              munsell_0.5.0            viridisLite_0.3.0

**Comment by shaka87** [comment] 2020-05-03 12:55
Update: I just realized that if I only do saveArchRProject(ArchRProj = FCR.patient) without specifying the output directory, it seems to work.

**Comment by rcorces** [comment] 2020-05-03 13:55
Thanks for reporting this. I was able to recapitulate this bug with the tutorial data on my end. I think this is an edge case that we did not anticipate. The problem here is that the `outputDirectory` parameter was intended to specify a directory other than the directory indicated by `getOutputDirectory(ArchRProj)` so that you could create a snapshot of the current `ArchRProject` object and Arrow files and store it somewhere new. But 

@jgranja24 - You know this better than I do but here is my attempt to diagnose the problem.
1. I believe https://github.com/GreenleafLab/ArchR/blob/77c147deadbf067be2a698360f3a7d7f26c117f0/R/AllClasses.R#L501 should be inside of an `if(outputDirectory != outDirOld)` statement
2. I believe https://github.com/GreenleafLab/ArchR/blob/77c147deadbf067be2a698360f3a7d7f26c117f0/R/AllClasses.R#L551 is duplicated and should be replaced with a saveRDS statement within an `if(outputDirectory == outDirOld)`  statement
3. If you do # 2 above, you need to add a `message("Saving ArchRProject...")` to the `saveRDS` line inside the `if(outputDirectory != outDirOld)` statement

**Comment by jgranja24** [comment] 2020-05-04 17:19
I believe i fixed what the current issue is. I added normalizePath to correct for users inputing the same relative path in different ways. I also removed the duplicate saveRDS. This is now in the dev branch and once all checks are done will be committed to master sometime this week.

**Comment by rcorces** [comment] 2020-05-05 04:24
I have tested this on my end and it appears to work as expected.

@shaka87 - you can install the dev branch and test this yourself if you'd like.

`devtools::install_github( "GreenleafLab/ArchR", ref="dev_050120", repos = BiocManager::repositories() )`

Closing for now but re-open if you dont think this problem has been solved.

**Closed by rcorces** 2020-05-05 04:24 UTC
Labels: bug

**Comment by concatenize** [comment] 2020-05-06 12:20
This is a really impressive piece of software and I really appreciate how much work you have put in to keep the memory footprint low. As part of that, doesn't ArchR already modify the arrow files as the analysis proceeds? If so, then what else gets added by `saveArchRProject`?

**Comment by rcorces** [comment] 2020-05-06 13:23
@concatenize - this question doesn't seem related to the closed issue. In the future, create a documentation issue.

The addition of information to Arrow files is covered in the manual and publication:
https://www.archrproject.com/bookdown/what-is-an-arrow-file-archrproject.html

Nothing gets "added" to a project by `saveArchRProject()`. It is merely saving a snapshot of your project and Arrow files on disk for usage later.

**Comment by concatenize** [comment] 2020-05-06 13:34
Yes, I have read that page. This issue is about what should happen when you call `saveArchRProject()` with the output directory matching the current output directory, right? I am trying to understand whether doing that has any effect.

> In the future, create a documentation issue.

I understand. I am working on that; I just needed to test a couple more things first.

**Comment by rcorces** [comment] 2020-05-06 13:42
I see your question now. calling `saveArchRProject()` on the current directory does not alter Arrow files in any way. The primary function is to save an RDS file of the `ArchRProject` which is currently stored in memory.

Calling `saveArchRProject()` and providing a new `outputDirectory` also doesnt "alter" the Arrow files but it copies them to a new location, creates a new `ArchRProject` and re-normalizes all paths so that the `ArchRProject` knows where to find everything. Does that answer the question? I can work on making this more clear in the documentation.

**Comment by concatenize** [comment] 2020-05-06 13:48
Yes, that clears it up perfectly. It's also immediately useful to me because I am having separate issues with the development branch that is suggested above as the temporary fix. It's good to know I can just revert to the version I had as long as I avoid saving to the current directory. (I'll post that separate issue if I have time to reproduce it on the haematopoiesis data.)

**Comment by rcorces** [comment] 2020-05-06 13:54
You can still save to the current directory using the version of ArchR on the `master` branch (0.9.3) - just dont provide any value to the `outputDirectory` parameter and allow it to use its default. This should work.

**Comment by concatenize** [comment] 2020-05-06 13:58
I'm sorry, I'm not trying to be a pain here, but I thought you just said that would have no effect?

**Comment by rcorces** [comment] 2020-05-06 14:31
If my previous reply was unclear, just ignore it. This github issue is about a bug. I was explaining how to get around that bug on the master branch.

**Comment by concatenize** [comment] 2020-05-11 14:13
I am still having this issue even though I am not providing any value to the `outputDirectory` parameter. I am sorry but it seems that `saveArchRProject` does not create logs.

**Comment by rcorces** [comment] 2020-05-11 15:53
Please try to reproduce this behavior using the tutorial dataset from the user manual and provide a detailed log of the commands you used and the directory contents after relevant commands.

**Comment by concatenize** [comment] 2020-05-12 13:28
This script can reproduce the problem using the tutorial data. The issue was a line where I failed to do tilde-expansion while ensuring the output directory was correct.

[number_99.R](https://github.com/GreenleafLab/ArchR/files/4615860/number_99.R.txt)

**Comment by jgranja24** [comment] 2020-05-12 20:47
Ill look into this further

**Comment by jgranja24** [comment] 2020-05-13 20:30
Is this still occuring? If so please re-open the issue.

**Comment by concatenize** [comment] 2020-05-13 21:50
I haven't had it happen on either `dev_051120` or today's `master`. I was using the version mentioned [above](https://github.com/GreenleafLab/ArchR/issues/99#issuecomment-624663982).
