### ISSUE TITLE
import10xFeatureMatrix

### ISSUE THREAD

**Issue by HieuNg1598** [GreenleafLab/ArchR#1724] opened 2022-11-07 11:46 UTC
Sorry, i am currently doing on atac seq project but also new to this field and dont know why i got this error 
Could you help me fix this issue ?

seRNA <- import10xFeatureMatrix(
+   input = c("/media/singlecell/TOSHIBA EXT/snATAC-seq/TBI RNA seq/BI-ANA-4781/Cellranger_default/XO-cellplex/outs/per_sample_outs/O_DHEA/count/sample_filtered_feature_bc_matrix.h5"),
+   names = c("dhea")
+ )
Importing Feature Matrix 1 of 1
Re-ordering RNA matricies for consistency.
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'rep.int': error in evaluating the argument 'x' in selecting a method for function 'runValue': error in evaluating the argument 'x' in selecting a method for function 'seqnames': error in evaluating the argument 'x' in selecting a method for function 'sortSeqlevels': error in evaluating the argument 'x' in selecting a method for function 'seqlevels': unable to find an inherited method for function ‘seqinfo’ for signature ‘"SummarizedExperiment"’

**Comment by rcorces** [comment] 2022-11-07 11:46
Hi @HieuNg1598! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment] 2022-11-07 13:33
Please show me what `featureMats` looks like after you run this command where `input` and `names` are the values you passed to the function in your original post:

```
featureMats <- lapply(seq_along(input), function(y) {
    message("Importing Feature Matrix ", y, " of ", length(input))
    ArchR:::.importFM(featureMatrix = input[y], featureType = "Gene Expression", 
              name = names[y])
  })
```

**Comment by HieuNg1598** [comment] 2022-11-07 14:04
it works. 
So i can use featureMats as seRNA for the further downstream analysis ? 
Really appreciate your solution and your ArchR platform . It helps me a lot for this project .
Btw, i want to ask about the method for combining RNA dataset before intergration with ATAC dataset as i want to compare 3 different samples . Can you help me provide the method or code ?

**Comment by rcorces** [comment] 2022-11-07 14:22
> So i can use featureMats as seRNA for the further downstream analysis ?

No - I asked to see what the object looked like

> Btw, i want to ask about the method for combining RNA dataset before intergration with ATAC dataset as i want to compare 3 different samples . Can you help me provide the method or code ?

If you are talking about multiome data, `import10xFeatureMatrix()` handles multiple files as input.

**Comment by HieuNg1598** [comment] 2022-11-07 15:14
ok so this is what featureMats looks like .
> featureMats
[[1]]
class: SummarizedExperiment 
dim: 32245 9901 
metadata(0):
assays(1): counts
rownames(32245): Xkr4 Gm1992 ... AC234645.1 AC149090.1
rowData names(7): feature_type genome ... read sequence
colnames(9901): dhea#AAACCCAAGTCATTGC-1 dhea#AAACCCACAATATCCG-1 ...
  dhea#TTTGTTGTCTGCCTCA-1 dhea#TTTGTTGTCTTCTTCC-1
colData names(0):

**Comment by rcorces** [comment] 2022-11-07 16:23
can you upgrade to the `dev` branch and try running your original function call?
```
devtools::install_github("GreenleafLab/ArchR", ref="dev", repos = BiocManager::repositories())
#to unload a package and reload
detach("package:ArchR", unload=TRUE)
library(ArchR)
```

**Comment by HieuNg1598** [comment] 2022-11-08 00:53
After i followed your guide, somehow i thought it would be okay but then i got another error when i tried to use function addGeneExpressionMatrix (below)

> seRNA <- import10xFeatureMatrix(
+   input = c("/media/singlecell/TOSHIBA EXT/snATAC-seq/TBI RNA seq/BI-ANA-4781/Cellranger_default/XO-cellplex/outs/per_sample_outs/O_DHEA/count/sample_filtered_feature_bc_matrix.h5"),
+   names = c("dhea")
+ )
Importing Feature Matrix 1 of 1
> seRNA
class: SummarizedExperiment 
dim: 32285 9901 
metadata(0):
assays(1): data
rownames(32285): 0610005C13Rik 0610006L08Rik ... Zzef1 Zzz3
rowData names(7): feature_type genome ... read sequence
colnames(9901): dhea#AAACCCAAGTCATTGC-1 dhea#AAACCCACAATATCCG-1 ... dhea#TTTGTTGTCTGCCTCA-1 dhea#TTTGTTGTCTTCTTCC-1
colData names(0):

**ERROR:**
> proj <- addGeneExpressionMatrix(input = dhea, seRNA = seRNA, force = TRUE)
ArchR logging to : ArchRLogs/ArchR-addGeneExpressionMatrix-3e3bfc54880ac-Date-2022-11-08_Time-08-50-27.log
If there is an issue, please report to github with logFile!
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqnames’ for signature ‘"SummarizedExperiment"’

**Comment by rcorces** [comment] 2022-11-08 13:44
Thanks for trying the `dev` branch. There is either something wrong with your input file or your environment. Can you run the multiome tutorial and let me know if it works? The most up-to-date tutorial isnt published yet but can be found here for the time being:
https://github.com/GreenleafLab/ArchR_Website/blob/ui_updates/bookdown/XX_MultiomicDataAnalysis.Rmd

**Comment by HieuNg1598** [comment] 2022-11-08 15:07
Thank you so much. I tried your code but then encountered some problems like these . Can you check what happened cause the paths to all the files are correct but they still showed no such file or directory leading to no arrowfiles could be created.

library(ArchR)
addArchRGenome("mm10")
addArchRThreads(32)
set.seed(1)

atacFiles <- c("control" = "/media/singlecell/TOSHIBA EXT/snATAC-seq/NGS1090763/Sham/outs/fragments.tsv.gz",
               "tbi" = "/media/singlecell/TOSHIBA EXT/snATAC-seq/NGS1090763/TBI/outs/fragments.tsv.gz",
               "dhea" = "/media/singlecell/TOSHIBA EXT/snATAC-seq/NGS1090763/TBI_DHEA/outs/fragments.tsv.gz")

rnaFiles <- c("control" = "/media/singlecell/TOSHIBA EXT/snATAC-seq/TBI RNA seq/BI-ANA-4781/Cellranger_default/XO-cellplex/outs/per_sample_outs/X_DMSO/count/sample_filtered_feature_bc_matrix.h5", 
              "tbi" = "/media/singlecell/TOSHIBA EXT/snATAC-seq/TBI RNA seq/BI-ANA-4781/Cellranger_default/XO-cellplex/outs/per_sample_outs/O_DMSO/count/sample_filtered_feature_bc_matrix.h5",
              "dhea" = "/media/singlecell/TOSHIBA EXT/snATAC-seq/TBI RNA seq/BI-ANA-4781/Cellranger_default/XO-cellplex/outs/per_sample_outs/O_DHEA/count/sample_filtered_feature_bc_matrix.h5" )

names(atacFiles)
names(rnaFiles)
all.equal(names(atacFiles), names(rnaFiles))

ArrowFiles <- createArrowFiles(
  inputFiles = atacFiles,
  sampleNames = names(atacFiles),
  minTSS = 4,
  minFrags = 1000,
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

**ERROR:**
[14057:14057:20221108,225735.187392:ERROR elf_dynamic_array_reader.h:61] tag not found
[14057:14057:20221108,225735.187422:ERROR elf_dynamic_array_reader.h:61] tag not found
[14057:14057:20221108,225735.187456:ERROR elf_dynamic_array_reader.h:61] tag not found
[14057:14060:20221108,225735.212108:ERROR directory_reader_posix.cc:42] opendir: No such file or directory (2)
2022-11-08 23:02:10 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
ArchR logging successful to : ArchRLogs/ArchR-createArrows-3e529950e408a4-Date-2022-11-08_Time-22-56-01.log
Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  1 function calls resulted in an error

**Comment by rcorces** [comment] 2022-11-08 16:20
Sorry if my previous request was unclear. Please run the tutorial code on the tutorial data, not your own data.

**Comment by HieuNg1598** [comment] 2022-11-17 12:53
Thank you .
Also i want to ask is there other way that i can annotate my cluster of atac seq dataset solely based on the activity of promoters without the need of rna seq projection. In my folder, i have the file named peak_annotation.tsv , until now, i dont know how to utilize this file, i am supposed this file can help me deal with the annotation.
Hope to hear from you soon.

**Comment by rcorces** [comment] 2022-11-17 13:51
I'm not sure exactly what you are asking. On the `dev` branch, you should be able to use `plotEmbedding()` to visualize the activity of specific peaks. You could also group multiple peaks into a module via `addModuleScore()` and visualize the activity of that module. Since this is unrelated to your initial issue, I am closing this issue. Please remember that usage questions should be posted in Discussions while bugs and error reports should be posted to Issues.

**Closed by rcorces** 2022-11-17 13:51 UTC
Labels: bug
