### ISSUE TITLE
Ordering of markers in Heatmap

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#511] opened 2021-01-25 00:35 UTC
Hi,

 For the plotMarkerHeatmap() function how can I control the order in which the transposed Markers appear in the Heatmap?

Thanks

**Comment by rcorces** [comment] 2021-01-25 15:42
this sounds like a duplicate of #329
I'm going to close this but if you dont think it is a duplicate, just comment why and I'll re-open.

I dont think this is possible at the moment.

**Comment by rcorces** [comment] 2021-01-25 15:43
I know it isnt a direct duplicate, but i think that you could post over there to keep issues tidy for us.

**Closed by rcorces** 2021-01-25 15:42 UTC
Labels: documentation

**Comment by sylestiel** [comment] 2021-01-25 16:58
Point taken!

Setting binaryClusterRows = FALSE,  clusterCols = FALSE helped to some degree.
