### ISSUE TITLE
Error in subsetting in archr project

### ISSUE THREAD

**Issue by lsundaram** [GreenleafLab/ArchR#212] opened 2020-06-15 06:28 UTC
Hi I am trying to subset the archr obj by extracting cell from a few clusters and running into the below error. When i subset an archr object without motif matrix it subsets fine. But when it has a motif matrix i get this error. please advice if i am doing something wrong.  It did not give me a log file to attach.

Copying ArchRProject to new outputDirectory : /scratch//lsundaram/single_cell/data/archr_input_output/subsetfold

Copying Arrow Files...

Warning message in mclapply(..., mc.cores = threads, mc.preschedule = preschedule):
"3 function calls resulted in an error"
Error in .safelapply(seq_along(inArrows), function(x) {: 
Error Found Iteration 1 : 
	[1] "Error in h5read(ArrowFile, paste0(subGroup, \"/Info/CellNames\")) : \n  Object 'MotifMatrix/Info/CellNames' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(subGroup, "/Info/CellNames")): Object 'MotifMatrix/Info/CellNames' does not exist in this HDF5 file.>
Error Found Iteration 2 : 
	[1] "Error in h5read(ArrowFile, paste0(subGroup, \"/Info/CellNames\")) : \n  Object 'MotifMatrix/Info/CellNames' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(subGroup, "/Info/CellNames")): Object 'MotifMatrix/Info/CellNames' does not exist in this HDF5 file.>
Error Found Iteration 3 : 
	[1] "Error in h5read(ArrowFile, paste0(subGroup, \"/Info/CellNames\")) : \n  Object 'MotifMatrix/Info/CellNames' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(subGroup, "/Info/CellNames")): Object 'MotifMatrix/Info/CellNames' does not exist in this HDF5 file.>

Traceback:

1. subsetArchRProject(proj, cells = get_cardiomyocytes_Cells, outputDirectory = "/scratch//lsundaram/single_cell/data/archr_input_output/subsetfold")
2. saveArchRProject(ArchRProj = ArchRProj[cells, ], outputDirectory = outputDirectory, 
 .     load = TRUE, dropCells = dropCells, logFile = logFile, threads = threads)
3. .copyArrows(inArrows = ArrowFiles, outArrows = ArrowFilesNew, 
 .     cellsKeep = ArchRProj$cellNames, logFile = logFile, threads = threads)
4. unlist(.safelapply(seq_along(inArrows), function(x) {
 .     .copyArrowSingle(inArrow = inArrows[x], outArrow = outArrows[x], 
 .         cellsKeep = cellsKeep, level = level, verbose = verbose, 
 .         logFile = logFile)
 . }, threads = threads))
5. .safelapply(seq_along(inArrows), function(x) {
 .     .copyArrowSingle(inArrow = inArrows[x], outArrow = outArrows[x], 
 .         cellsKeep = cellsKeep, level = level, verbose = verbose, 
 .         logFile = logFile)
 . }, threads = threads)
6. stop(errorMsg)

**Comment by jgranja24** [comment] 2020-06-15 18:45
Can you try h5ls(getArrowFiles(proj)[1]) to list the contents of an ArrowFile. Additionally, this returns nothing -
`
h5read(getArrowFiles(proj)[1], "MotifMatrix/Info/CellNames")
`

**Comment by lsundaram** [comment] 2020-06-15 20:50
Yes all that is fine. I also get output for both the commands. The h5read(getArrowFiles(proj)[1], "MotifMatrix/Info/CellNames") returns barcode names

**Comment by Sophiesze** [comment] 2020-06-17 13:34
Hi @jgranja24,
I also meet the same issue when I try to use `subsetArchRProject()`.

<img width="1179" alt="截屏2020-06-17 下午9 32 30" src="https://user-images.githubusercontent.com/53801318/84904732-3ebea380-b0e2-11ea-908a-b2d351bb3935.png">
<img width="534" alt="截屏2020-06-17 下午9 33 22" src="https://user-images.githubusercontent.com/53801318/84904740-4120fd80-b0e2-11ea-97cb-29e16b415917.png">

**Comment by jgranja24** [comment] 2020-06-23 07:08
Sorry for the delay Im still looking into this

**Comment by juliabelk** [comment] 2020-06-28 03:37
@jgranja24 I am also running into this error

**Comment by juliabelk** [comment] 2020-06-28 04:15
FYI here is a workaround that solved this for me:

subsetArchRProject(...,dropCells=FALSE)

**Comment by e-arslan** [comment] 2020-10-26 18:22
any solution for this problem?

**Comment by jgranja24** [comment] 2020-10-26 18:59
Sorry for the delays.. I fixed this in the current release branch. It was a silly bug but nonetheless it has been addressed.

See below for a simple test example -

```
#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)

#######################
# Old Result
#######################
proj <- getTestProject()
projSubset <- subsetArchRProject(proj, sample(proj$cellNames, 100))

# Copying ArchRProject to new outputDirectory : /oak/stanford/groups/howchang/users/jgranja/ArchRTutorial/Test/ArchRSubset
# Copying Arrow Files...
# Error in h5read(ArrowFile, paste0(subGroup, "/Info/CellNames")) : 
#   Object 'MotifMatrix/Info/CellNames' does not exist in this HDF5 file.

#######################
# New Result
#######################
proj <- getTestProject()
projSubset <- subsetArchRProject(proj, sample(proj$cellNames, 100), force = TRUE)

# Copying ArchRProject to new outputDirectory : /oak/stanford/groups/howchang/users/jgranja/ArchRTutorial/Test/ArchRSubset
# Copying Arrow Files...
# Getting ImputeWeights
# No imputeWeights found, returning NULL
# Copying Other Files...
# Copying Other Files (1 of 6): Annotations
# Copying Other Files (2 of 6): Embeddings
# Copying Other Files (3 of 6): GroupCoverages
# Copying Other Files (4 of 6): PBMCSmall
# Copying Other Files (5 of 6): PeakCalls
# Copying Other Files (6 of 6): Plots
# Saving ArchRProject...
# Loading ArchRProject...
# Successfully loaded ArchRProject!

#                                                    / |
#                                                  /    \
#             .                                  /      |.
#             \\\                              /        |.
#               \\\                          /           `|.
#                 \\\                      /              |.
#                   \                    /                |\
#                   \\#####\           /                  ||
#                 ==###########>      /                   ||
#                  \\##==......\    /                     ||
#             ______ =       =|__ /__                     ||      \\\
#         ,--' ,----`-,__ ___/'  --,-`-===================##========>
#        \               '        ##_______ _____ ,--,__,=##,__   ///
#         ,    __==    ___,-,__,--'#'  ==='      `-'    | ##,-/
#         -,____,---'       \\####\\________________,--\\_##,/
#            ___      .______        ______  __    __  .______      
#           /   \     |   _  \      /      ||  |  |  | |   _  \     
#          /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |    
#         /  /_\  \   |      /     |  |     |   __   | |      /     
#        /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
#       /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|

```

**Comment by jgranja24** [comment] 2020-10-28 02:59
I am closing this issue. If you have further issues please add more comments or open a new issue! Thanks for your patience! Excited to get this more stable release out soon!

**Comment by ccruizm** [comment] 2021-01-01 13:26
Good day,

I am having trouble subsetting an `ArchR` object. Below the error:
```
Dropping ImputeWeights Since You Are Subsetting Cells! ImputeWeights is a cell-x-cell Matrix!

Copying ArchRProject to new outputDirectory : /hpc/pmc_stunnenberg/cruiz/scATAC/analysis/dipg_ascites/notebooks/primary_tumor/archr/ArchRSubset

Copying Arrow Files...

.copyArrow : Initializing Out ArrowFile

.copyArrow : Adding Metadata to Out ArrowFile

.copyArrow : Adding SubMatrices to Out ArrowFile

Error in H5Fopen(file): HDF5. File accessibilty. Unable to open file.
Traceback:

1. subsetArchRProject(projdipg, cellsSample, force = TRUE)
2. saveArchRProject(ArchRProj = ArchRProj[cells, ], outputDirectory = outputDirectory, 
 .     load = TRUE, dropCells = dropCells, logFile = logFile, threads = threads)
3. .copyArrows(inArrows = ArrowFiles, outArrows = ArrowFilesNew, 
 .     cellsKeep = ArchRProj$cellNames, logFile = logFile, threads = threads)
4. unlist(.safelapply(seq_along(inArrows), function(x) {
 .     .copyArrowSingle(inArrow = inArrows[x], outArrow = outArrows[x], 
 .         cellsKeep = cellsKeep, level = level, verbose = verbose, 
 .         logFile = logFile)
 . }, threads = threads))
5. .safelapply(seq_along(inArrows), function(x) {
 .     .copyArrowSingle(inArrow = inArrows[x], outArrow = outArrows[x], 
 .         cellsKeep = cellsKeep, level = level, verbose = verbose, 
 .         logFile = logFile)
 . }, threads = threads)
6. mclapply(..., mc.cores = threads, mc.preschedule = preschedule)
7. lapply(X = X, FUN = FUN, ...)
8. FUN(X[[i]], ...)
9. .copyArrowSingle(inArrow = inArrows[x], outArrow = outArrows[x], 
 .     cellsKeep = cellsKeep, level = level, verbose = verbose, 
 .     logFile = logFile)
10. paste0(sampleName, "#", .h5read(inArrow, paste0(groupName, "/Info/CellNames")))
11. .h5read(inArrow, paste0(groupName, "/Info/CellNames"))
12. H5Fopen(file)
```
and `sessionInfo`:
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /hpc/pmc_stunnenberg/cruiz/miniconda3/envs/r_env_4.0.3/lib/libopenblasp-r0.3.10.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] stringr_1.4.0               Seurat_3.9.9.9023          
 [3] ArchR_1.0.1                 magrittr_2.0.1             
 [5] rhdf5_2.34.0                Matrix_1.2-18              
 [7] data.table_1.13.4           SummarizedExperiment_1.20.0
 [9] Biobase_2.50.0              GenomicRanges_1.42.0       
[11] GenomeInfoDb_1.26.2         IRanges_2.24.1             
[13] S4Vectors_0.28.1            BiocGenerics_0.36.0        
[15] MatrixGenerics_1.2.0        matrixStats_0.57.0         
[17] ggplot2_3.3.2.9000         

loaded via a namespace (and not attached):
  [1] Rtsne_0.15                        colorspace_2.0-0                 
  [3] deldir_0.2-3                      ellipsis_0.3.1                   
  [5] ggridges_0.5.2                    BSgenome.Hsapiens.UCSC.hg38_1.4.3
  [7] IRdisplay_0.7.0                   XVector_0.30.0                   
  [9] base64enc_0.1-3                   spatstat.data_1.7-0              
 [11] leiden_0.3.6                      listenv_0.8.0                    
 [13] ggrepel_0.9.0                     codetools_0.2-18                 
 [15] splines_4.0.3                     polyclip_1.10-0                  
 [17] IRkernel_1.1.1                    jsonlite_1.7.2                   
 [19] Rsamtools_2.6.0                   ica_1.0-2                        
 [21] cluster_2.1.0                     png_0.1-7                        
 [23] uwot_0.1.10                       shiny_1.5.0                      
 [25] sctransform_0.3.2.9000            compiler_4.0.3                   
 [27] httr_1.4.2                        fastmap_1.0.1                    
 [29] lazyeval_0.2.2                    later_1.1.0.1                    
 [31] htmltools_0.5.0                   tools_4.0.3                      
 [33] rsvd_1.0.3                        igraph_1.2.6                     
 [35] gtable_0.3.0                      glue_1.4.2                       
 [37] GenomeInfoDbData_1.2.4            RANN_2.6.1                       
 [39] reshape2_1.4.4                    dplyr_1.0.2                      
 [41] Rcpp_1.0.5                        spatstat_1.64-1                  
 [43] scattermore_0.7                   Biostrings_2.58.0                
 [45] vctrs_0.3.6                       rhdf5filters_1.2.0               
 [47] nlme_3.1-150                      rtracklayer_1.50.0               
 [49] lmtest_0.9-38                     globals_0.14.0                   
 [51] mime_0.9                          miniUI_0.1.1.1                   
 [53] lifecycle_0.2.0                   irlba_2.3.3                      
 [55] XML_3.99-0.5                      goftest_1.2-2                    
 [57] future_1.21.0                     zlibbioc_1.36.0                  
 [59] MASS_7.3-53                       zoo_1.8-8                        
 [61] scales_1.1.1                      BSgenome_1.58.0                  
 [63] promises_1.1.1                    spatstat.utils_1.17-0            
 [65] RColorBrewer_1.1-2                reticulate_1.18                  
 [67] pbapply_1.4-3                     gridExtra_2.3                    
 [69] rpart_4.1-15                      stringi_1.5.3                    
 [71] BiocParallel_1.24.1               repr_1.1.0                       
 [73] rlang_0.4.10                      pkgconfig_2.0.3                  
 [75] bitops_1.0-6                      evaluate_0.14                    
 [77] lattice_0.20-41                   tensor_1.5                       
 [79] ROCR_1.0-11                       purrr_0.3.4                      
 [81] Rhdf5lib_1.12.0                   GenomicAlignments_1.26.0         
 [83] patchwork_1.1.1                   htmlwidgets_1.5.3                
 [85] cowplot_1.1.0                     tidyselect_1.1.0                 
 [87] parallelly_1.22.0                 RcppAnnoy_0.0.18                 
 [89] plyr_1.8.6                        R6_2.5.0                         
 [91] generics_0.1.0                    pbdZMQ_0.3-3.1                   
 [93] DelayedArray_0.16.0               mgcv_1.8-33                      
 [95] pillar_1.4.7                      withr_2.3.0                      
 [97] fitdistrplus_1.1-3                abind_1.4-5                      
 [99] survival_3.2-7                    RCurl_1.98-1.2                   
[101] tibble_3.0.4                      future.apply_1.6.0               
[103] crayon_1.3.4                      uuid_0.1-4                       
[105] KernSmooth_2.23-18                plotly_4.9.2.2                   
[107] grid_4.0.3                        digest_0.6.27                    
[109] xtable_1.8-4                      tidyr_1.1.2                      
[111] httpuv_1.5.4                      munsell_0.5.0                    
[113] viridisLite_0.3.0                
```
What could be the reason for this issue? Thanks in advance!

**Comment by jgranja24** [comment] 2021-01-04 06:32
I will test it on R 4.0.3 in the next day and see if i can reproduce this.

**Comment by ccruizm** [comment] 2021-01-04 09:12
Thanks! I also tested it on R4.0 but got another error (keeping in mind that I tried to subset an object that was created with the versions of the packages mentioned above)

```
Copying ArchRProject to new outputDirectory : /hpc/pmc_stunnenberg/cruiz/scATAC/analysis/notebooks/primary_tumor/archr/ArchRSubset

Copying Arrow Files...

.copyArrow : Initializing Out ArrowFile

.copyArrow : Adding Metadata to Out ArrowFile

.copyArrow : Adding SubMatrices to Out ArrowFile

Error in h5read(ArrowFile, paste0(subGroup, "/Info/CellNames")): Object 'MotifMatrix/Info/CellNames' does not exist in this HDF5 file.
Traceback:

1. subsetArchRProject(projdipg, cellsSample)
2. saveArchRProject(ArchRProj = ArchRProj[cells, ], outputDirectory = outputDirectory, 
 .     load = TRUE, dropCells = dropCells, logFile = logFile, threads = threads)
3. .copyArrows(inArrows = ArrowFiles, outArrows = ArrowFilesNew, 
 .     cellsKeep = ArchRProj$cellNames, logFile = logFile, threads = threads)
4. unlist(.safelapply(seq_along(inArrows), function(x) {
 .     .copyArrowSingle(inArrow = inArrows[x], outArrow = outArrows[x], 
 .         cellsKeep = cellsKeep, level = level, verbose = verbose, 
 .         logFile = logFile)
 . }, threads = threads))
5. .safelapply(seq_along(inArrows), function(x) {
 .     .copyArrowSingle(inArrow = inArrows[x], outArrow = outArrows[x], 
 .         cellsKeep = cellsKeep, level = level, verbose = verbose, 
 .         logFile = logFile)
 . }, threads = threads)
6. mclapply(..., mc.cores = threads, mc.preschedule = preschedule)
7. lapply(X = X, FUN = FUN, ...)
8. FUN(X[[i]], ...)
9. .copyArrowSingle(inArrow = inArrows[x], outArrow = outArrows[x], 
 .     cellsKeep = cellsKeep, level = level, verbose = verbose, 
 .     logFile = logFile)
10. .addMatToArrow(mat = mat, ArrowFile = outArrow, Group = paste0(groupName, 
  .     "/", seqOrder[j]), binarize = all(mat@x == 1), addColSums = "colSums" %in% 
  .     addAnalysis, addRowSums = "rowSums" %in% addAnalysis, addRowMeans = "rowMeans" %in% 
  .     addAnalysis, addRowVars = "rowVars" %in% addAnalysis, addRowVarsLog2 = "rowVarsLog2" %in% 
  .     addAnalysis)
11. .availableCells(ArrowFile, dirname(Group))
12. h5read(ArrowFile, paste0(subGroup, "/Info/CellNames"))
13. stop("Object '", name, "' does not exist in this HDF5 file.") 
```
and `sessionInfo`:
```
R version 4.0.0 (2020-04-24)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /hpc/pmc_stunnenberg/cruiz/miniconda3/envs/r_env_4.0/lib/libopenblasp-r0.3.9.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] stringr_1.4.0               Seurat_3.2.2               
 [3] ArchR_0.9.5                 magrittr_2.0.1             
 [5] rhdf5_2.32.2                Matrix_1.2-18              
 [7] data.table_1.13.4           SummarizedExperiment_1.18.1
 [9] DelayedArray_0.14.0         matrixStats_0.57.0         
[11] Biobase_2.48.0              GenomicRanges_1.40.0       
[13] GenomeInfoDb_1.24.0         IRanges_2.22.1             
[15] S4Vectors_0.26.0            BiocGenerics_0.34.0        
[17] ggplot2_3.3.2              

loaded via a namespace (and not attached):
  [1] Rtsne_0.15                        colorspace_2.0-0                 
  [3] deldir_0.1-29                     ellipsis_0.3.1                   
  [5] ggridges_0.5.2                    BSgenome.Hsapiens.UCSC.hg38_1.4.3
  [7] IRdisplay_0.7.0                   XVector_0.28.0                   
  [9] base64enc_0.1-3                   spatstat.data_1.4-3              
 [11] leiden_0.3.3                      listenv_0.8.0                    
 [13] ggrepel_0.8.2                     codetools_0.2-16                 
 [15] splines_4.0.0                     polyclip_1.10-0                  
 [17] IRkernel_1.1                      jsonlite_1.7.2                   
 [19] Rsamtools_2.4.0                   ica_1.0-2                        
 [21] cluster_2.1.0                     png_0.1-7                        
 [23] uwot_0.1.8                        shiny_1.5.0                      
 [25] sctransform_0.3                   compiler_4.0.0                   
 [27] httr_1.4.2                        fastmap_1.0.1                    
 [29] lazyeval_0.2.2                    later_1.1.0.1                    
 [31] htmltools_0.5.0                   tools_4.0.0                      
 [33] rsvd_1.0.3                        igraph_1.2.6                     
 [35] gtable_0.3.0                      glue_1.4.2                       
 [37] GenomeInfoDbData_1.2.3            RANN_2.6.1                       
 [39] reshape2_1.4.4                    dplyr_1.0.2                      
 [41] rappdirs_0.3.1                    Rcpp_1.0.5                       
 [43] spatstat_1.64-1                   Biostrings_2.56.0                
 [45] vctrs_0.3.5                       nlme_3.1-148                     
 [47] rtracklayer_1.48.0                lmtest_0.9-38                    
 [49] globals_0.14.0                    mime_0.9                         
 [51] miniUI_0.1.1.1                    lifecycle_0.2.0                  
 [53] irlba_2.3.3                       XML_3.99-0.3                     
 [55] goftest_1.2-2                     future_1.21.0                    
 [57] zlibbioc_1.34.0                   MASS_7.3-51.6                    
 [59] zoo_1.8-8                         scales_1.1.1                     
 [61] BSgenome_1.56.0                   promises_1.1.1                   
 [63] spatstat.utils_1.17-0             RColorBrewer_1.1-2               
 [65] reticulate_1.16                   pbapply_1.4-3                    
 [67] gridExtra_2.3                     rpart_4.1-15                     
 [69] stringi_1.5.3                     BiocParallel_1.22.0              
 [71] repr_1.1.0                        rlang_0.4.9                      
 [73] pkgconfig_2.0.3                   bitops_1.0-6                     
 [75] evaluate_0.14                     lattice_0.20-41                  
 [77] tensor_1.5                        ROCR_1.0-11                      
 [79] purrr_0.3.4                       Rhdf5lib_1.10.1                  
 [81] GenomicAlignments_1.24.0          patchwork_1.1.0.9000             
 [83] htmlwidgets_1.5.3                 cowplot_1.1.0                    
 [85] tidyselect_1.1.0                  parallelly_1.22.0                
 [87] RcppAnnoy_0.0.16                  plyr_1.8.6                       
 [89] R6_2.5.0                          generics_0.1.0                   
 [91] pbdZMQ_0.3-3                      mgcv_1.8-31                      
 [93] pillar_1.4.7                      withr_2.3.0                      
 [95] fitdistrplus_1.1-1                abind_1.4-5                      
 [97] survival_3.1-12                   RCurl_1.98-1.2                   
 [99] tibble_3.0.4                      future.apply_1.6.0               
[101] crayon_1.3.4                      uuid_0.1-4                       
[103] KernSmooth_2.23-17                plotly_4.9.2.1                   
[105] grid_4.0.0                        digest_0.6.27                    
[107] xtable_1.8-4                      tidyr_1.1.2                      
[109] httpuv_1.5.4                      munsell_0.5.0                    
[111] viridisLite_0.3.0                
```

**Comment by ccruizm** [comment] 2021-01-04 13:31
in the meantime, I have been trying to plot only specific clusters in different plots but have not figured out how to do it. When returning a `SummarizedExperiment`, I can easily subset the clusters I want to plot (for instance, in the case of heatmaps); however, functions like `plotGroups` or `plotBrowserTrack`  that take the whole ArchR object, I have not been able to only plot the clusters I want to include in the figure. Is it necessary to subset the clusters (through `subsetArchRProject`) every time I want to accomplish this? or there is a way to only show the clusters I am interested in on the plot? Thanks in advance!

**Comment by gregszetoAI** [comment] 2021-02-01 04:27
Is there a fix to this for arrow files that are rendered inaccessible after subsetting? I just ran subset on a large number of arrowfiles and can no longer read any of them now.

**Comment by rcorces** [comment] 2021-02-01 15:28
As far as I know, we have not been able to recapitulate this error. If you can provide a reproducible example with code using the tutorial dataset that would be very helpful.

**Comment by rcorces** [comment] 2021-02-27 05:32
Closing due to inactivity. Feel free to comment again here and I will re-open if you still need help.

**Closed by rcorces** 2021-02-27 05:32 UTC
Labels: bug, help wanted

**Comment by sqs1020** [comment] 2022-03-11 19:50
I am trying to subset several clusters from the original archR project based on your answer under #363. I tried to figure out the cell names in my clusters using:
idxMP <- BiocGenerics::which(PARNAcluster$predictedGroup %in% c("Mesenchymal progenitors A", "Mesenchymal progenitors B", "Mesenchymal progenitors C", "Mesenchymal progenitors D"))
cellsMP <- PARNAcluster$predictedGroup[idxMP]
PARNAcluster[cellsMP, ]
And then I got the error:
Error in .Call2("map_positions", run_lens, pos, method, PACKAGE = "S4Vectors") : 
  subscript contains NAs

**Comment by rcorces** [comment] 2022-03-12 04:01
@sqs1020 - I cant tell what you are trying to do. If you are trying to subset your project, use the `subsetArchRProject()` function. 
https://www.archrproject.com/reference/subsetArchRProject.html
Also, I would avoid using spaces in your names like "Mesenchymal progenitors A"

**Comment by retidu** [comment] 2024-12-04 04:18
I first  run the command of this: projSubset <- subsetArchRProject(proj, sample(proj$cellNames, 100)). It works well.
while, I want to subset according to the cluster name, and write the command as below:

proj.inn <- subsetArchRProject(
  ArchRProj = proj,
  sample(proj$Clusters22,"C.inNeu")),   C.inNeu is one of the name of cluster. But it doesn't work. Could someone please provide some advice for this? Thanks.
