### ISSUE TITLE
Importing data using 10X count matrix

### ISSUE THREAD

**Issue by kvshams** [GreenleafLab/ArchR#558] opened 2021-03-01 19:07 UTC
Is it possible to have a workaround to import data using only the 10X feature matrix alone (`matrix.mtx.gz`, `features.txt.gz` & `barcodes.txt.gz`) as many public data in GEO is in this format.

**Comment by rcorces** [comment] 2021-03-01 19:53
Thanks for the suggestion. I see the utility but I dont think this is trivial to implement and I defer to @jgranja24. Almost all of the infrastructure of ArchR uses information stored in the Arrow files which would be mostly empty with this type of import. So even though it sounds trivial, this would require pretty major code revisions (and enable analytical workflows that are less ideal than starting from fragments). I think the solution is for people to start uploading fragment files but I'm not even sure GEO allows this?

A more generic proposal would be that you want the ability to use ArchR's functions on random matrices but I think this is quite complicated from an infrastructure perspective.

**Comment by kvshams** [comment] 2021-03-01 21:45
Agree... I think it would be relatively straight forward to fetch-out all information required form all these files right?. Ie can make the bed/region/peak file from the `features.txt.gz` and so on.

**Comment by rcorces** [comment] 2021-03-02 02:24
I'm not so sure. the fragment level information could not be captured this way which would break lots of downstream ArchR functionality.

**Comment by rcorces** [comment] 2021-03-02 15:22
Just realizing that this is a pretty close duplicate of #501 
I'm going to close this for now but feel free to comment here if you disagree or comment in #501 if you would like to add more to the discussion

**Closed by rcorces** 2021-03-02 15:22 UTC
Labels: enhancement

**Comment by kvshams** [comment] 2021-03-03 18:42
@rcorces is it possible to import with a fragment file. ie matrix.mtx.gz, features.txt.gz, barcodes.txt.gz & fragments.tsv.gz

**Comment by kvshams** [comment] 2021-03-03 19:33
One option is to create the [`h5`](https://rdrr.io/github/MarioniLab/DropletUtils/man/write10xCounts.html) file first and process it as usual.

**Comment by rcorces** [comment] 2021-03-03 20:04
I'm not following your questions (ArchR's default input is fragments.tsv.gz) but please continue the discussion on the open issue #501
