### ISSUE TITLE
Error in model$nn_index$save(nn_tmpfname) : attempt to apply non-function

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#428] opened 2020-11-20 02:59 UTC
addUMAP function gives this error.

Recent Issue. Was not a problem in the past.

**Comment by rcorces** [comment] 2020-11-20 04:25
duplicate of #424

**Closed by rcorces** 2020-11-20 04:25 UTC
Labels: bug

**Comment by sylestiel** [comment] 2020-11-20 16:08
I read through issue #424 but do not understand what exactly I'm required to do to bypass the error. Kindly break it down for me.
