### ISSUE TITLE
Error in addArchRAnnotations

### ISSUE THREAD

**Issue by jindalk** [GreenleafLab/ArchR#491] opened 2021-01-13 17:44 UTC
Hi, I ran the following code to add EncodeTFBS data to my object: 

`proj_lsk4 <- addArchRAnnotations(ArchRProj = proj_lsk4, collection = "EncodeTFBS")
`

and got this error: 

`Error in as.character.default(x) : no method for coercing this S4 class to a vector`

Upon further investigation, the issue to me seems to be in addArchRAnnotations function, specifically the following section of code:

`genome <- tolower(tryCatch({
    validBSgenome(getGenome(ArchRProj))
  }, error = function(e) {
    strsplit(validBSgenome(getGenome(ArchRProj)), "\\.")[[1]][4]
  }))`

The function validBSgenome returns a BS genome object and not a string.

![image](https://user-images.githubusercontent.com/46723936/104488941-ac598200-5594-11eb-924b-b931c52095ea.png)

Perhaps the line of code should be the following:

`validBSgenome(getGenome(ArchRProj))@metadata$genome`

Either that or I am doing something very wrong here. Could you please check this?

Thank you

**Comment by rcorces** [comment] 2021-01-14 04:42
Thanks for pointing this out. I haven't reproduced this myself but it looks like you are right. This is related to a recent change referenced in #416 
I think your assessment is correct but because of changes to BSgenome I'm not sure the solution is correct.

This is the functionality that we want:
```
genomeName <- tryCatch({
      bsg@provider_version
    }, error = function(e){
      strsplit(bsg@pkgname,"\\.")[[1]][4]
    })
```
From this line - https://github.com/GreenleafLab/ArchR/blob/3321710bd5eea119596a7d8c6daf943de4538b0b/R/AnnotationGenome.R#L45

So I think we need to change this line:
https://github.com/GreenleafLab/ArchR/blob/3321710bd5eea119596a7d8c6daf943de4538b0b/R/AnnotationPeaks.R#L619
to:
```
genome <- tolower(tryCatch({
    validBSgenome(getGenome(ArchRProj))$provider_version
  }, error = function(e){
    strsplit(validBSgenome(getGenome(ArchRProj))@pkgname,"\\.")[[1]][4]
  }))
```

To keep things tidy, I'm going to close this issue and cross post over there. You can follow up on the other issue thread.

**Closed by rcorces** 2021-01-14 04:42 UTC
Labels: bug
