### ISSUE TITLE
easiest way to load group coverages into public browser?

### ISSUE THREAD

**Issue by juliabelk** [GreenleafLab/ArchR#54] opened 2020-02-25 17:15 UTC
I usually use the washu browser which doesn't have an option for h5 files. Also, the output folders have replicates - ideally I would like to merge these and be able to load whatever tracks are shown in the ArchR browser (which look great btw) into a public browser.

Thanks!

**Comment by juliabelk** [comment] 2020-05-13 17:31
Any update on this @jgranja24 ? Thanks again!

**Comment by jgranja24** [comment] 2020-05-13 17:58
Yeah, sorry its on my current list. Will update soon hopefully. Just ran into a few complicated challenges when writing this.

**Comment by kikegoni** [comment] 2020-05-15 05:17
Hey,

Congrats and thanks so much for implementing and sharing ArchR. 

I am also interested in a way to extract the bigwigs from the ArrowFiles, is that possible?

I am asking since in your publication in biorxic is says that "ArchR also enables direct export of group normalized bigwig files using “export.bw” from Rtracklayer that can be directly used in conventional genome browsers." and I have not figure out yet how this could be done since 
```r
export.bw
```
expects a GRanges object as input.

Thanks in advance for any help with this.

Kike

**Comment by rcorces** [comment] 2020-05-19 15:36
This is still in progress. We had an iteration of this but removed it because it wasnt stable (hence the excerpt from the paper).

**Comment by kikegoni** [comment] 2020-05-21 02:08
Hey @rcorces ! Thanks for your answer. It agree with the previous comments, it would be an awesome improvement.

**Comment by jgranja24** [comment] 2020-05-21 23:18
This is now added in the dev branch with `getGroupBW`. It still needs a little more testing on my end before ill commit it to master.

**Comment by kikegoni** [comment] 2020-05-22 04:44
Hey @jgranja24 @rcorces 

I can confirm it is working in the dev branch. Thanks for adding it.

Kike

**Comment by rcorces** [comment] 2020-05-30 01:54
Closing this. Related error with logfile came up and is fixed in the dev branch #180

**Closed by rcorces** 2020-05-30 01:54 UTC
Labels: enhancement
