### ISSUE TITLE
error in multiomic analysis

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#433] opened 2020-11-21 15:28 UTC
I am following https://greenleaflab.github.io/ArchR_2020/Ex-Analyze-Multiome.html, and at this step:

```
#Combined Dims
proj <- addCombinedDims(proj, reducedDims = c("LSI_ATAC", "LSI_RNA"), name =  "LSI_Combined")
#UMAPs
proj <- addUMAP(proj, reducedDims = "LSI_ATAC", name = "UMAP_ATAC", minDist = 0.8, force = TRUE)
```
 I get this error:

```


22:56:28 UMAP embedding parameters a = 0.2321 b = 1.681

22:56:28 Read 10887 rows and found 30 numeric columns

22:56:28 Using Annoy for neighbor search, n_neighbors = 40

22:56:28 Building Annoy index with metric = cosine, n_trees = 50

0%   10   20   30   40   50   60   70   80   90   100%

[----|----|----|----|----|----|----|----|----|----|

*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
|

22:56:29 Writing NN index file to temp file /tmp/RtmpgVC73s/file6ca2f65f48bea

22:56:29 Searching Annoy index using 28 threads, search_k = 4000

22:56:29 Annoy recall = 100%

22:56:30 Commencing smooth kNN distance calibration using 28 threads

22:56:31 Initializing from normalized Laplacian + noise

22:56:32 Commencing optimization for 200 epochs, with 627734 positive edges

22:56:47 Optimization finished

Error in model$nn_index$save(nn_tmpfname): attempt to apply non-function
Traceback:

1. addUMAP(proj, reducedDims = "LSI_ATAC", name = "UMAP_ATAC", minDist = 0.8, 
 .     force = TRUE)
2. .saveUWOT(uwot_umap, modelFile)
```

I attached the log file as well
[ArchR-addIterativeLSI-6ca2f4d4f6892-Date-2020-11-20_Time-22-50-42.log](https://github.com/GreenleafLab/ArchR/files/5577871/ArchR-addIterativeLSI-6ca2f4d4f6892-Date-2020-11-20_Time-22-50-42.log)

**Comment by rcorces** [comment] 2020-11-21 18:20
duplicate of #424

**Closed by rcorces** 2020-11-21 18:20 UTC
Labels: bug
