### ISSUE TITLE
Confusion encountered in 16.1.3 Integrative pseudo-time Analyses  

### ISSUE THREAD

**Issue by 1221li** [GreenleafLab/ArchR#976] opened 2021-08-13 03:15 UTC
Hello, author. Sorry to trouble you again.In 16.1.3 Integrative pseudo-time Analyses, I want to do an individualized analysis, but I don't know how to do it .
![1628824157(1)](https://user-images.githubusercontent.com/76415266/129299548-3c7ba74c-df69-4ed0-a888-1edd974bcf14.png)
"Plotting these two heatmaps side-by-side, we see that the rows are matched across the two heatmaps. You may notice that the analysis captures both GATA3 and GATA3-AS1 (an anti-sense transcript of GATA3). This is due to how feature matching is performed and the anti-sense transcript entry could be removed manually in post-processing or programatically if desired."This is what you described in the original
ANnd now,I found some Markergenes and tried to replace those genes automatically identified by the system, and I arranged these Markergenes in a similar way, and made the heat map show specific changes  .
I look forward to hearing from you.With best wishes.

**Comment by rcorces** [comment] 2021-08-13 15:21
Sorry, I do not understand your question.
Please note that this is not a bug or error report and should not have been posted in the Issues section. I am closing this issue. You can re-post your question in Discussions but please try to clarify since I do not understand what you are asking.

**Closed by rcorces** 2021-08-13 15:21 UTC
