### ISSUE TITLE
getMarkerFeatures() not working

### ISSUE THREAD

**Issue by dannyconrad** [GreenleafLab/ArchR#562] opened 2021-03-02 17:47 UTC
I've tried this on two different MBPs (macOS 10.14 and 10.11), with two different R versions (4.0.4 and 3.6.3), both with fresh installs of ArchR v1.0.1. I can't use v1.0.0 for my pipeline because addUMAP fails (same as Issue #424). The same error occurs no matter what matrix I use for differential analysis. Changing the groupBy parameter (instead of the default "Clusters") reproduces the errors described in Issue #483, presumably because I'm also using a subsetted project, so maybe this is related?

**Attach your log file**
When groupBy = "Clusters":
[ArchR-getMarkerFeatures-60a75e9af00-Date-2021-03-02_Time-09-07-34.log](https://github.com/GreenleafLab/ArchR/files/6070470/ArchR-getMarkerFeatures-60a75e9af00-Date-2021-03-02_Time-09-07-34.log)

When groupBy = other celltype/sample metadata I've added manually:
[ArchR-getMarkerFeatures-60a11484843-Date-2021-03-02_Time-09-23-52.log](https://github.com/GreenleafLab/ArchR/files/6070610/ArchR-getMarkerFeatures-60a11484843-Date-2021-03-02_Time-09-23-52.log)

**Describe the bug**
When groupBy = "Clusters":

> ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-60a75e9af00-Date-2021-03-02_Time-09-07-34.log
If there is an issue, please report to github with logFile!
MatrixClass = Sparse.Integer.Matrix
2021-03-02 09:07:34 : Matching Known Biases, 0.005 mins elapsed.
Found less than 100 cells for background matching, Lowering k to 0
2021-03-02 09:07:36 : 
Error in nabor::knn(data = data, query = query, k = k, ...) : 
  Cloud has no points

When groupBy = other celltype/sample metadata I've added manually:

> ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-60a11484843-Date-2021-03-02_Time-09-23-52.log
If there is an issue, please report to github with logFile!
2021-03-02 09:23:52 : Matching Known Biases, 0.002 mins elapsed.
Error in .safelapply(seq_along(matchObj[[1]]), function(x) { : 
Error Found Iteration 1 : 
	[1] "Error in pairwiseDF$fdr[idxFilter] <- p.adjust(pairwiseDF$pval[idxFilter],  : \n  NAs are not allowed in subscripted assignments\n"
	<simpleError in pairwiseDF$fdr[idxFilter] <- p.adjust(pairwiseDF$pval[idxFilter],     method = "fdr"): NAs are not allowed in subscripted assignments>
Error Found Iteration 2 : 
	[1] "Error in pairwiseDF$fdr[idxFilter] <- p.adjust(pairwiseDF$pval[idxFilter],  : \n  NAs are not allowed in subscripted assignments\n"
	<simpleError in pairwiseDF$fdr[idxFilter] <- p.adjust(pairwiseDF$pval[idxFilter],     method = "fdr"): NAs are not allowed in subscripted assignments>
Error Found Iteration 3 : 
	[1] "Error in pairwiseDF$fdr[idxFilter] <- p.adjust(pairwiseDF$pval[idxFilter],  : \n  NAs are not allowed in subscripted assignments\n"
	<simpleError in pairwiseDF$fdr[idxFilter] <- p.adjust(pairwiseDF$pval[idxFilter],     method = "fdr"): NAs are not allowed in subscripted assignments>
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  3 function calls resulted in an error

**Comment by dannyconrad** [comment] 2021-03-02 17:58
Uh okay I figured out what the difference with "Clusters" is, for some reason there are NAs introduced by the addClusters() function:

![image](https://user-images.githubusercontent.com/22381421/109692295-335ebb80-7b3d-11eb-8fdb-9cea39b5386b.png)

**Comment by rcorces** [comment] 2021-03-02 18:21
I dont have an immediate solution for this. I dont believe that addClusters() should produce NAs. Any idea what those cells are / does this happen regardless of what clustering parameters you use?

**Comment by dannyconrad** [comment] 2021-03-02 19:00
Okay, looks like the NAs may be a byproduct of addIterativeLSI? The 19 NAs in question are SUPER low-quality cells (this dataset is not QC filtered):

![image](https://user-images.githubusercontent.com/22381421/109699222-247c0700-7b45-11eb-9632-9fbb226c2f4c.png)

"proj_5" has 8638 cells in it, but when I inspect the iLSI and UMAP data, the dimensions show only 8619 cells (which would explain where the 19 NAs are coming from):

> dim(proj_5@reducedDims$IterativeLSI$matSVD)
> [1] 8619   30
> 
> dim(proj_5@embeddings$UMAP$df)
> [1] 8619    2

This would also explain why I was previously having lots of issues subsetting my projects, kept getting "subscript out of bounds" errors that I couldn't make sense of, presumably because of this mismatch in cell numbers due to these weird cell dropouts.

Let me know if I can provide any more information, seems like kind of a fringe issue I've come across.

**Comment by rcorces** [comment] 2021-03-02 19:28
Interesting. Thanks for digging into this. Yes definitely fringe - I'm not sure either Jeff or I have ever run a full dataset without QC filtering - but still important to address. I will try to recapitulate this with the tutorial data.

**Comment by dannyconrad** [comment] 2021-03-02 21:22
Yeah, the dataset in question is more about method/tech than biology so I've kept low quality cells in order to compare between libraries.

I don't want to jinx anything but after I removed those NA cells and re-did the peak calling steps (addGroupCoverages, addReproduciblePeakSet, addPeakMatrix), getMarkerFeatures() works again, even for the GeneScoreMatrix and other groupBy options... so this might be the answer to #483 as well.

**Comment by rcorces** [comment] 2021-04-30 04:40
I think this has been solved with the resolution of #483 so I'm closing. Feel free to comment here if additional help is needed.

**Closed by rcorces** 2021-04-30 04:40 UTC
Labels: bug, help wanted

**Comment by zrhhl** [comment] 2021-06-21 00:18
Hi,  I have met a  error when running:
`geneSet1 <- getMarkerFeatures( ArchRProj = subName, useMatrix = "MotifMatrix", groupBy = "groupInfo", useGroups = "case", bgdGroups = "control", bias = c("TSSEnrichment", "log10(nFrags)"), testMethod = "wilcoxon", useSeqnames = "z" )`

with the error:
`Error in if (all(mColSums == 1) & is.null(normBy)) { : missing value where TRUE/FALSE needed`

And I have update the ArchR to release_1.0.2, althongh the packages "RSQLite" can not update to RSQLite_2.2.7 with the error
`make: *** ~/lib/R/etc/Makeconf:181: SqliteColumnDataSource.o] Error 1 ERROR: compilation failed for package 'RSQLite'`
so the package RSQLite still version 2.2.5

Befor 'getFeatures', I have done subsetArchRProject with dropCells = FALSE, when I set dropCells = FALSE, I got the same error as #212

Besides, I am not sure how to fix mColSums mentioned preveriously.
https://github.com/GreenleafLab/ArchR/issues/483#issuecomment-762977214

And I tried to use different version of r-base, it still did not work.

here is `sessionInfo:`
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS/LAPACK: ~/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_US.utf-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.utf-8        LC_COLLATE=en_US.utf-8
 [5] LC_MONETARY=en_US.utf-8    LC_MESSAGES=en_US.utf-8
 [7] LC_PAPER=en_US.utf-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.utf-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] TFBSTools_1.24.0            nabor_0.5.0
 [3] ArchR_1.0.2                 magrittr_2.0.1
 [5] rhdf5_2.30.1                Matrix_1.3-0
 [7] data.table_1.14.0           SummarizedExperiment_1.16.1
 [9] DelayedArray_0.12.3         BiocParallel_1.20.1
[11] matrixStats_0.59.0          Biobase_2.46.0
[13] GenomicRanges_1.38.0        GenomeInfoDb_1.22.1
[15] IRanges_2.20.2              S4Vectors_0.24.4
[17] BiocGenerics_0.32.0         ggplot2_3.3.4

loaded via a namespace (and not attached):
 [1] httr_1.4.2                         bit64_4.0.5
 [3] R.utils_2.10.1                     gtools_3.9.2
 [5] assertthat_0.2.1                   blob_1.2.1
 [7] BSgenome_1.54.0                    GenomeInfoDbData_1.2.2
 [9] Rsamtools_2.2.3                    DirichletMultinomial_1.28.0
[11] pillar_1.6.1                       RSQLite_2.2.1
[13] lattice_0.20-41                    glue_1.4.2
[15] XVector_0.26.0                     colorspace_2.0-1
[17] R.oo_1.24.0                        plyr_1.8.6
[19] XML_3.99-0.3                       pkgconfig_2.0.3
[21] zlibbioc_1.32.0                    GO.db_3.10.0
[23] purrr_0.3.4                        xtable_1.8-4
[25] scales_1.1.1                       pracma_2.3.3
[27] tibble_3.1.2                       annotate_1.64.0
[29] KEGGREST_1.26.1                    generics_0.1.0
[31] ellipsis_0.3.2                     cachem_1.0.5
[33] withr_2.4.2                        TFMPvalue_0.0.8
[35] crayon_1.4.1                       memoise_2.0.0
[37] poweRlaw_0.70.6                    R.methodsS3_1.8.1
[39] fansi_0.5.0                        CNEr_1.22.0
[41] Cairo_1.5-10                       tools_3.6.3
[43] hms_1.1.0                          lifecycle_1.0.0
[45] stringr_1.4.0                      Rhdf5lib_1.8.0
[47] munsell_0.5.0                      AnnotationDbi_1.48.0
[49] Biostrings_2.54.0                  compiler_3.6.3
[51] caTools_1.18.2                     rlang_0.4.11
[53] grid_3.6.3                         RCurl_1.98-1.3
[55] bitops_1.0-7                       gtable_0.3.0
[57] codetools_0.2-18                   DBI_1.1.1
[59] reshape2_1.4.4                     R6_2.5.0
[61] GenomicAlignments_1.22.1           dplyr_1.0.7
[63] seqLogo_1.52.0                     rtracklayer_1.46.0
[65] fastmap_1.1.0                      bit_4.0.4
[67] utf8_1.2.1                         readr_1.4.0
[69] stringi_1.6.2                      BSgenome.Mmusculus.UCSC.mm10_1.4.0
[71] Rcpp_1.0.6                         png_0.1-7
[73] vctrs_0.3.8                        tidyselect_1.1.1
```

Please give me any advice. Thanks a lot!

**Comment by rcorces** [comment] 2021-06-21 15:15
@zrhhl - your error related to `mColSums` should have been corrected by upgrading to 1.0.2. I am not sure why you seem to still be having the problem.

**Comment by zrhhl** [comment] 2021-06-22 00:41
@rcorces Yes, I have updated to 1.0.2 except for the RSQLite package. Maybe it is the key factor?  I will try a different R version again. Thanks!

**Comment by zrhhl** [comment] 2021-06-25 00:40
Hi, I have also tried to install ArchR on windows, change different versions of R, undate RSQLite to 2.2.7, they all didn't work. While I can export MotifMatrix with z-score, can I find different motifs on the matrix directly? Actually, I am not sure how to deal next...

**Comment by andyyhchen** [comment] 2021-07-02 20:58
I think the mColSums issue wasn't fix well here. The newest version of ArchR (1.0.2). The fix in the tread #483 is 
```
mColSums <- tryCatch({
        suppressMessages(.getColSums(ArrowFiles, seqnames = featureDF$seqnames@values,
            useMatrix = useMatrix, threads = threads))
    }, error = function(x) {
        rep(1, nCells(ArchRProj))
    })
mColSums <- mColSums[ArchRProj$cellNames]
if (all(mColSums == 1) & is.null(normBy)) {
        normBy <- "none"
}
```

The problem is that when there is no colsum in the ArrowFile, mColSums will be rep(1, nCells(ArchRProj)) vector with no name with it. In that case mColSums <- mColSums[ArchRProj$cellNames] will return bunches of NA, which causes all(mColSums == 1) also returns NA and incurs error
`Error in if (all(mColSums == 1) & is.null(normBy)) { : missing value where TRUE/FALSE needed`

the fix probably will be 

```
mColSums <- tryCatch({
        suppressMessages(tmp <- .getColSums(ArrowFiles, seqnames = featureDF$seqnames@values,
            useMatrix = useMatrix, threads = threads))
        tmp[ArchRProj$cellNames]
    }, error = function(x) {
        rep(1, nCells(ArchRProj))
    })
if (all(mColSums == 1) & is.null(normBy)) {
    normBy <- "none"
}
```

**Comment by andyyhchen** [comment] 2021-07-02 22:49
@zrhhl the quick fix for you is to have your own .MarkersSC function and override the one in ArchR. 

```
.MarkersSC_fixed <- function(
  ArchRProj = NULL,
  groupBy = "Clusters",
  useGroups = NULL,
  bgdGroups = NULL,
  normBy = NULL,
  maxCells = 500,
  scaleTo = 10^4,
  bufferRatio = 0.8,
  bias = NULL,
  k = 100,
  threads = 1,
  binarize = FALSE,
  useSeqnames = NULL,
  testMethod = "wilcoxon",
  useMatrix = "GeneScoreMatrix",
  markerParams = list(),
  verbose = TRUE,
  logFile = NULL
){
  
  tstart <- Sys.time()
  
  #####################################################
  # Feature Info
  #####################################################
  ArrowFiles <- getArrowFiles(ArchRProj)
  featureDF <- .getFeatureDF(head(ArrowFiles, 2), useMatrix)
  matrixClass <- as.character(h5read(getArrowFiles(ArchRProj)[1], paste0(useMatrix, "/Info/Class")))
  
  .logThis(range(as.vector(table(paste0(featureDF$seqnames)))), "FeaturesPerSeqnames", logFile = logFile)
  
  isDeviations <- FALSE
  if(all(unique(paste0(featureDF$seqnames)) %in% c("z", "dev"))){
    isDeviations <- TRUE
  }
  
  .logThis(featureDF, "FeatureDF", logFile=logFile)
  .logMessage(paste0("MatrixClass = ", matrixClass), logFile=logFile)
  
  seqnames <- unique(as.vector(featureDF$seqnames))
  useSeqnames <- useSeqnames[useSeqnames %in% seqnames]
  if(length(useSeqnames)==0){
    useSeqnames <- NULL
  }
  
  if(!is.null(useSeqnames)){
    if(matrixClass == "Sparse.Assays.Matrix"){
      if(length(useSeqnames) == 1){
        featureDF <- featureDF[BiocGenerics::which(featureDF$seqnames %bcin% useSeqnames),]
      }else{
        .logMessage("When accessing features from a matrix of class Sparse.Assays.Matrix it requires 1 seqname!\n",
                    "Continuing with first seqname '", seqnames[1], "'!\n",
                    "If confused, try getSeqnames(ArchRProj, '", useMatrix,"'') to list out available seqnames for input!", verbose = verbose, logFile = logFile)
        useSeqnames <- seqnames[1]
        featureDF <- featureDF[BiocGenerics::which(featureDF$seqnames %bcin% useSeqnames),]
      }
    }else{
      featureDF <- featureDF[BiocGenerics::which(featureDF$seqnames %bcin% useSeqnames),]
    }
  }else{
    if(matrixClass == "Sparse.Assays.Matrix"){
      .logMessage("When accessing features from a matrix of class Sparse.Assays.Matrix it requires 1 seqname!\n",
                  "Continuing with first seqname '", seqnames[1], "'!\n",
                  "If confused, try getSeqnames(ArchRProj, '", useMatrix,"'') to list out available seqnames for input!", verbose = verbose, logFile = logFile)
      useSeqnames <- seqnames[1]
      featureDF <- featureDF[BiocGenerics::which(featureDF$seqnames %bcin% useSeqnames),]
    }
  }
  if(!(nrow(featureDF) > 1)){
    .logStop("Less than 1 feature is remaining in featureDF please check input!", logFile = logFile)
  }
  
  #####################################################
  # Match Bias Groups
  #####################################################
  .logDiffTime("Matching Known Biases", t1 = tstart, addHeader = FALSE, verbose = verbose, logFile = logFile)
  groups <- getCellColData(ArchRProj, groupBy, drop = TRUE)
  colDat <- getCellColData(ArchRProj)
  
  matchObj <- .matchBiasCellGroups(
    input = colDat, 
    groups = groups,
    useGroups = useGroups,
    bgdGroups = bgdGroups,
    bias = bias,
    k = k,
    n = maxCells,
    bufferRatio = bufferRatio,
    logFile = logFile
  )
  
  #####################################################
  # Pairwise Test Per Seqnames
  #####################################################
  mColSums <- tryCatch({
    suppressMessages(tmpColSum <- .getColSums(ArrowFiles, seqnames = featureDF$seqnames@values, useMatrix = useMatrix, threads = threads))
    tmpColSum[ArchRProj$cellNames]
    }, error = function(x){
    rep(1, nCells(ArchRProj))
  })
  if(all(mColSums==1) & is.null(normBy)){
    normBy <- "none"
  }
  
  if(is.null(normBy)){
    if(tolower(testMethod) == "binomial"){
      normFactors <- NULL
    }else{
      if(tolower(useMatrix) %in% c("tilematrix", "peakmatrix")){
        normBy <- "ReadsInTSS"
        normFactors <- getCellColData(ArchRProj, normBy, drop=FALSE)
        normFactors[,1] <- median(normFactors[,1]) / normFactors[,1]
      }else{
        normFactors <- scaleTo / mColSums
        normFactors <- DataFrame(normFactors)
      }
    }
  }else{
    if(tolower(normBy) == "none"){
      normFactors <- NULL
    }else{
      normFactors <- scaleTo / mColSums
      normFactors <- DataFrame(normFactors)
    }
  }
  
  if(!is.null(normFactors)){
    normFactors[,1] <- normFactors[,1] * (scaleTo / median(normFactors[names(mColSums), 1] * mColSums))
  }
  
  diffList <- .safelapply(seq_along(matchObj[[1]]), function(x){
    .logDiffTime(sprintf("Computing Pairwise Tests (%s of %s)", x, length(matchObj[[1]])), tstart, addHeader = FALSE, verbose = verbose, logFile = logFile)
    .testMarkerSC(
      ArrowFiles = ArrowFiles,
      matchObj = matchObj, 
      group = names(matchObj[[1]])[x], 
      testMethod = testMethod, 
      threads = 1, 
      useMatrix = useMatrix,
      featureDF = featureDF,
      normFactors = normFactors,
      binarize = binarize,
      logFile = logFile
    )
  }, threads = threads)
  
  .logDiffTime("Completed Pairwise Tests", tstart, addHeader = TRUE, verbose = verbose, logFile = logFile)
  
  #####################################################
  # Summarize Output
  #####################################################
  if(tolower(testMethod) == "wilcoxon"){
    pse <- SummarizedExperiment::SummarizedExperiment(
      assays = 
        SimpleList(
          Log2FC = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$log2FC)) %>% Reduce("cbind",.),
          Mean = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$mean1)) %>% Reduce("cbind",.),
          FDR = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$fdr)) %>% Reduce("cbind",.),
          Pval = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$pval)) %>% Reduce("cbind",.),
          MeanDiff = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$mean1 - diffList[[x]]$mean2)) %>% Reduce("cbind",.),
          AUC = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$auc)) %>% Reduce("cbind",.),
          MeanBGD = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$mean2)) %>% Reduce("cbind",.)
        ),
      rowData = featureDF
    )
  }else if(tolower(testMethod) == "ttest"){
    pse <- SummarizedExperiment::SummarizedExperiment(
      assays = 
        SimpleList(
          Log2FC = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$log2FC)) %>% Reduce("cbind",.),
          Mean = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$mean1)) %>% Reduce("cbind",.),
          Variance = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$var1)) %>% Reduce("cbind",.),
          FDR = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$fdr)) %>% Reduce("cbind",.),
          Pval = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$pval)) %>% Reduce("cbind",.),
          MeanDiff = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$mean1 - diffList[[x]]$mean2)) %>% Reduce("cbind",.),
          MeanBGD = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$mean2)) %>% Reduce("cbind",.),
          VarianceBGD = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$var2)) %>% Reduce("cbind",.)
        ),
      rowData = featureDF
    )
  }else if(tolower(testMethod) == "binomial"){
    pse <- SummarizedExperiment::SummarizedExperiment(
      assays = 
        SimpleList(
          Log2FC = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$log2FC)) %>% Reduce("cbind",.),
          Mean = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$mean1)) %>% Reduce("cbind",.),
          FDR = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$fdr)) %>% Reduce("cbind",.),
          Pval = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$pval)) %>% Reduce("cbind",.),
          MeanDiff = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$mean1 - diffList[[x]]$mean2)) %>% Reduce("cbind",.),
          MeanBGD = lapply(seq_along(diffList), function(x) data.frame(x = diffList[[x]]$mean2)) %>% Reduce("cbind",.)
        ),
      rowData = featureDF
    )
  }else{
    stop("Error Unrecognized Method!")
  }
  colnames(pse) <- names(matchObj[[1]])
  
  metadata(pse)$MatchInfo <- matchObj
  
  if(isDeviations){
    assays(pse)[["Log2FC"]] <- NULL #This measure does not make sense with deviations matrices better to just remove
  }
  
  
  return(pse)
  
}

```
Overriding the original function with: 

```
environment(.MarkersS_fixed) <- asNamespace('ArchR')
assignInNamespace(".MarkersSC", .MarkersS_fixed, ns='ArchR')
```

**Comment by zrhhl** [comment] 2021-07-03 10:31
@andyyhchen 
Hi, Andy. I have tried your solution and it worked smoothly! Thank you so much!!

**Comment by rcorces** [comment] 2021-07-03 12:46
Thanks @andyyhchen for figuring this out and @zrhhl for confirming. I've implemented the solution in the `release_1.0.2` branch via https://github.com/GreenleafLab/ArchR/commit/f98354ce07f72c86213982e5fbcd9a5bd70d743b

**Comment by A-legac45** [comment] 2024-06-18 15:07
Hello, 

I am going through this error message does somebody know how to manage

`> marker_by_subcluster <- getMarkerFeatures(
+   ArchRProj = MAIT_zoom, 
+   useMatrix = "GeneScoreMatrix",
+   groupBy = "Clusters.res_RNA0.9",
+   testMethod = "wilcoxon",
+   bias = c("TSSEnrichment", "log10(nFrags)")
+ )
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-dac02f38eac1-Date-2024-06-18_Time-17-06-11.958484.log
If there is an issue, please report to github with logFile!
MatrixClass = Sparse.Double.Matrix
2024-06-18 17:06:12.15638 : Matching Known Biases, 0.001 mins elapsed.
Found less than 100 cells for background matching, Lowering k to 72
2024-06-18 17:06:12.218513 : 
Found less than 100 cells for background matching, Lowering k to 74
2024-06-18 17:06:12.260676 : 
Found less than 100 cells for background matching, Lowering k to 90
2024-06-18 17:06:12.315435 : 
Found less than 100 cells for background matching, Lowering k to 57
2024-06-18 17:06:12.350245 : 
Found less than 100 cells for background matching, Lowering k to 0
2024-06-18 17:06:12.380623 : 
Error: Cloud has no points



> MAIT_zoom$Clusters.res_RNA0.9
 [1] "C3"  "C6"  "C6"  "C3"  "C3"  "C6"  "C3"  "C6"  "C6"  "C6"  "C6"  "C3"  "C6"  "C6"  "C6" 
[16] "C4"  "C6"  "C6"  "C6"  "C6"  "C6"  "C6"  "C6"  "C6"  "C6"  "C6"  "C6"  "C3"  "C4"  "C3" 
[31] "C6"  "C3"  "C6"  "C6"  "C3"  "C3"  "C6"  "C6"  "C3"  "C3"  "C4"  "C6"  "C6"  "C3"  "C3" 
[46] "C3"  "C3"  "C14" "C15" "C4"  "C4"  "C6"  "C3"  "C6"  "C6"  "C6"  "C3"  "C4"  "C5"  "C6" 
[61] "C3"  "C3"  "C6"  "C5"  "C6"  "C5"  "C4"  "C3"  "C4"  "C4"  "C4"  "C4"  "C15" "C4"  "C4" 
[76] "C3"  "C7"  "C5"  "C5"  "C6"  "C4"  "C4"  "C4"  "C4"  "C3"  "C4"  "C5"  "C4"  "C6"  "C15"
[91] "C4"  "C6"  "C3"  "C4"  "C6"  "C4" `
