### ISSUE TITLE
Error in subsetArchRProject

### ISSUE THREAD

**Issue by xz333** [GreenleafLab/ArchR#512] opened 2021-01-25 09:20 UTC
Hi!  I found a new error
**Describe the bug**
When I ran the subsetArchRProject step in some subclusters, an error occurred
These are my codes:
```
library(ArchR)
args = commandArgs(T)
sub <- args[1]
proj <- loadArchRProject(paste0("/hwfssz1/ST_PRECISION_COVID/brain/ATAC/",sub))

#remove arrow files with one cell

data <- as.data.frame(proj@cellColData)
df <- as.data.frame(table(data$Sample))
df1 <- df[df$Freq ==1,]
ca <- as.character(df1[,1])
c <- rownames(data[data$Sample %in% ca,])

#save ArchR proj to new outdir

proj = subsetArchRProject(proj, cells = proj$cellNames[proj$cellNames %ni% c], outputDirectory = paste0("/hwfssz1/ST_PRECISION_COVID/brain/ATAC/",sub,"remove_single"),force =TRUE)

```
But if I run it in reverse, there is no problem, for example

```
proj = subsetArchRProject(proj, cells = proj$cellNames[proj$cellNames %in% c], outputDirectory = paste0("/hwfssz1/ST_PRECISION_COVID/brain/ATAC/",sub,"remove_single"),force =TRUE)
```
And some other subclusters run successfully with same codes

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/77724576/105684126-825a7500-5f2f-11eb-99f0-c8360fa1e497.png)

**Session Info**
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /hwfssz5/ST_PRECISION/OCG/yuqichao/CDCPtools/softwares/miniconda3/lib/R/lib/libRblas.so

locale:
[1] en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] ArchR_1.0.0                 magrittr_2.0.1             
 [3] rhdf5_2.30.1                Matrix_1.2-18              
 [5] data.table_1.13.4           SummarizedExperiment_1.16.1
 [7] DelayedArray_0.12.3         BiocParallel_1.20.1        
 [9] matrixStats_0.57.0          Biobase_2.46.0             
[11] GenomicRanges_1.38.0        GenomeInfoDb_1.22.1        
[13] IRanges_2.20.2              S4Vectors_0.24.4           
[15] BiocGenerics_0.32.0         ggplot2_3.3.2              

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5             pillar_1.4.7           compiler_3.6.1        
 [4] XVector_0.26.0         bitops_1.0-6           tools_3.6.1           
 [7] zlibbioc_1.32.0        lifecycle_0.2.0        tibble_3.0.4          
[10] gtable_0.3.0           lattice_0.20-41        pkgconfig_2.0.3       
[13] rlang_0.4.9            GenomeInfoDbData_1.2.2 withr_2.3.0           
[16] dplyr_1.0.2            generics_0.1.0         vctrs_0.3.6           
[19] grid_3.6.1             tidyselect_1.1.0       glue_1.4.2            
[22] R6_2.5.0               Rhdf5lib_1.8.0         purrr_0.3.4           
[25] scales_1.1.1           ellipsis_0.3.1         colorspace_2.0-0      
[28] RCurl_1.98-1.2         munsell_0.5.0          crayon_1.3.4          
[31] Cairo_1.5-10          

**Additional context**

**Comment by rcorces** [comment] 2021-01-25 15:27
I'm a little confused. Can you show the output of these things:

1) `proj$cellNames %ni% c`
2) `proj$cellNames[proj$cellNames %ni% c]`
3) `proj$cellNames %in% c`
4) `proj$cellNames[proj$cellNames %in% c]`

**Comment by xz333** [comment] 2021-01-26 01:10
sure
c is a string composed of the names of these individual cells stored in a single arrow file
![image](https://user-images.githubusercontent.com/77724576/105785341-9c3e9b00-5fb5-11eb-8901-4af86221bc8e.png)

1. `proj$cellNames %ni% c`   
![image](https://user-images.githubusercontent.com/77724576/105785508-06efd680-5fb6-11eb-9330-14532cc905bc.png)

2 `proj$cellNames[proj$cellNames %ni% c]`
![image](https://user-images.githubusercontent.com/77724576/105785544-20911e00-5fb6-11eb-8812-723e7a3b2ed1.png)

3`proj$cellNames %in% c`
![image](https://user-images.githubusercontent.com/77724576/105785580-2e46a380-5fb6-11eb-9e8b-0174e7017d9b.png)

4`proj$cellNames[proj$cellNames %in% c]`
![image](https://user-images.githubusercontent.com/77724576/105785602-41597380-5fb6-11eb-99a6-f58bf99d3609.png)

Thanks!

**Comment by rcorces** [comment] 2021-01-26 02:38
Sorry - I dont have a solution for this. I'm not able to reproduce your error so I imagine that this is either an edge case or a problem with your input and not a problem with ArchR *per se*. It is very difficult to provide additional help without a reproducible example.

**Comment by xz333** [comment] 2021-01-26 02:48
Thank you anyway!
I found that the core problem is that an arrow file has an error. When extracting the cells in the arrow, an error will be reported. It may be an error in saving the arrow file.

**Comment by rcorces** [comment] 2021-01-26 04:32
> I found that the core problem is that an arrow file has an error. When extracting the cells in the arrow, an error will be reported. It may be an error in saving the arrow file.

That makes sense to me. I'm going to close this for now but feel free to comment again here if this happens again in the future and I will reopen as necessary.

**Closed by rcorces** 2021-01-26 04:32 UTC
Labels: bug
