### ISSUE TITLE
Error in as.POSIXct.numeric(e)

### ISSUE THREAD

**Issue by xuzongren** [GreenleafLab/ArchR#217] opened 2020-06-19 01:53 UTC
hi!
    When i run filterDoublets(ArchRProj = proj1),I got an error "Error in as.POSIXct.numeric(e) : 'origin' must be supplied".
    And i don't konw how to solve the problem.There is nothing wrong with the previous steps.
    I want to know how to deal with this problem, continue to analyze the data (My data comes from 10x)
Thanks!

**Comment by rcorces** [comment] 2020-06-19 14:44
Can you reproduce this error using the tutorial dataset?

**Comment by xuzongren** [comment] 2020-06-22 01:21
When i use tutorial dataset,this error does not occur.
Is there something wrong with my data? (but my data comes from 10X cellranger-atac,I didn't do anything else to fragments.tsv.gz file.)
How can I deal with this error?

**Comment by Meggie-MH** [comment] 2020-06-22 05:21
Run into the same error here. Hope to see update on the issue.

**Comment by rcorces** [comment] 2020-06-22 13:25
We will need more information in order to help since we cannot reproduce this error. If you can create a minimal example, including input files, that would be helpful.

**Comment by xuzongren** [comment] 2020-06-23 01:00
The R^2 values of my samples all < 0.9, that mean I can skip this step(filterDoublets)?

**Comment by rcorces** [comment] 2020-06-23 01:33
No, that is not the correct interpretation. see https://github.com/GreenleafLab/ArchR/issues/173#issuecomment-634278512 for an explanation

**Comment by xuzongren** [comment] 2020-06-23 02:11
Thanks. I've read the question( #173 (comment)).
And how can I create a minimal example so that you can better solve this problem?

**Comment by rcorces** [comment] 2020-06-23 03:05
Ideally, take a random 50,000 lines (or the first 50,000 if you prefer) of your fragment file and see if you get the same error. If so, provide us with the small fragment file and the code you used that resulted in the error.

**Comment by jgranja24** [comment] 2020-06-23 07:16
> hi!
> When i run filterDoublets(ArchRProj = proj1),I got an error "Error in as.POSIXct.numeric(e) : 'origin' must be supplied".
> And i don't konw how to solve the problem.There is nothing wrong with the previous steps.
> I want to know how to deal with this problem, continue to analyze the data (My data comes from 10x)
> Thanks!

When does this happen? Towards the end or beginning? Is there a logfile you can share?

**Comment by xuzongren** [comment] 2020-06-23 08:31
@jgranja24 ,This step does not generate any logfiles.
it show me this:
![error](https://user-images.githubusercontent.com/41030907/85379941-e9194980-b56e-11ea-9726-e9ed80da3cbf.png)

**Comment by xuzongren** [comment] 2020-06-24 03:34
@rcorces ,I'm sorry for what I said earlier(I guess I forgot to run the tutorial dataset)
Today,I run tutorial dataset, the same error occurred……emmmm,do you have any suggestions?
Thanks!

**Comment by rcorces** [comment] 2020-06-24 04:13
@Meggie-MH are you also running on Windows? We arent currently supporting windows and I should make that more clear on the home page.

@jgranja24 - I think this is a problem related to date format conversion on Windows from Sys.time(). https://rdrr.io/r/base/Sys.time.html
https://github.com/GreenleafLab/ArchR/blob/efc743c6982a142f1aa33b7d2becc09a3e946d47/R/FilterCells.R#L101

**Comment by Meggie-MH** [comment] 2020-06-24 05:10
@rcorces No, I was running on Mac. I also tried the tutorial dataset and ran into the same error  from filterDoublets. The only thing I did different from the tutorial was creating arrow files by inputting individual fragments.tsv.gz and then combined all the arrow files into one character vector before running the following the steps. For some reasons, it takes infinite time to createarrowfiles directly from 'hemefragments' folder which contains three tsv.gz datasets. Not sure if that's the step starts with this issue.

**Comment by rcorces** [comment] 2020-06-24 14:57
Ok - thats not what I was expecting. The tutorial code should run as expected on MacOS. Are you using RStudio? I think when you say that it takes "infinite time" this is probably because RStudio fails to produce output during certain parallelized steps (but processing is still happening and you should see temp files being produced in the correct output directory). Try running the tutorial code as written from the R command line through Terminal. Also, make sure all of the install instructions have been followed.

**Comment by Meggie-MH** [comment] 2020-06-24 18:41
@rcorces Yes, running tutorial code line by line through RStudio. What I meant by "infinite" is ~2h so I have to manually stop the step. All temp files, log files can be found under the assigned directory without interruption. It's just those sample arrow files were never been completed within the given time. As if it's helpful to provide more details, I ended up with creating individual sample.arrow and took <4min per sample, in other words, same as tutorial indicated ~15min for running the entire datasets together. Also, all the commands ran before filterDoublets have been successful, including creating outputDirectory for ArchRProject object and generating QC plots under output folder, etc. As an potential ArchR user, I sincerely believe that it's unavoidable to run sample separately as for the size of real-world date is around 3GB per fragment file, at least that's the only way to process my own data. I may give it a try with Terminal. Thanks.

**Comment by rcorces** [comment] 2020-06-24 18:53
Hmmm. ok. I think there are two separate issues going on.
1) problems creating arrow files - likely related to using parallelization. I would try running the tutorial code with threads = 1 to see if you still get locked in the "infinite" wait.
2) a specific error in `filterDoublets()` related to the title of this issue. I originally thought the POSIXct error would be a windows-specific problem but it doesnt appear to be that simple. I imagine there is a configuration-specific issue going on. could you provide the output of `sessionInfo()` after running the `filterDoublets()` step that fails.

**Comment by rcorces** [comment] 2020-06-24 19:15
@Meggie-MH can you show me the output of this:
```
library(ArchR)
summary <- c("Date" = Sys.time(), test1 = 1, test2 = "two")
temp <- SimpleList(summary)
str(temp)
```

**Comment by Meggie-MH** [comment] 2020-06-24 19:29
@rcorces Here you go...same error....
> summary <- c("Date" = Sys.time(), test1 = 1, test2 = "two")
Error in as.POSIXct.numeric(e) : 'origin' must be supplied
> temp <- SimpleList(summary)
> str(temp)
Formal class 'SimpleList' [package "S4Vectors"] with 4 slots
  ..@ listData       :List of 1
  .. ..$ :Formal class 'standardGeneric' [package "methods"] with 8 slots
  .. .. .. ..@ .Data     :function (object, ...)  
  .. .. .. ..@ generic   : chr "summary"
  .. .. .. .. ..- attr(*, "package")= chr "base"
  .. .. .. ..@ package   : chr "base"
  .. .. .. ..@ group     : list()
  .. .. .. ..@ valueClass: chr(0) 
  .. .. .. ..@ signature : chr "object"
  .. .. .. ..@ default   :Formal class 'derivedDefaultMethod' [package "methods"] with 4 slots
  .. .. .. .. .. ..@ .Data  :function (object, ...)  
  .. .. .. .. .. ..@ target :Formal class 'signature' [package "methods"] with 3 slots
  .. .. .. .. .. .. .. ..@ .Data  : chr "ANY"
  .. .. .. .. .. .. .. ..@ names  : chr "object"
  .. .. .. .. .. .. .. ..@ package: chr "methods"
  .. .. .. .. .. ..@ defined:Formal class 'signature' [package "methods"] with 3 slots
  .. .. .. .. .. .. .. ..@ .Data  : chr "ANY"
  .. .. .. .. .. .. .. ..@ names  : chr "object"
  .. .. .. .. .. .. .. ..@ package: chr "methods"
  .. .. .. .. .. ..@ generic: chr "summary"
  .. .. .. .. .. .. ..- attr(*, "package")= chr "base"
  .. .. .. ..@ skeleton  : language (new("derivedDefaultMethod", .Data = function (object, ...)  UseMethod("summary"), target = new("signature", .Dat| __truncated__ ...
  ..@ elementType    : chr "ANY"
  ..@ elementMetadata: NULL
  ..@ metadata       : list()

**Comment by rcorces** [comment] 2020-06-24 19:41
Thanks @Meggie-MH - thats very helpful. If you dont mind digging a little bit more on this with me, what is the output of the following things:
1. `Sys.time()`
2. `as.Date(Sys.time())`
3. `as.Date(Sys.time(), origin = "1970-01-01")`
4. `sessionInfo()`

**Comment by Meggie-MH** [comment] 2020-06-24 23:30
@rcorces Of course not. 
> Sys.time()
[1] "2020-06-24 19:25:36 EDT"
> as.Date(Sys.time())
[1] "2020-06-24"
> as.Date(Sys.time(), origin = "1970-01-01")
[1] "2020-06-24"
> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] clustree_0.4.3              ggraph_2.0.3                ArchR_0.9.5                 magrittr_1.5               
 [5] rhdf5_2.32.0                Matrix_1.2-18               data.table_1.12.8           SummarizedExperiment_1.18.1
 [9] DelayedArray_0.14.0         matrixStats_0.56.0          patchwork_1.0.0             EnsDb.Hsapiens.v75_2.99.0  
[13] ensembldb_2.12.1            AnnotationFilter_1.12.0     GenomicFeatures_1.40.0      AnnotationDbi_1.50.0       
[17] Biobase_2.48.0              Signac_0.2.5                ggplot2_3.3.2               dplyr_1.0.0                
[21] Seurat_3.1.5                GenomicRanges_1.40.0        GenomeInfoDb_1.24.2         IRanges_2.22.2             
[25] S4Vectors_0.26.1            BiocGenerics_0.34.0        

loaded via a namespace (and not attached):
  [1] backports_1.1.7                   BiocFileCache_1.12.0              plyr_1.8.6                       
  [4] igraph_1.2.5                      lazyeval_0.2.2                    splines_4.0.1                    
  [7] BiocParallel_1.22.0               listenv_0.8.0                     usethis_1.6.1                    
 [10] digest_0.6.25                     htmltools_0.4.0                   viridis_0.5.1                    
 [13] fansi_0.4.1                       checkmate_2.0.0                   memoise_1.1.0                    
 [16] BSgenome_1.56.0                   cluster_2.1.0                     ROCR_1.0-11                      
 [19] remotes_2.1.1                     graphlayouts_0.7.0                globals_0.12.5                   
 [22] Biostrings_2.56.0                 ggfittext_0.8.1                   askpass_1.1                      
 [25] prettyunits_1.1.1                 colorspace_1.4-1                  blob_1.2.1                       
 [28] rappdirs_0.3.1                    ggrepel_0.8.2                     callr_3.4.3                      
 [31] crayon_1.3.4                      RCurl_1.98-1.2                    jsonlite_1.6.1                   
 [34] survival_3.1-12                   zoo_1.8-8                         ape_5.4                          
 [37] glue_1.4.1                        polyclip_1.10-0                   gtable_0.3.0                     
 [40] zlibbioc_1.34.0                   XVector_0.28.0                    leiden_0.3.3                     
 [43] pkgbuild_1.0.8                    Rhdf5lib_1.10.0                   future.apply_1.5.0               
 [46] scales_1.1.1                      DBI_1.1.0                         Rcpp_1.0.4.6                     
 [49] viridisLite_0.3.0                 progress_1.2.2                    reticulate_1.16                  
 [52] bit_1.1-15.2                      rsvd_1.0.3                        tsne_0.1-3                       
 [55] htmlwidgets_1.5.1                 httr_1.4.1                        RColorBrewer_1.1-2               
 [58] ellipsis_0.3.1                    ica_1.0-2                         farver_2.0.3                     
 [61] pkgconfig_2.0.3                   XML_3.99-0.3                      ggseqlogo_0.1                    
 [64] uwot_0.1.8                        dbplyr_1.4.4                      labeling_0.3                     
 [67] tidyselect_1.1.0                  rlang_0.4.6                       reshape2_1.4.4                   
 [70] munsell_0.5.0                     tools_4.0.1                       cli_2.0.2                        
 [73] generics_0.0.2                    RSQLite_2.2.0                     devtools_2.3.0                   
 [76] ggridges_0.5.2                    stringr_1.4.0                     processx_3.4.2                   
 [79] bit64_0.9-7                       fs_1.4.1                          tidygraph_1.2.0                  
 [82] fitdistrplus_1.1-1                purrr_0.3.4                       RANN_2.6.1                       
 [85] pbapply_1.4-2                     future_1.17.0                     nlme_3.1-148                     
 [88] biomaRt_2.44.0                    compiler_4.0.1                    rstudioapi_0.11                  
 [91] plotly_4.9.2.1                    curl_4.3                          png_0.1-7                        
 [94] testthat_2.3.2                    tweenr_1.0.1                      tibble_3.0.1                     
 [97] stringi_1.4.6                     ps_1.3.3                          RSpectra_0.16-0                  
[100] desc_1.2.0                        lattice_0.20-41                   ProtGenerics_1.20.0              
[103] vctrs_0.3.1                       pillar_1.4.4                      lifecycle_0.2.0                  
[106] BiocManager_1.30.10               lmtest_0.9-37                     RcppAnnoy_0.0.16                 
[109] cowplot_1.0.0                     bitops_1.0-6                      irlba_2.3.3                      
[112] gggenes_0.4.0                     rtracklayer_1.47.0                R6_2.4.1                         
[115] KernSmooth_2.23-17                gridExtra_2.3                     sessioninfo_1.1.1                
[118] codetools_0.2-16                  MASS_7.3-51.6                     assertthat_0.2.1                 
[121] pkgload_1.1.0                     openssl_1.4.1                     rprojroot_1.3-2                  
[124] withr_2.2.0                       GenomicAlignments_1.24.0          sctransform_0.2.1                
[127] Rsamtools_2.4.0                   GenomeInfoDbData_1.2.3            hms_0.5.3                        
[130] grid_4.0.1                        tidyr_1.1.0                       BSgenome.Hsapiens.UCSC.hg19_1.4.3
[133] Cairo_1.5-12                      Rtsne_0.15                        ggforce_0.3.1                    
>

**Comment by jgranja24** [comment] 2020-06-24 23:37
Hi @Meggie-MH can you try running this filterDoublets function where we just remove the line causing the issue

filterDoublets <- function(ArchRProj = NULL, cutEnrich = 1, cutScore = -Inf, filterRatio = 1){

  fn <- unclass(lsf.str(envir = asNamespace("ArchR"), all = TRUE))
    for (i in seq_along(fn)) {
        tryCatch({
            eval(parse(text = paste0(fn[i], "<-ArchR:::", fn[i])))
        }, error = function(x) {
        })
    }

  .validInput(input = ArchRProj, name = "ArchRProj", valid = c("ArchRProj"))
  .validInput(input = cutEnrich, name = "cutEnrich", valid = c("numeric"))
  .validInput(input = cutScore, name = "cutScore", valid = c("numeric"))
  .validInput(input = filterRatio, name = "filterRatio", valid = c("numeric"))

  if(any(grepl("filterDoublets", names(ArchRProj@projectSummary)))){
    stop("Already ran filterDoublets on ArchRProject! Cannot be re-ran on an ArchRProject!")
  }

  df <- getCellColData(ArchRProj, c("Sample", "DoubletEnrichment", "DoubletScore"))
  splitDF <- split(seq_len(nrow(df)), as.character(df$Sample))

  cellsFilter <- lapply(splitDF, function(y){

    x <- df[y, ,drop = FALSE]

    n <- nrow(x)

    x <- x[order(x$DoubletEnrichment, decreasing = TRUE), ]
    
    if(!is.null(cutEnrich)){
      x <- x[which(x$DoubletEnrichment >= cutEnrich), ]
    } 
    
    if(!is.null(cutScore)){
      x <- x[which(x$DoubletScore >= cutScore), ]
    } 

    if(nrow(x) > 0){
      head(rownames(x), filterRatio * n * (n / 100000))
    }else{
      NULL
    }

  }) %>% unlist(use.names=FALSE)

  message("Filtering ", length(cellsFilter), " cells from ArchRProject!")
  tabRemove <- table(df[cellsFilter,]$Sample)
  tabAll <- table(df$Sample)
  samples <- unique(df$Sample)
  for(i in seq_along(samples)){
    if(!is.na(tabRemove[samples[i]])){
      message("\t", samples[i], " : ", tabRemove[samples[i]], " of ", tabAll[samples[i]], " (", round(100 * tabRemove[samples[i]] / tabAll[samples[i]], 1),"%)")
    }else{
      message("\t", samples[i], " : ", 0, " of ", tabAll[samples[i]], " (0%)")
    }
  }

  if(length(cellsFilter) > 0){
    
    ArchRProj@cellColData <- ArchRProj@cellColData[rownames(ArchRProj@cellColData) %ni% cellsFilter,,drop=FALSE]

  }
  
  ArchRProj

}

**Comment by rcorces** [comment] 2020-06-24 23:49
My assumption is that there is something different about how R 4.0 handles POSIX dates but I dont have a strong rationale for why this would be. We havent tested ArchR on R 4.0 yet and have seen a few other issues crop up related to R 4.0. Could be worth your while to downgrade to R 3.6 but we should work towards addressing R 4.0 issues since more and more people will be upgrading soon.

In addition to @jgranja24 's suggestion, could you try the following to see if it avoids the error?
```
summary <- c("Date" = as.Date(Sys.time(), origin = "1970-01-01"), test1 = 1, test2 = "two")
```

**Comment by Meggie-MH** [comment] 2020-06-25 17:51
@rcorces Woohoo, rewrite the function works! Thanks a lot :)

- Back to your previous question, it does't avoid the error when running > summary <- c("Date" = as.Date(Sys.time(), origin = "1970-01-01"), test1 = 1, test2 = "two")

**Comment by huidongchen** [comment] 2020-06-25 21:06
First of all, thanks for creating such an amazing tool! I have been such a huge fan.

Unfortunately I'm running into the same problem. The same error happens when filtering doublets. (I m running it on Linux) 

`proj <- filterDoublets(ArchRProj = proj,cutEnrich=5)`

Error info
```
Error in as.POSIXct.numeric(e): 'origin' must be supplied
Traceback:
1. filterDoublets(ArchRProj = proj, cutEnrich = 5)
2. addProjectSummary(ArchRProj = ArchRProj, name = "filterDoublets", 
 .     summary = c(Date = Sys.time(), cutEnrich = cutEnrich, cutScore = cutScore, 
 .         filterRatio = filterRatio))
3. append(pS, SimpleList(summary))
4. SimpleList(summary)
5. c(Date = Sys.time(), cutEnrich = cutEnrich, cutScore = cutScore, 
 .     filterRatio = filterRatio)
6. c.POSIXct(Date = Sys.time(), cutEnrich = cutEnrich, cutScore = cutScore, 
 .     filterRatio = filterRatio)
7. .POSIXct(c(unlist(lapply(list(...), function(e) unclass(as.POSIXct(e))))))
8. unlist(lapply(list(...), function(e) unclass(as.POSIXct(e))))
9. lapply(list(...), function(e) unclass(as.POSIXct(e)))
10. FUN(X[[i]], ...)
11. as.POSIXct(e)
12. as.POSIXct.numeric(e)
13. stop("'origin' must be supplied")
```

**Comment by rcorces** [comment] 2020-06-25 22:40
@Meggie-MH - thanks for checking. We will update the dev branch with the fix from @jgranja24 

@huidongchen - can you confirm which version of R you are using? Presumably >4.0?

**Comment by huidongchen** [comment] 2020-06-25 22:44
> @huidongchen - can you confirm which version of R you are using? Presumably >4.0?

Thanks for your quick reply! Yes, I'm using R 4.0.1

**Comment by xuzongren** [comment] 2020-06-28 07:36
@jgranja24 ,Thanks for your help!
@rcorces ,And I've run this function successfully,Using the function @jgranja24 wrote.
Thanks again for all your help! (I also use R 4.0.1)

**Comment by shaka87** [comment] 2020-07-08 20:31
I can confirm this problem. The fixed function worked for me and I am happy to have found the information in this thread!

My system: 

R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin19.5.0 (64-bit)

**Comment by rcorces** [comment] 2020-07-08 21:05
@jgranja24 can you make the relevant update(s) in dev? This gets rid of the project summary so if anything downstream uses the summary that will also need to change

**Comment by ankushs0128** [comment] 2020-08-07 11:29
Facing the Same Issue on R 4.0.1! Running filterdoublet functions works well

> Hi @Meggie-MH can you try running this filterDoublets function where we just remove the line causing the issue
> 
> ```
> 
> filterDoublets <- function(ArchRProj = NULL, cutEnrich = 1, cutScore = -Inf, filterRatio = 1){
> 
>   fn <- unclass(lsf.str(envir = asNamespace("ArchR"), all = TRUE))
>     for (i in seq_along(fn)) {
>         tryCatch({
>             eval(parse(text = paste0(fn[i], "<-ArchR:::", fn[i])))
>         }, error = function(x) {
>         })
>     }
> 
>   .validInput(input = ArchRProj, name = "ArchRProj", valid = c("ArchRProj"))
>   .validInput(input = cutEnrich, name = "cutEnrich", valid = c("numeric"))
>   .validInput(input = cutScore, name = "cutScore", valid = c("numeric"))
>   .validInput(input = filterRatio, name = "filterRatio", valid = c("numeric"))
> 
>   if(any(grepl("filterDoublets", names(ArchRProj@projectSummary)))){
>     stop("Already ran filterDoublets on ArchRProject! Cannot be re-ran on an ArchRProject!")
>   }
> 
>   df <- getCellColData(ArchRProj, c("Sample", "DoubletEnrichment", "DoubletScore"))
>   splitDF <- split(seq_len(nrow(df)), as.character(df$Sample))
> 
>   cellsFilter <- lapply(splitDF, function(y){
> 
>     x <- df[y, ,drop = FALSE]
> 
>     n <- nrow(x)
> 
>     x <- x[order(x$DoubletEnrichment, decreasing = TRUE), ]
>     
>     if(!is.null(cutEnrich)){
>       x <- x[which(x$DoubletEnrichment >= cutEnrich), ]
>     } 
>     
>     if(!is.null(cutScore)){
>       x <- x[which(x$DoubletScore >= cutScore), ]
>     } 
> 
>     if(nrow(x) > 0){
>       head(rownames(x), filterRatio * n * (n / 100000))
>     }else{
>       NULL
>     }
> 
>   }) %>% unlist(use.names=FALSE)
> 
>   message("Filtering ", length(cellsFilter), " cells from ArchRProject!")
>   tabRemove <- table(df[cellsFilter,]$Sample)
>   tabAll <- table(df$Sample)
>   samples <- unique(df$Sample)
>   for(i in seq_along(samples)){
>     if(!is.na(tabRemove[samples[i]])){
>       message("\t", samples[i], " : ", tabRemove[samples[i]], " of ", tabAll[samples[i]], " (", round(100 * tabRemove[samples[i]] / tabAll[samples[i]], 1),"%)")
>     }else{
>       message("\t", samples[i], " : ", 0, " of ", tabAll[samples[i]], " (0%)")
>     }
>   }
> 
>   if(length(cellsFilter) > 0){
>     
>     ArchRProj@cellColData <- ArchRProj@cellColData[rownames(ArchRProj@cellColData) %ni% cellsFilter,,drop=FALSE]
> 
>   }
>   
>   ArchRProj
> 
> }
> ```

**Comment by rcorces** [comment] 2020-08-11 18:57
@jgranja24 - can you make this update on `dev`?

**Comment by jgranja24** [comment] 2020-10-15 02:52
This is now fixed on the release branch

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
`

Closing this issue, if you have any more troubles please open a new issue!

Best

Jeff

**Closed by jgranja24** 2020-10-15 02:52 UTC
Labels: documentation
