### ISSUE TITLE
Cell type specific differential analysis between case and control

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#97] opened 2020-05-02 15:57 UTC
Hi,

**Describe the problem that your feature request would address.**
Great package, but I think one important aspect of the analysis is missing in your package.
I would love to have the following feature in your package.
Given that fact most of the time people have single-cell data from case and control groups, and they are interested to learn about disease-specific perturbation in a cell type-specific manner.
For example, linking differential peaks (between disease-control) to differential gene expression. or
Looking for differential TF activity in a specific cell type between case and control.

Having these features can increase the use case of your package.

**Comment by rcorces** [comment] 2020-05-02 16:16
This appears to be a duplicate of #96 
Closing

**Closed by rcorces** 2020-05-02 16:16 UTC
Labels: enhancement

**Comment by CSBioAzim** [comment] 2020-05-02 17:24
@rcorces, I know this, but this section does only differential analysis between cell types.
What do I mean is that doing differential analysis for cell type A between condition 1 and condition 2. 
Also, if I have samples from two categories (condition A, B), do I need to do peak calling combined or I should do it separately?

**Comment by jgranja24** [comment] 2020-05-02 21:06
> What do I mean is that doing differential analysis for cell type A between condition 1 and condition 2.

This is already described in the manual, just add a new grouping column in the cellColData of the ArchRProject.

> Also, if I have samples from two categories (condition A, B), do I need to do peak calling combined or I should do it separately?

Peak calling should be done on the lowest grouping format of your cells. So they should be separated for peak calling.

**Comment by jgranja24** [comment] 2020-05-02 21:07
Oh this was already answered by @rcorces in #96

**Comment by rcorces** [comment] 2020-05-02 21:28
Yes - please don't continue to post the same material in two different issues
