### ISSUE TITLE
gene plotEmbedding error

### ISSUE THREAD

**Issue by brinrosenthal** [GreenleafLab/ArchR#1296] opened 2022-02-18 00:56 UTC
I am getting the following warning when I run plotEmbedding with a marker gene. And the plot is empty (no cells at all). The command works fine when colorBy is cellColData.

> 
> 1 
> Warning message:
> “Computation failed in `stat_summary_hex()`:
> ”

This is the command which throws the error:
```
p <- plotEmbedding(
    ArchRProj = proj, 
    colorBy = "GeneScoreMatrix", 
    name = "PECAM1", 
    embedding = "UMAP",
    imputeWeights = getImputeWeights(proj),
    verbose=TRUE
)

```

**To Reproduce**
I have reproduced the error with the tutorial data

Log file attached

[ArchR-plotEmbedding-16dde547014a2-Date-2022-02-18_Time-00-52-15.log](https://github.com/GreenleafLab/ArchR/files/8093262/ArchR-plotEmbedding-16dde547014a2-Date-2022-02-18_Time-00-52-15.log)

**Comment by rcorces** [comment] 2022-02-18 00:56
Hi @brinrosenthal! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment] 2022-02-18 01:00
This is a duplicate of https://github.com/GreenleafLab/ArchR/issues/1292
Unfortunately, I thought that original issue was going to be an isolated incident. Clearly it isnt a user-specific issue.  I will close this and re-open the original post. Please follow up there.
Your log file doesnt appear to be a log file so maybe you can upload that again under https://github.com/GreenleafLab/ArchR/issues/1292

**Closed by rcorces** 2022-02-18 01:00 UTC
Labels: bug
