### ISSUE TITLE
addGeneIntegrationMatrix error

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#174] opened 2020-05-25 17:01 UTC
Hello,

Im getting an error running addGeneIntegrationMatrix as follows:
```

> archp <- addGeneIntegrationMatrix(
+     ArchRProj = archp, 
+     useMatrix = "GeneScoreMatrix",
+     matrixName = "GeneIntegrationMatrix",
+     reducedDims = "IterativeLSI",
+     seRNA = rnaCFd,
+     addToArrow = TRUE,
+     groupRNA = "celltype",
+     nameCell = "predictedCell_Un",
+     nameGroup = "predictedGroup_Un",
+     nameScore = "predictedScore_Un"
+ )
ArchR logging to : ArchRLogs/ArchR-addGeneIntegrationMatrix-622261a82576-Date-2020-05-25_Time-16-42-27.log
If there is an issue, please report to github with logFile!
2020-05-25 16:42:28 : Running Seurat's Integration Stuart* et al 2019, 0.004 mins elapsed.
2020-05-25 16:43:04 : Checking ATAC Input, 0.616 mins elapsed.
2020-05-25 16:43:04 : Checking RNA Input, 0.617 mins elapsed.
2020-05-25 16:43:08 : Creating Integration Blocks, 0.674 mins elapsed.
2020-05-25 16:43:08 : Prepping Interation Data, 0.682 mins elapsed.
2020-05-25 16:43:09 : Computing Integration in 5 Integration Blocks!, 0 mins elapsed.
2020-05-25 16:43:09 : Block (1 of 5) : Computing Integration, 0 mins elapsed.
2020-05-25 16:43:09 : Block (2 of 5) : Computing Integration, 0.001 mins elapsed.
2020-05-25 16:43:09 : Block (3 of 5) : Computing Integration, 0.001 mins elapsed.
2020-05-25 16:43:09 : Block (4 of 5) : Computing Integration, 0.001 mins elapsed.
2020-05-25 16:43:09 : Block (5 of 5) : Computing Integration, 0.002 mins elapsed.
2020-05-25 16:43:24 : Block (3 of 5) : Identifying Variable Genes, 0.239 mins elapsed.
2020-05-25 16:43:24 : Block (1 of 5) : Identifying Variable Genes, 0.241 mins elapsed.
2020-05-25 16:43:24 : Block (4 of 5) : Identifying Variable Genes, 0.241 mins elapsed.
2020-05-25 16:43:24 : Block (2 of 5) : Identifying Variable Genes, 0.242 mins elapsed.
2020-05-25 16:43:24 : Block (5 of 5) : Identifying Variable Genes, 0.243 mins elapsed.
2020-05-25 16:43:32 : Block (1 of 5) : Getting GeneScoreMatrix, 0.375 mins elapsed.
2020-05-25 16:43:32 : Block (3 of 5) : Getting GeneScoreMatrix, 0.375 mins elapsed.
2020-05-25 16:43:32 : Block (2 of 5) : Getting GeneScoreMatrix, 0.376 mins elapsed.
2020-05-25 16:43:32 : Block (4 of 5) : Getting GeneScoreMatrix, 0.376 mins elapsed.
2020-05-25 16:43:32 : Block (5 of 5) : Getting GeneScoreMatrix, 0.377 mins elapsed.
2020-05-25 16:43:53 : Block (5 of 5) : Imputing GeneScoreMatrix, 0.732 mins elapsed.
2020-05-25 16:43:53 : Block (2 of 5) : Imputing GeneScoreMatrix, 0.732 mins elapsed.
2020-05-25 16:43:53 : Block (1 of 5) : Imputing GeneScoreMatrix, 0.732 mins elapsed.
2020-05-25 16:43:53 : Block (4 of 5) : Imputing GeneScoreMatrix, 0.732 mins elapsed.
2020-05-25 16:43:53 : Block (3 of 5) : Imputing GeneScoreMatrix, 0.732 mins elapsed.
Getting ImputeWeights
Getting ImputeWeights
Getting ImputeWeights
Getting ImputeWeights
Getting ImputeWeights
2020-05-25 16:44:54 : Block (2 of 5) : Seurat FindTransferAnchors, 1.746 mins elapsed.
2020-05-25 16:44:55 : Block (1 of 5) : Seurat FindTransferAnchors, 1.757 mins elapsed.
2020-05-25 16:44:55 : Block (4 of 5) : Seurat FindTransferAnchors, 1.759 mins elapsed.
2020-05-25 16:44:55 : Block (3 of 5) : Seurat FindTransferAnchors, 1.762 mins elapsed.
2020-05-25 16:44:56 : Block (5 of 5) : Seurat FindTransferAnchors, 1.787 mins elapsed.
<simpleError in `.rowNamesDF<-`(x, value = value): invalid 'row.names' length>
<simpleError in `.rowNamesDF<-`(x, value = value): invalid 'row.names' length>
<simpleError in `.rowNamesDF<-`(x, value = value): invalid 'row.names' length>
<simpleError in `.rowNamesDF<-`(x, value = value): invalid 'row.names' length>
<simpleError in `.rowNamesDF<-`(x, value = value): invalid 'row.names' length>
Error in .safelapply(seq_along(blockList), function(i) { : 
Error Found Iteration 1 : 
	[1] "Error in .retryCatch({ : \n"
	<simpleError in .retryCatch({    gc()    Seurat::FindTransferAnchors(reference = subRNA, query = seuratATAC,         reduction = reduction, features = genesUse, verbose = FALSE,         ...)}, maxAttempts = 2, logFile = logFile): >
Error Found Iteration 2 : 
	[1] "Error in .retryCatch({ : \n"
	<simpleError in .retryCatch({    gc()    Seurat::FindTransferAnchors(reference = subRNA, query = seuratATAC,         reduction = reduction, features = genesUse, verbose = FALSE,         ...)}, maxAttempts = 2, logFile = logFile): >
Error Found Iteration 3 : 
	[1] "Error in .retryCatch({ : \n"
	<simpleError in .retryCatch({    gc()    Seurat::FindTransferAnchors(reference = subRNA, query = seuratATAC,         reduction = reduction, features = genesUse, verbose = FALSE,         ...)}, maxAttempts = 2, logFile = logFile): >
Error Found Iteration 4 : 
	[1] "Error in .retryCatch({ : \n"
	<simpleError in .retryCatch({    gc()    
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  5 function calls resulted in an error
```

Thanks a lot!

[ArchR-addGeneIntegrationMatrix-622261a82576-Date-2020-05-25_Time-16-42-27.log](https://github.com/GreenleafLab/ArchR/files/4678204/ArchR-addGeneIntegrationMatrix-622261a82576-Date-2020-05-25_Time-16-42-27.log)

**Comment by mjprzybilla** [comment] 2020-06-09 01:08
Hey guys, 

do you have any idea on a solution to this problem? 
I've been running into a similar issue, which at first was related to [#193](https://github.com/GreenleafLab/ArchR/issues/193). Changing the number of threads `addArchRThreads(threads = 1)` seemed to solve it at first, but then resulted in the same error @Brawni reported. 
Would greatly appreciate your help/thoughts on this! 

Many thanks, 
Moritz

**Comment by jgranja24** [comment] 2020-06-11 17:37
Hi all, I am working on this now sorry for the delay.

**Comment by jgranja24** [comment] 2020-06-16 18:03
It looks like Seurat had this issue [https://github.com/satijalab/seurat/issues/2726](https://github.com/satijalab/seurat/issues/2726) resolved in there current devbranch. Can you confirm if this is still an issue with their version

```
devtools::install_github(
 "satijalab/seurat", 
  ref = "develop",
  repos = BiocManager::repositories()
)

```

**Comment by mjprzybilla** [comment] 2020-06-16 22:50
Thanks for looking into it Jeff! This solves the issue in my case - many thanks!

**Comment by Brawni** [comment] 2020-06-18 03:15
Yes this now works thanks!

**Closed** 2020-06-18 03:16 UTC
Labels: bug

**Comment by NoemieL** [comment] 2020-06-26 19:21
Hi, for me the problem is still there..... with 1 or 2 threads but only for the constrained integration.

[ArchR-addGeneIntegrationMatrix-292746fc293-Date-2020-06-26_Time-11-05-30.log](https://github.com/GreenleafLab/ArchR/files/4838867/ArchR-addGeneIntegrationMatrix-292746fc293-Date-2020-06-26_Time-11-05-30.log)
[ArchR-addGeneIntegrationMatrix-292756c2df99-Date-2020-06-26_Time-13-18-05.log](https://github.com/GreenleafLab/ArchR/files/4838881/ArchR-addGeneIntegrationMatrix-292756c2df99-Date-2020-06-26_Time-13-18-05.log)

**Comment by NoemieL** [comment] 2020-07-07 20:41
After reinstalling packages processx and Seurat, it is now working for me too
