### ISSUE TITLE
Unexpected behavior of addGroupCoverages

### ISSUE THREAD

**Issue by GrafZahl1234** [GreenleafLab/ArchR#1742] opened 2022-11-16 17:30 UTC
Hi everyone,

I have looked through Issues and I did not find anything alike, so I believe it was not reported before. It is also not a error in the classic way in that it stops the function from running through, its more like I don't get the result I would expect. I tried it now with two different datasets, one is the Hema Set from the manual. I hope the whole thing is not a misunderstanding on my side what the function is supposed to do, as I am still a beginner.

My goal is to generate a high number of pseudobulks covering most of the cells in each group, each with a standardized number of cells. I use the function call shown below, you will find the Log attached.

```
ArchR_Proj <- addGroupCoverages(
  ArchRProj = ArchR_Proj,
  groupBy = "Clusters2",
  useLabels = TRUE,
  minCells = 50,
  maxCells = 50,
  maxFragments = 5 * 10^6,
  minReplicates = 10,
  maxReplicates = 20,
  sampleRatio = 0.8,
  kmerLength = 6,
  threads = 10,
  returnGroups = FALSE,
  parallelParam = NULL,
  force = TRUE,
  verbose = TRUE,
  logFile = createLogFile("addGroupCoverages")
)
```
The groups I get now are absolutely not what I would expect. For most clusters I just get 2-3 replicates, despite the fact that there are plenty of cells. For other clusters on the other hand I get 10 replicates, despite these clusters not having enough cells. Setting threads=1 does not change the situation.

The image below shows the result of 
```
ArchR_Proj <- addReproduciblePeakSet(
    ArchRProj = ArchR_Proj,
    groupBy = "Clusters2",
    pathToMacs2 = pathToMacs2,
    threads = 1, 
    force = TRUE
)
```
[ArchR-addGroupCoverages-b0ad3f49d0c5-Date-2022-11-16_Time-17-51-28.log](https://github.com/GreenleafLab/ArchR/files/10024217/ArchR-addGroupCoverages-b0ad3f49d0c5-Date-2022-11-16_Time-17-51-28.log)
![Screenshot from 2022-11-16 18-25-49](https://user-images.githubusercontent.com/73557574/202250593-d3c3b11b-64a7-4d7c-a47b-e7cb8ba7b626.png)

**Comment by rcorces** [comment] 2022-11-16 17:31
Hi @GrafZahl1234! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment] 2022-11-16 18:54
I think you are bumping into an edge case that is quite complicated. You've set `useLabels = TRUE`  which means that ArchR is going to try to create sample-aware pseudobulk replicates. In the context of the very low cell numbers in the tutorial, this leads to the behavior you are seeing because some cell types are able to make sample-aware pseudobulks while others are not. I agonized over the flowchart shown in the manual here - https://www.archrproject.com/bookdown/how-does-archr-make-pseudo-bulk-replicates.html

If you are able to prove that something violates this flow chart, then I'm happy to dig into the code and figure it out. But you'll notice that if you set `useLabels = FALSE`, you get the result that you were expecting.

I'm going to close this but feel free to prove the flow chart wrong and post again here and I'll look into it.

**Closed by rcorces** 2022-11-16 18:54 UTC
Labels: bug
