### ISSUE TITLE
addGeneIntegrationMatrix() only recogize reduction name  "IteractiveLSI"

### ISSUE THREAD

**Issue by laiyiwei** [GreenleafLab/ArchR#202] opened 2020-06-10 09:16 UTC
I was using Harmony for batch correction so I named the reduction as "Harmony". However, ArchR never recognizes it until I rename it as "IteractiveLSI".

**Comment by juliabelk** [comment] 2020-06-30 19:21
Hmm I think I'm also running into this - 

```
addGeneIntegrationMatrix(
    ArchRProj = proj, 
    useMatrix = "GeneScoreMatrix",
    matrixName = "GeneIntegrationMatrix",
    reducedDims = "IterativeLSI",
    ...
)
```

I get the below error if I pass anything to `reducedDims` other than `IterativeLSI`

If there is an issue, please report to github with logFile!
2020-06-30 11:29:23 : Running Seurat's Integration Stuart* et al 2019, 0.011 mins elapsed.
2020-06-30 11:29:24 : Checking ATAC Input, 0.02 mins elapsed.
2020-06-30 11:29:24 : Checking RNA Input, 0.021 mins elapsed.
2020-06-30 11:29:26 : Creating Integration Blocks, 0.062 mins elapsed.
2020-06-30 11:29:26 : Prepping Interation Data, 0.067 mins elapsed.
2020-06-30 11:29:27 : Computing Integration in 2 Integration Blocks!, 0 mins elapsed.
2020-06-30 11:29:27 : Block (1 of 2) : Computing Integration, 0.001 mins elapsed.
2020-06-30 11:29:27 : Block (2 of 2) : Computing Integration, 0.002 mins elapsed.
2020-06-30 11:29:36 : Block (1 of 2) : Identifying Variable Genes, 0.154 mins elapsed.
2020-06-30 11:29:36 : Block (2 of 2) : Identifying Variable Genes, 0.154 mins elapsed.
2020-06-30 11:29:45 : Block (1 of 2) : Getting GeneScoreMatrix, 0.298 mins elapsed.
2020-06-30 11:29:45 : Block (2 of 2) : Getting GeneScoreMatrix, 0.298 mins elapsed.
2020-06-30 11:29:59 : Block (2 of 2) : Imputing GeneScoreMatrix, 0.54 mins elapsed.
2020-06-30 11:30:00 : Block (1 of 2) : Imputing GeneScoreMatrix, 0.542 mins elapsed.
Error in .safelapply(seq_along(blockList), function(i) { : 
Error Found Iteration 1 : 
	[1] "Error in getReducedDims(ArchRProj, reducedDims = reducedDims, dimsToUse = dimsToUse,  : \n  Reduced dimensions not in computed reduceDims, Current ones are : All_5_LSI,All_10_LSI,All_15_LSI,All_25_LSI,All_40_LSI,All_50_LSI,All_20_LSI,Tcell_5_LSI
	<simpleError in getReducedDims(ArchRProj, reducedDims = reducedDims, dimsToUse = dimsToUse,     corCutOff = corCutOff): Reduced dimensions not in computed reduceDims, Current ones are : All_5_LSI,All_10_LSI,All_15_LSI,All_25_LSI,All_40_LSI,All_50_LSI
Error Found Iteration 2 : 
	[1] "Error in getReducedDims(ArchRProj, reducedDims = reducedDims, dimsToUse = dimsToUse,  : \n  Reduced dimensions not in computed reduceDims, Current ones are : All_5_LSI,All_10_LSI,All_15_LSI,All_25_LSI,All_40_LSI,All_50_LSI,All_20_LSI,Tcell_5_LSI
	<simpleError in getReducedDims(ArchRProj, reducedDims = reducedDims, dimsToUse = dimsToUse,     corCutOff = corCutOff): Reduced dimensions not in computed reduceDims, Current one
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  2 function calls resulted in an error

**Comment by stem-sam** [comment] 2020-10-17 23:32
Hello, 

I, too, am getting an error just as @juliabelk is experiencing. Despite the fact that I have "Current ones" that I've made previously (ArchR_object@reducedDims$LSI*), the addGeneIntegrationMatrix() fails with the same error as above ("Reduced dimensions not in computed reduceDims, Current ones are: etc. etc.). 

Thanks you for your help!


proj_ATAC <- addIterativeLSI(
  ArchRProj = proj_ATAC,
  useMatrix = "TileMatrix", 
  name = "IterativeLSI_4", 
  iterations = 4, 
  clusterParams = list( #See Seurat::FindClusters
    resolution = c(0.1, 0.2, 0.4), 
    sampleCells = 20000, 
    n.start = 10
  ), 
  varFeatures = 25000, 
  dimsToUse = 1:30
)


*followed tutorial to 'addGeneIntegrationMatrix'*

proj_ATAC <- addGeneIntegrationMatrix(
  ArchRProj = proj_ATAC, 
  useMatrix = "GeneScoreMatrix",
  matrixName = "GeneIntegrationMatrix",
  reducedDims = "IterativeLSI_4",
  seRNA = scRNAseq,
  addToArrow = FALSE,
  groupRNA = "BioClassification",
  nameCell = "predictedCell_Un",
  nameGroup = "predictedGroup_Un",
  nameScore = "predictedScore_Un"
)

Error in .safelapply(seq_along(blockList), function(i) { : 
Error Found Iteration 1 : 
        [1] "Error in getReducedDims(ArchRProj, reducedDims = reducedDims, dimsToUse = dimsToUse,  : \n  Reduced dimensions not in computed reduceDims, Current ones are : etc. etc. ...

**Comment by juliabelk** [comment] 2020-10-18 00:10
in case its helpful to anyone here is a workaround which I have been using

```
  proj@reducedDims[["IterativeLSI"]] <- proj@reducedDims[[dr]]

  proj <- addGeneIntegrationMatrix(
      ArchRProj=proj,
      reducedDims="IterativeLSI",
      ...
  )   

  proj@reducedDims[["IterativeLSI"]] <- NULL
```

**Comment by jgranja24** [comment] 2020-10-18 05:57
I see the issue, the problem was `addImputeWeights` was being called without supplying it with your reduceDims. I was able to reproduce this bug and it is now fixed in the release branch. See below -

```
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)

load("Chapter-10-MarkerPeaks.Rdata")

projHeme2@reducedDims[["IterativeLSI"]] <- NULL

projHeme2 <- ArchR::addGeneIntegrationMatrix(
    ArchRProj = projHeme2, 
    useMatrix = "GeneScoreMatrix",
    matrixName = "GeneIntegrationMatrix",
    reducedDims = "Harmony",
    seRNA = seRNA,
    addToArrow = FALSE,
    groupRNA = "BioClassification",
    nameCell = "predictedCell_Un",
    nameGroup = "predictedGroup_Un",
    nameScore = "predictedScore_Un"
)

# #Previous Error
# ArchR logging to : ArchRLogs/ArchR-addGeneIntegrationMatrix-295087ccc2daf-Date-2020-10-17_Time-17-35-36.log
# If there is an issue, please report to github with logFile!
# 2020-10-17 17:35:36 : Running Seurat's Integration Stuart* et al 2019, 0.004 mins elapsed.
# 2020-10-17 17:35:43 : Checking ATAC Input, 0.125 mins elapsed.
# 2020-10-17 17:35:43 : Checking RNA Input, 0.126 mins elapsed.
# 2020-10-17 17:35:52 : Creating Integration Blocks, 0.271 mins elapsed.
# 2020-10-17 17:35:53 : Prepping Interation Data, 0.285 mins elapsed.
# 2020-10-17 17:35:54 : Computing Integration in 1 Integration Blocks!, 0 mins elapsed.
# 2020-10-17 17:35:54 : Block (1 of 1) : Computing Integration, 0 mins elapsed.
# 2020-10-17 17:35:59 : Block (1 of 1) : Identifying Variable Genes, 0.075 mins elapsed.
# 2020-10-17 17:36:05 : Block (1 of 1) : Getting GeneScoreMatrix, 0.173 mins elapsed.
# 2020-10-17 17:36:11 : Block (1 of 1) : Imputing GeneScoreMatrix, 0.274 mins elapsed.
# ArchR logging to : ArchRLogs/ArchR-addImputeWeights-295085c202bf5-Date-2020-10-17_Time-17-36-11.log
# If there is an issue, please report to github with logFile!
# 2020-10-17 17:36:11 : Computing Impute Weights Using Magic (Cell 2018), 0 mins elapsed.
# Error in getReducedDims(ArchRProj, reducedDims = reducedDims, dimsToUse = dimsToUse,  : 
#   Reduced dimensions not in computed reduceDims, Current ones are : IterativeLSI2,Harmony

```

**Comment by stem-sam** [comment] 2020-10-18 07:24
Thank you @juliabelk for the workaround, and thank you @jgranja24 for fixing the bug!

**Comment by rcorces** [comment] 2020-10-19 14:28
@jgranja24 - what was the fix here? better error reporting? Just checking to make sure documentation doesnt need to be updated.
Also - typo in "reduceDims" in the error report:

> Reduced dimensions not in computed reduceDims, Current ones are : IterativeLSI2,Harmony

**Comment by jgranja24** [comment] 2020-10-20 03:11
There was a bug with addImputeWeights was being called without supplying it with your reduceDims. I am closing this issue. Feel free to open a new issue if there are others!

**Closed by jgranja24** 2020-10-20 03:11 UTC
