### ISSUE TITLE
How to sort the specified cells on the Marker Peak Heatmaps

### ISSUE THREAD

**Issue by xz333** [GreenleafLab/ArchR#560] opened 2021-03-02 09:35 UTC
Hi Ryan @rcorces ！

![image](https://user-images.githubusercontent.com/77724576/109627919-19dd6400-7b7d-11eb-97bd-ca3475d06d5a.png)

Can I sort the cell types in the heatmap from top to bottom according to specific cell types like this?
 "L23it","L4it","L5it","L6it","L5/6 IT Car3","L5et", "L56np","L6ct","L6b"

Thanks

**Comment by rcorces** [comment] 2021-03-02 15:25
This is not currently possible inside of ArchR but we are working on it.. This is a close duplicate of #329 and #511 so I'm closing this. Feel free to post at #329 if you would like to continue the discussion there.

**Closed by rcorces** 2021-03-02 15:25 UTC
