### ISSUE TITLE
2020-07-24 17:14:52 : ERROR Found in .tabixToTmp for (CAT-07 : 1 of 1)

### ISSUE THREAD

**Issue by RyanYip-Kat** [GreenleafLab/ArchR#260] opened 2020-07-24 09:20 UTC
I tried all the similiar issue report listed,but it still did not work!

**Comment by doctorxie** [comment] 2020-07-29 11:13
I have encounterd the same problem. ERROR Found in .tabixToTmp for (/home/data/ArchR_input/A088_fragments.tsv.gz : 1 of 6)

**Comment by rcorces** [comment] 2020-08-11 18:19
Apologies for the delay in our response. However, we have no way of addressing your issue without a more detailed report. If this issue does not occur with the tutorial dataset, then it is likely an issue with your input. I'm closing this issue due to lack of specificity but feel free to open it and provide a more in depth report with a workable example to reproduce.

**Closed by rcorces** 2020-08-11 18:19 UTC
Labels: bug

**Comment by schae211** [comment] 2022-02-17 12:37
For other people googling this issue: I got this error when I used the wrong annotation, so check which annotation you are using.
