### ISSUE TITLE
error in addUMAP in R 4.0.3

### ISSUE THREAD

**Issue by bioinfo-sc** [GreenleafLab/ArchR#424] opened 2020-11-18 07:12 UTC
Hi, 

I have installed the latest version of ArchR following the instructions without any error. Then I tried to run the example provided on the website and met two errors.

1. Error in as.POSIXct.numeric(e) when filtering doublets
I followed suggestions in issue #217 and then the error message is gone.
2. Then I was trying to run proj <- addUMAP(ArchRProj = proj, reducedDims = "IterativeLSI")
and got the error message "Error in model$nn_index$save(nn_tmpfname) : attempt to apply non-function"

This seems to be the same issue as https://github.com/GreenleafLab/ArchR/issues/386
I was trying to uninstall uwot 0.1.9 and reinstall version 0.1.8 but failed.

Here is my session info. Would you please suggest how to fix this error message? Thank you very much.

R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.7 (Maipo)

Matrix products: default
BLAS/LAPACK: /path/ArchRBak/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils
 [8] datasets  methods   base

other attached packages:
 [1] uwot_0.1.9                        gridExtra_2.3
 [3] nabor_0.5.0                       Seurat_3.2.2
 [5] BSgenome.Hsapiens.UCSC.hg19_1.4.3 BSgenome_1.58.0
 [7] rtracklayer_1.50.0                Biostrings_2.58.0
 [9] XVector_0.30.0                    ArchR_1.0.0
[11] magrittr_2.0.1                    rhdf5_2.34.0
[13] Matrix_1.2-18                     data.table_1.13.2
[15] SummarizedExperiment_1.20.0       Biobase_2.50.0
[17] GenomicRanges_1.42.0              GenomeInfoDb_1.26.0
[19] IRanges_2.24.0                    S4Vectors_0.28.0
[21] BiocGenerics_0.36.0               MatrixGenerics_1.2.0
[23] matrixStats_0.57.0                ggplot2_3.3.2

loaded via a namespace (and not attached):
  [1] Rtsne_0.15               colorspace_2.0-0         deldir_0.2-3
  [4] ellipsis_0.3.1           ggridges_0.5.2           spatstat.data_1.5-2
  [7] farver_2.0.3             leiden_0.3.5             listenv_0.8.0
 [10] ggrepel_0.8.2            RSpectra_0.16-0          codetools_0.2-18
 [13] splines_4.0.3            polyclip_1.10-0          jsonlite_1.7.1
 [16] Rsamtools_2.6.0          Cairo_1.5-12.2           ica_1.0-2
 [19] cluster_2.1.0            png_0.1-7                shiny_1.5.0
 [22] sctransform_0.3.1        BiocManager_1.30.10      compiler_4.0.3
 [25] httr_1.4.2               fastmap_1.0.1            lazyeval_0.2.2
 [28] later_1.1.0.1            htmltools_0.5.0          tools_4.0.3
 [31] rsvd_1.0.3               igraph_1.2.6             gtable_0.3.0
 [34] glue_1.4.2               GenomeInfoDbData_1.2.4   RANN_2.6.1
 [37] reshape2_1.4.4           dplyr_1.0.2              Rcpp_1.0.5
 [40] spatstat_1.64-1          vctrs_0.3.5              rhdf5filters_1.2.0
 [43] nlme_3.1-150             lmtest_0.9-38            stringr_1.4.0
 [46] globals_0.13.1           mime_0.9                 miniUI_0.1.1.1
 [49] lifecycle_0.2.0          irlba_2.3.3              gtools_3.8.2
 [52] goftest_1.2-2            XML_3.99-0.5             future_1.20.1
 [55] zlibbioc_1.36.0          MASS_7.3-53              zoo_1.8-8
 [58] scales_1.1.1             promises_1.1.1           spatstat.utils_1.17-0
 [61] RColorBrewer_1.1-2       reticulate_1.18          pbapply_1.4-3
 [64] rpart_4.1-15             stringi_1.5.3            BiocParallel_1.24.1
 [67] rlang_0.4.8              pkgconfig_2.0.3          bitops_1.0-6
 [70] lattice_0.20-41          tensor_1.5               ROCR_1.0-11
 [73] purrr_0.3.4              Rhdf5lib_1.12.0          labeling_0.4.2
 [76] GenomicAlignments_1.26.0 patchwork_1.1.0          htmlwidgets_1.5.2
 [79] cowplot_1.1.0            tidyselect_1.1.0         parallelly_1.21.0
 [82] RcppAnnoy_0.0.17         plyr_1.8.6               R6_2.5.0
 [85] generics_0.1.0           DelayedArray_0.16.0      mgcv_1.8-33
 [88] pillar_1.4.6             withr_2.3.0              fitdistrplus_1.1-1
 [91] abind_1.4-5              survival_3.2-7           RCurl_1.98-1.2
 [94] tibble_3.0.4             future.apply_1.6.0       crayon_1.3.4
 [97] KernSmooth_2.23-18       plotly_4.9.2.1           digest_0.6.27
[100] xtable_1.8-4             tidyr_1.1.2              httpuv_1.5.4
[103] munsell_0.5.0            viridisLite_0.3.0

**Comment by markphillippebworth** [comment] 2020-11-18 10:34
I have the same exact issue. 

R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils    
 [8] datasets  methods   base     

other attached packages:
 [1] gtable_0.3.0                      uwot_0.1.9                       
 [3] gridExtra_2.3                     nabor_0.5.0                      
 [5] BSgenome.Hsapiens.UCSC.hg38_1.4.3 BSgenome_1.56.0                  
 [7] rtracklayer_1.48.0                Biostrings_2.56.0                
 [9] XVector_0.28.0                    forcats_0.5.0                    
[11] stringr_1.4.0                     dplyr_1.0.2                      
[13] purrr_0.3.4                       readr_1.4.0                      
[15] tidyr_1.1.2                       tibble_3.0.4                     
[17] tidyverse_1.3.0                   ggridges_0.5.2                   
[19] Seurat_3.2.2                      pheatmap_1.0.12                  
[21] ArchR_1.0.0                       magrittr_1.5                     
[23] rhdf5_2.32.4                      Matrix_1.2-18                    
[25] data.table_1.13.2                 SummarizedExperiment_1.18.2      
[27] DelayedArray_0.14.1               matrixStats_0.57.0               
[29] Biobase_2.48.0                    GenomicRanges_1.40.0             
[31] GenomeInfoDb_1.24.2               IRanges_2.22.2                   
[33] S4Vectors_0.26.1                  BiocGenerics_0.34.0              
[35] ggplot2_3.3.2                    

loaded via a namespace (and not attached):
  [1] readxl_1.3.1             backports_1.2.0          plyr_1.8.6              
  [4] igraph_1.2.5             lazyeval_0.2.2           splines_4.0.2           
  [7] BiocParallel_1.22.0      listenv_0.8.0            digest_0.6.27           
 [10] htmltools_0.5.0          fansi_0.4.1              tensor_1.5              
 [13] cluster_2.1.0            ROCR_1.0-11              globals_0.13.1          
 [16] modelr_0.1.8             colorspace_2.0-0         blob_1.2.1              
 [19] rvest_0.3.6              rappdirs_0.3.1           ggrepel_0.8.2           
 [22] haven_2.3.1              crayon_1.3.4             RCurl_1.98-1.2          
 [25] jsonlite_1.7.1           spatstat_1.64-1          spatstat.data_1.4-3     
 [28] survival_3.2-3           zoo_1.8-8                glue_1.4.2              
 [31] polyclip_1.10-0          zlibbioc_1.34.0          leiden_0.3.3            
 [34] Rhdf5lib_1.10.1          future.apply_1.6.0       abind_1.4-5             
 [37] scales_1.1.1             DBI_1.1.0                miniUI_0.1.1.1          
 [40] Rcpp_1.0.5               viridisLite_0.3.0        xtable_1.8-4            
 [43] reticulate_1.16          rsvd_1.0.3               htmlwidgets_1.5.2       
 [46] httr_1.4.2               RColorBrewer_1.1-2       ellipsis_0.3.1          
 [49] ica_1.0-2                farver_2.0.3             XML_3.99-0.5            
 [52] pkgconfig_2.0.3          dbplyr_1.4.4             deldir_0.1-29           
 [55] labeling_0.4.2           tidyselect_1.1.0         rlang_0.4.8             
 [58] reshape2_1.4.4           later_1.1.0.1            munsell_0.5.0           
 [61] cellranger_1.1.0         tools_4.0.2              cli_2.1.0               
 [64] generics_0.1.0           broom_0.7.0              fastmap_1.0.1           
 [67] goftest_1.2-2            fs_1.5.0                 fitdistrplus_1.1-1      
 [70] RANN_2.6.1               pbapply_1.4-3            future_1.20.1           
 [73] nlme_3.1-149             mime_0.9                 xml2_1.3.2              
 [76] compiler_4.0.2           rstudioapi_0.13          plotly_4.9.2.1          
 [79] png_0.1-7                spatstat.utils_1.17-0    reprex_0.3.0            
 [82] stringi_1.5.3            ps_1.4.0                 RSpectra_0.16-0         
 [85] lattice_0.20-41          vctrs_0.3.4              pillar_1.4.6            
 [88] lifecycle_0.2.0          lmtest_0.9-38            RcppAnnoy_0.0.17        
 [91] cowplot_1.1.0            bitops_1.0-6             irlba_2.3.3             
 [94] httpuv_1.5.4             patchwork_1.0.1          R6_2.5.0                
 [97] promises_1.1.1           KernSmooth_2.23-17       parallelly_1.21.0       
[100] codetools_0.2-16         gtools_3.8.2             MASS_7.3-53             
[103] assertthat_0.2.1         withr_2.3.0              GenomicAlignments_1.24.0
[106] Rsamtools_2.4.0          sctransform_0.3.1        GenomeInfoDbData_1.2.3  
[109] mgcv_1.8-33              hms_0.5.3                rpart_4.1-15            
[112] Cairo_1.5-12.2           Rtsne_0.15               shiny_1.5.0             
[115] lubridate_1.7.9

**Comment by rcorces** [comment] 2020-11-18 14:52
As suggested in #386 - this is some error or incompatibility with the new version of `uwot`
So I would suggest troubleshooting getting the old version of uwot properly installed and post on their github for whatever help you need.

We will separately look into whether there is anything that can be done within ArchR to prevent the error but this will take time.

**Comment by rcorces** [comment] 2020-11-18 15:00
Looking at the `uwot` source, it looks like this is an incompatibility.
@jgranja24 - Not sure how we want to handle this. Unless I'm mistaken, the old version 0.1.8 of uwot uses
`model$nn_index$save`
and the new version 0.1.9
`model$nn_index$ann$save`

Shown in this `uwot` commit -
https://github.com/jlmelville/uwot/commit/ef1978f26c069b8c97ee6e7c219e6765ab9ecfcc

**Comment by coffeeCowLu** [comment] 2020-11-18 16:30
I have tested old version 0.1.8 of uwot can solve it!

**Comment by fkeramati** [comment] 2020-11-19 23:41
> I have tested old version 0.1.8 of uwot can solve it!

Hi,
I'm also having the same problem! :-(

How did you mange to install 0.1.8 uwot? I can't because of Rcpp and RcppAnnoy problems!!! I'm using mac OS Catalina!!!
https://github.com/jlmelville/uwot/issues/54

This problem has halted all of my analysis workflow!!

Thanks

**Comment by coffeeCowLu** [comment] 2020-11-20 02:05
> > I have tested old version 0.1.8 of uwot can solve it!
> 
> Hi,
> I'm also having the same problem! :-(
> 
> How did you mange to install 0.1.8 uwot? I can't because of Rcpp and RcppAnnoy problems!!! I'm using mac OS Catalina!!!
> [jlmelville/uwot#54](https://github.com/jlmelville/uwot/issues/54)
> 
> This problem has halted all of my analysis workflow!!
> 
> Thanks

hi, have you finished your problems?

i dowload uwot :https://cran.r-project.org/src/contrib/Archive/uwot/uwot_0.1.8.tar.gz' , and installed it by install.packages('yourDownLoadPath/uwot_0.1.8.gz').

If you need a dependency package, you need to install the dependency first.

If the conventional installation method fails, it is usually solved through git installation, by devtools::install_git() or devtools::install_local().

best wishes.

**Comment by coffeeCowLu** [comment] 2020-11-20 02:40
> > > I have tested old version 0.1.8 of uwot can solve it!
> > 
> > 
> > Hi,
> > I'm also having the same problem! :-(
> > How did you mange to install 0.1.8 uwot? I can't because of Rcpp and RcppAnnoy problems!!! I'm using mac OS Catalina!!!
> > [jlmelville/uwot#54](https://github.com/jlmelville/uwot/issues/54)
> > This problem has halted all of my analysis workflow!!
> > Thanks
> 
> hi, have you finished your problems?
> you can use devtools::install_version("uwot", version = "0.1.8") to install uwot.
> best wishes.

**Comment by jlmelville** [comment] 2020-11-20 05:42
Hello, I am the maintainer of **uwot**. I am sorry the 0.1.9 release has broken people's workflows (I don't think I was aware of the existence of **ArchR** until now).

Probably there has been a failure of API communication on my part: the UMAP `model` produced by `uwot::umap` and the like should be considered to be completely opaque and can change at any time. Its contents are left undocumented on purpose (I will explicitly note this in future releases). In general, only *calling* the functions exported by the `NAMESPACE` file should be considered stable, so I also can't promise the model contents (and the implementation of `load_uwot` and `save_uwot`) won't change further in the future. It's probable that these *will* be subject to future change, because the nearest neighbor performance is the least satisfactory part of **uwot** at the moment.

Could someone open an issue at <https://github.com/jlmelville/uwot/issues> and help me understand what the use case/requirements are for `.saveUWOT` and `.loadUWOT`, i.e. what are the deficiencies with `uwot::load_uwot` and `uwot::save_uwot`? Perhaps we can work out how to extract some common code to make `.saveUWOT` and `.loadUWOT` less reliant on the internals of the model with future versions of **uwot**.

For the current issue, I think you could have a (admittedly verbose) workaround where you do something like:

```R
if (!is.null(model$nn_index$ann)) {
  # use the same code as you currently have but with the $ann$ sandwiched in between
}
else {
  # a model from a pre-0.1.9 version of uwot so you can use the current code as-is
}
```

**Comment by fkeramati** [comment] 2020-11-20 07:57
> > > I have tested old version 0.1.8 of uwot can solve it!
> > 
> > 
> > Hi,
> > I'm also having the same problem! :-(
> > How did you mange to install 0.1.8 uwot? I can't because of Rcpp and RcppAnnoy problems!!! I'm using mac OS Catalina!!!
> > [jlmelville/uwot#54](https://github.com/jlmelville/uwot/issues/54)
> > This problem has halted all of my analysis workflow!!
> > Thanks
> 
> hi, have you finished your problems?
> 
> you can use devtools::install_version("uwot", version = "0.1.8") to install uwot.
> 
> best wishes.

Hi,
I've already tried this and unfortunately this does not work on mac!
In the recent couple of days both Rcpp and RcppAnnoy have also been updated, and now it is impossible to install older versions of uwot because of RcppAnnoy error!!

`In file included from nn_parallel.cpp:6:
./nn_parallel.h:68:3: error: too few template arguments for class template 'AnnoyIndex'
  AnnoyIndex<typename UwotAnnoyDistance::S, typename UwotAnnoyDistance::T,
  ^
/Users/faridkeramati/Library/R/4.0/library/RcppAnnoy/include/annoylib.h:845:9: note: template is declared here
  class AnnoyIndex : public AnnoyIndexInterface<S, T> {
        ^
1 error generated.
make: *** [nn_parallel.o] Error 1
ERROR: compilation failed for package ‘uwot’`

This is the last statement generated when I tried to install older version of uwot!

**Comment by rcorces** [comment] 2020-11-20 14:14
@jlmelville - Thanks! We will follow up soon.

**Comment by jlmelville** [comment] 2020-11-20 16:58
@fkeramati oh yeah, the reason for the new version of **uwot** was to allow a change in **RcppAnnoy**. So if you want to install uwot 0.1.8 you will also need to install RcppAnnoy 0.0.16.

**Comment by sylestiel** [comment] 2020-11-20 18:12
1 error generated.
make: *** [nn_parallel.o] Error 1
ERROR: compilation failed for package ‘uwot’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/uwot’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/uwot’
Error: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package ‘/var/folders/2c/zzjsgs_53vqflzjl28hf1x7r0000gn/T//Rtmpk03wA7/remotes169bc1fbd219/uwot’ had non-zero exit status

**Comment by cb4github** [comment] 2020-11-20 19:41
@rcorces, @jlmelville Many thanks for your ongoing efforts!
@sylestiel I confirmed success with the following on macOS Catalina Version 10.15.7, R.version 4.03

> install.packages("devtools")
> devtools::install_version("RcppAnnoy", version = "0.0.16") #needed to remove/rename my file ~/.R/Makevars for this to work
> devtools::install_version("uwot", version = "0.1.8")
> 

Best,
CB

**Comment by sylestiel** [comment] 2020-11-20 20:52
Addressed! Thanks CB for your help.

**Comment by fkeramati** [comment] 2020-11-22 15:02
> @rcorces, @jlmelville Many thanks for your ongoing efforts!
> @sylestiel I confirmed success with the following on macOS Catalina Version 10.15.7, R.version 4.03
> 
> > install.packages("devtools")
> > devtools::install_version("RcppAnnoy", version = "0.0.16") #needed to remove/rename my file ~/.R/Makevars for this to work
> > devtools::install_version("uwot", version = "0.1.8") #Note - when prompted to update packages, answer 3 (None) - thus avoiding replacing RcppAnnoy v0.0.16 with v0.0.17
> 
> Best,
> CB

This also worked for me! Thanks a lot.

**Comment by jgranja24** [comment] 2020-11-23 03:09
Hi All, Ive updated both .saveUWOT and .loadUWOT to better handle the newer versions from @jlmelville as follows.
By default it will try the normal save/load_uwot and if that fails try the previous save/loadUWOT which will be
further deprecated

These fixes are available in the release 1.0.1 branch.

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories())
`

in essence -

```
.saveUWOT <- function(model, file){
  tryCatch({
    uwot::save_uwot(model = model, file = file, verbose = TRUE)
  }, error = function(e){
    .saveUWOT_Deprecated(model = model, file = file) #backwards to previous version
  })
}
```

and

```
.loadUWOT <- function(file){
  tryCatch({
    uwot::load_uwot(file = file, verbose = TRUE)
  }, error = function(e){
    .loadUWOT_Deprecated(file = file, nDim = nDim) #backwards to previous version
  })
}
```

@jlmelville I ran into previous issues a while back with save_uwot being that the utils::tar was having permissions issues on Stanford's compute server vs calling the console with system. Additionally, I believe I found a weird bug with the dimensionality of load_uwot. I meant to create an issue but at the time I was a bit overwhelmed with things. If the errors re-appear from users Ill post them in uwots github. 

Hi @bioinfo-sc, @markphillippebworth, @coffeeCowLu, @sylestiel, @cb4github, @fkeramati, please let me know if the new branch solves your issues and let us know if you have any other further issues!

Thanks for the help!

Jeff

**Comment by jlmelville** [comment] 2020-11-23 04:47
> @jlmelville I ran into previous issues a while back with save_uwot being that the utils::tar was having permissions issues on Stanford's compute server vs calling the console with system. Additionally, I believe I found a weird bug with the dimensionality of load_uwot. I meant to create an issue but at the time I was a bit overwhelmed with things. If the errors re-appear from users Ill post them in uwots github.

@jgranja24 there was a bug in uwot until fairly recently where the dimensionality of Annoy nearest neighbor model wasn't being saved, which lead to an error when trying load the index. You might have run into that (or changes to the internals after the fix happened). Please do report an issue if it comes up again.

**Comment by edencru** [comment] 2020-11-26 00:52
Hi, 

I am getting this same error.  I tried installing version 0.0.16 of RcppAnnoy and version 0.1.8 of uwot, but it didn't fix the problem. I also tried installing the newest release of ArchR (as noted above), but still get the same error.

Best,

**Comment by rcorces** [comment] 2020-11-26 02:09
@edencru - That does not sound right. Please show the command you are running, the corresponding error message, and the output of `sessionInfo()`

**Comment by edencru** [comment] 2020-11-26 02:16
@rcorces I think I got it resolved. I re-installed the newest ArchR release and rebooted. Now it seems to be working! Thank you for your quick response. 

Best, 
EC

**Comment by jgranja24** [comment] 2020-11-26 04:50
Closing this issue, feel free to open a new issue if this persists! 

Best

Jeff

**Closed by jgranja24** 2020-11-26 04:50 UTC
Labels: bug
